<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="">

<title>Regression and Classification Trees – Worked Examples in R</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-12757e4b7af482b2d9c5bd8860d2b707.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-b2ec79424e20c0f1fec78fa60be5e1fa.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Worked Examples in R</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-machine-learning" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Machine learning</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-machine-learning">    
        <li>
    <a class="dropdown-item" href="./EXAMPLE_DECISION_TREE.html">
 <span class="dropdown-text">Regression and Classification Trees</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./EXAMPLE_LDA.html">
 <span class="dropdown-text">Linear Discriminant Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./EXAMPLE_MNIST.html">
 <span class="dropdown-text">MNIST in Keras</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./EXAMPLE_REGULARIZED_REGRESSION.html">
 <span class="dropdown-text">Regularized Regression: Ridge, Heteroscedastic Ridge, Lasso, and Elastic Net</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-psychometrics" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Psychometrics</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-psychometrics">    
        <li>
    <a class="dropdown-item" href="./EXAMPLE_MEASUREMENT_INVARIANCE.html">
 <span class="dropdown-text">Measurement invariance</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./EXAMPLE_MULTITRAIT_MULTIMETHOD.html">
 <span class="dropdown-text">Multitrait Multimethod</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./EXAMPLE_TIRT.html">
 <span class="dropdown-text">Thurstonian IRT Example</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./EXAMPLE_TIRT_SCORING_GR.html">
 <span class="dropdown-text">Βαθμολόγηση Thurstonian IRT — Θεωρία</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-adaptive-testing" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Adaptive testing</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-adaptive-testing">    
        <li>
    <a class="dropdown-item" href="./EXAMPLE_MSTR.html">
 <span class="dropdown-text">MST</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./EXAMPLE_SIMULATION_catR.html">
 <span class="dropdown-text">CAT Simulation</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-statistics" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Statistics</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-statistics">    
        <li>
    <a class="dropdown-item" href="./EXAMPLE_GENERALIZED.html">
 <span class="dropdown-text">Generalized Linear Models</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./EXAMPLE_PARADOX.html">
 <span class="dropdown-text">A Gallery of Statistical Paradoxes</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/sedzinfo/vignettes"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#description" id="toc-description" class="nav-link active" data-scroll-target="#description">Description</a></li>
  <li><a href="#theoretical-background" id="toc-theoretical-background" class="nav-link" data-scroll-target="#theoretical-background">Theoretical Background</a>
  <ul class="collapse">
  <li><a href="#recursive-partitioning" id="toc-recursive-partitioning" class="nav-link" data-scroll-target="#recursive-partitioning">Recursive partitioning</a></li>
  <li><a href="#splitting-criteria" id="toc-splitting-criteria" class="nav-link" data-scroll-target="#splitting-criteria">Splitting criteria</a></li>
  <li><a href="#cost-complexity-pruning" id="toc-cost-complexity-pruning" class="nav-link" data-scroll-target="#cost-complexity-pruning">Cost-complexity pruning</a></li>
  <li><a href="#cross-validated-tree-size" id="toc-cross-validated-tree-size" class="nav-link" data-scroll-target="#cross-validated-tree-size">Cross-validated tree size</a></li>
  <li><a href="#variable-importance" id="toc-variable-importance" class="nav-link" data-scroll-target="#variable-importance">Variable importance</a></li>
  </ul></li>
  <li><a href="#rpart-classification" id="toc-rpart-classification" class="nav-link" data-scroll-target="#rpart-classification">Rpart Classification</a>
  <ul class="collapse">
  <li><a href="#growing-and-pruning-the-tree" id="toc-growing-and-pruning-the-tree" class="nav-link" data-scroll-target="#growing-and-pruning-the-tree">Growing and pruning the tree</a></li>
  <li><a href="#variable-importance-1" id="toc-variable-importance-1" class="nav-link" data-scroll-target="#variable-importance-1">Variable importance</a></li>
  <li><a href="#the-full-unpruned-tree" id="toc-the-full-unpruned-tree" class="nav-link" data-scroll-target="#the-full-unpruned-tree">The full, unpruned tree</a></li>
  <li><a href="#choosing-the-tree-size-via-cross-validation" id="toc-choosing-the-tree-size-via-cross-validation" class="nav-link" data-scroll-target="#choosing-the-tree-size-via-cross-validation">Choosing the tree size via cross-validation</a></li>
  <li><a href="#error-by-size-summary" id="toc-error-by-size-summary" class="nav-link" data-scroll-target="#error-by-size-summary">Error-by-size summary</a></li>
  <li><a href="#the-pruned-tree-diagram" id="toc-the-pruned-tree-diagram" class="nav-link" data-scroll-target="#the-pruned-tree-diagram">The pruned tree diagram</a></li>
  <li><a href="#raw-model-components" id="toc-raw-model-components" class="nav-link" data-scroll-target="#raw-model-components">Raw model components</a></li>
  </ul></li>
  <li><a href="#rpart-regression" id="toc-rpart-regression" class="nav-link" data-scroll-target="#rpart-regression">Rpart Regression</a>
  <ul class="collapse">
  <li><a href="#growing-and-pruning-the-tree-1" id="toc-growing-and-pruning-the-tree-1" class="nav-link" data-scroll-target="#growing-and-pruning-the-tree-1">Growing and pruning the tree</a></li>
  <li><a href="#variable-importance-2" id="toc-variable-importance-2" class="nav-link" data-scroll-target="#variable-importance-2">Variable importance</a></li>
  <li><a href="#the-full-unpruned-tree-1" id="toc-the-full-unpruned-tree-1" class="nav-link" data-scroll-target="#the-full-unpruned-tree-1">The full, unpruned tree</a></li>
  <li><a href="#choosing-the-tree-size-via-cross-validation-1" id="toc-choosing-the-tree-size-via-cross-validation-1" class="nav-link" data-scroll-target="#choosing-the-tree-size-via-cross-validation-1">Choosing the tree size via cross-validation</a></li>
  <li><a href="#error-by-size-summary-1" id="toc-error-by-size-summary-1" class="nav-link" data-scroll-target="#error-by-size-summary-1">Error-by-size summary</a></li>
  <li><a href="#the-pruned-tree-diagram-1" id="toc-the-pruned-tree-diagram-1" class="nav-link" data-scroll-target="#the-pruned-tree-diagram-1">The pruned tree diagram</a></li>
  <li><a href="#raw-model-components-1" id="toc-raw-model-components-1" class="nav-link" data-scroll-target="#raw-model-components-1">Raw model components</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Regression and Classification Trees</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="description" class="level2">
<h2 class="anchored" data-anchor-id="description">Description</h2>
<p>This page reproduces the steps of rwf’s <code>report_rtree()</code> using <code>rpart</code> directly; both models are fit on the training part of the first of 10 folds created by rwf’s <code>k_fold()</code>. Installation instructions for rwf can be found <a href="https://github.com/sedzinfo/rwf">here</a> <code>report_rtree()</code> is not installed by default; it is in /rwf/working_functions/OTHER/ML_TREE_RPART.R</p>
</section>
<section id="theoretical-background" class="level2">
<h2 class="anchored" data-anchor-id="theoretical-background">Theoretical Background</h2>
<section id="recursive-partitioning" class="level3">
<h3 class="anchored" data-anchor-id="recursive-partitioning">Recursive partitioning</h3>
<p><code>rpart</code> implements <strong>CART</strong> (Classification and Regression Trees, Breiman et al., 1984). Starting from the full dataset at the root node, the algorithm searches every predictor and every possible split point on that predictor, and picks the single split that most improves node purity. Each resulting child node is then split again, recursively, until a stopping rule is reached (a minimum number of observations per node, a minimum improvement threshold, or a maximum depth). The result is a <strong>binary tree</strong>: every internal node asks a yes/no question about one predictor, and every terminal node (“leaf”) gives a prediction.</p>
</section>
<section id="splitting-criteria" class="level3">
<h3 class="anchored" data-anchor-id="splitting-criteria">Splitting criteria</h3>
<p>The measure of “improvement” depends on the outcome type:</p>
<ul>
<li><strong>Classification</strong> (<code>method = "class"</code>, used below for <code>case</code>) — by default <code>rpart</code> uses the <strong>Gini impurity</strong> of the class distribution within a node; a split is chosen to make the two child nodes as class-pure as possible.</li>
<li><strong>Regression</strong> (<code>method = "anova"</code>, used below for <code>medv</code>) — the criterion is the reduction in <strong>within-node sum of squares</strong>, i.e.&nbsp;the split that most reduces the variance of the outcome within each child node.</li>
</ul>
</section>
<section id="cost-complexity-pruning" class="level3">
<h3 class="anchored" data-anchor-id="cost-complexity-pruning">Cost-complexity pruning</h3>
<p>A tree grown to full depth almost always <strong>overfits</strong> — it captures noise along with signal. <code>rpart</code> addresses this with <strong>cost-complexity pruning</strong>: every subtree <span class="math inline">\(T\)</span> is scored as</p>
<p><span class="math display">\[R_\alpha(T) = R(T) + \alpha \, |T|\]</span></p>
<p>where <span class="math inline">\(R(T)\)</span> is the tree’s error (relative to the root), <span class="math inline">\(|T|\)</span> is the number of terminal nodes, and <span class="math inline">\(\alpha\)</span> (called <code>CP</code> in <code>rpart</code>’s output) penalizes tree size. Varying <span class="math inline">\(\alpha\)</span> from 0 to 1 produces a nested sequence of subtrees, from the grown tree (stopped at <code>rpart</code>’s default <code>cp = 0.01</code>) down to a single root node — this sequence is stored in <code>model$cptable</code>.</p>
</section>
<section id="cross-validated-tree-size" class="level3">
<h3 class="anchored" data-anchor-id="cross-validated-tree-size">Cross-validated tree size</h3>
<p>Because the <em>apparent</em> error of a tree always decreases as it grows (a larger tree can always fit the training data at least as well), <code>rpart</code> estimates each subtree’s error via internal <strong>k-fold cross-validation</strong>. <code>cptable</code> reports, for every candidate <code>CP</code> value: the relative error on the training data (<code>rel error</code>), the cross-validated error (<code>xerror</code>), and its standard deviation (<code>xstd</code>). The code below selects the tree whose <code>CP</code> gives the <strong>minimum <code>xerror</code></strong> — a common, more conservative alternative is the “1-SE rule” (the smallest tree whose <code>xerror</code> is within one standard error of the minimum), which favors a simpler tree.</p>
</section>
<section id="variable-importance" class="level3">
<h3 class="anchored" data-anchor-id="variable-importance">Variable importance</h3>
<p>A predictor’s importance is the sum of the goodness-of-split (improvement in Gini impurity for classification, or in sum-of-squares for regression) for every split where it is the <em>primary</em> splitter, plus, for every split where it serves as a <strong>surrogate</strong> (a stand-in used when the primary splitting variable is missing), the primary split’s improvement weighted by the surrogate’s adjusted agreement. This is why a variable can show non-trivial importance even if it never appears as a labeled split in the final tree diagram.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>infert_formula<span class="ot">&lt;-</span><span class="fu">formula</span>(<span class="fu">factor</span>(case)<span class="sc">~</span>age<span class="sc">+</span>parity<span class="sc">+</span>education<span class="sc">+</span>spontaneous<span class="sc">+</span>induced)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>boston_formula<span class="ot">&lt;-</span><span class="fu">formula</span>(<span class="fu">c</span>(<span class="st">"medv~"</span>,<span class="fu">paste</span>(<span class="fu">names</span>(MASS<span class="sc">::</span>Boston)[<span class="dv">1</span><span class="sc">:</span><span class="dv">13</span>],<span class="at">collapse=</span><span class="st">"+"</span>)))</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(infert_formula)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>factor(case) ~ age + parity + education + spontaneous + induced</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(boston_formula)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>medv ~ crim + zn + indus + chas + nox + rm + age + dis + rad + 
    tax + ptratio + black + lstat</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># kfolding (seed fixed so folds, rpart's internal cross-validation and the prose below are reproducible)</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>train_test_classification<span class="ot">&lt;-</span><span class="fu">k_fold</span>(<span class="at">df=</span>infert,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">model_formula=</span>infert_formula)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Fold Cases: 1 Train: 223 Test: 25 Total: 248 Unique Train: 223 Unique Test: 25 
Fold Cases: 2 Train: 223 Test: 25 Total: 248 Unique Train: 223 Unique Test: 25 
Fold Cases: 3 Train: 223 Test: 25 Total: 248 Unique Train: 223 Unique Test: 25 
Fold Cases: 4 Train: 224 Test: 24 Total: 248 Unique Train: 224 Unique Test: 24 
Fold Cases: 5 Train: 223 Test: 25 Total: 248 Unique Train: 223 Unique Test: 25 
Fold Cases: 6 Train: 223 Test: 25 Total: 248 Unique Train: 223 Unique Test: 25 
Fold Cases: 7 Train: 224 Test: 24 Total: 248 Unique Train: 224 Unique Test: 24 
Fold Cases: 8 Train: 223 Test: 25 Total: 248 Unique Train: 223 Unique Test: 25 
Fold Cases: 9 Train: 223 Test: 25 Total: 248 Unique Train: 223 Unique Test: 25 
Fold Cases: 10 Train: 223 Test: 25 Total: 248 Unique Train: 223 Unique Test: 25 </code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>train_test_regression<span class="ot">&lt;-</span><span class="fu">k_fold</span>(<span class="at">df=</span>MASS<span class="sc">::</span>Boston,</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">model_formula=</span>boston_formula)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Fold Cases: 1 Train: 455 Test: 51 Total: 506 Unique Train: 455 Unique Test: 51 
Fold Cases: 2 Train: 455 Test: 51 Total: 506 Unique Train: 455 Unique Test: 51 
Fold Cases: 3 Train: 456 Test: 50 Total: 506 Unique Train: 456 Unique Test: 50 
Fold Cases: 4 Train: 455 Test: 51 Total: 506 Unique Train: 455 Unique Test: 51 
Fold Cases: 5 Train: 456 Test: 50 Total: 506 Unique Train: 456 Unique Test: 50 
Fold Cases: 6 Train: 455 Test: 51 Total: 506 Unique Train: 455 Unique Test: 51 
Fold Cases: 7 Train: 456 Test: 50 Total: 506 Unique Train: 456 Unique Test: 50 
Fold Cases: 8 Train: 455 Test: 51 Total: 506 Unique Train: 455 Unique Test: 51 
Fold Cases: 9 Train: 456 Test: 50 Total: 506 Unique Train: 456 Unique Test: 50 
Fold Cases: 10 Train: 455 Test: 51 Total: 506 Unique Train: 455 Unique Test: 51 </code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># rpart models</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>rtree_classification<span class="ot">&lt;-</span>rpart<span class="sc">::</span><span class="fu">rpart</span>(infert_formula,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>                                   train_test_classification<span class="sc">$</span>f<span class="sc">$</span>train<span class="sc">$</span>f1,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">model=</span><span class="cn">TRUE</span>,<span class="at">x=</span><span class="cn">TRUE</span>,<span class="at">y=</span><span class="cn">TRUE</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>rtree_regression<span class="ot">&lt;-</span>rpart<span class="sc">::</span><span class="fu">rpart</span>(boston_formula,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>                               train_test_regression<span class="sc">$</span>f<span class="sc">$</span>train<span class="sc">$</span>f1,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>                               <span class="at">model=</span><span class="cn">TRUE</span>,<span class="at">x=</span><span class="cn">TRUE</span>,<span class="at">y=</span><span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
</section>
<section id="rpart-classification" class="level2">
<h2 class="anchored" data-anchor-id="rpart-classification">Rpart Classification</h2>
<p>The classification tree predicts <code>case</code> (secondary infertility, from the classic <code>infert</code> case-control study) from <code>age</code>, <code>parity</code>, <code>education</code>, <code>spontaneous</code>, and <code>induced</code> (prior abortions).</p>
<section id="growing-and-pruning-the-tree" class="level3">
<h3 class="anchored" data-anchor-id="growing-and-pruning-the-tree">Growing and pruning the tree</h3>
<p><code>rtree_classification</code> was grown with rpart’s default stopping rules (<code>cp = 0.01</code>, <code>minsplit = 20</code>, <code>minbucket = 7</code>) in the <code>create_models</code> chunk above. Here it is pruned back to the <code>CP</code> value that minimizes the cross-validated error (<code>xerror</code>) in its <code>cptable</code>.</p>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>result<span class="ot">&lt;-</span><span class="fu">data.frame</span>(rtree_classification<span class="sc">$</span>cptable)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>result<span class="sc">$</span>nsplit<span class="ot">&lt;-</span><span class="fu">factor</span>(result<span class="sc">$</span>nsplit<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>minimun_size<span class="ot">&lt;-</span><span class="fu">as.numeric</span>(<span class="fu">as.character</span>(result[<span class="fu">which.min</span>(result[,<span class="st">"xerror"</span>]),<span class="st">"nsplit"</span>]))</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>initial_model<span class="ot">&lt;-</span>rtree_classification</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>model<span class="ot">&lt;-</span>rpart<span class="sc">::</span><span class="fu">prune</span>(rtree_classification,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">cp=</span>rtree_classification<span class="sc">$</span>cptable[<span class="fu">which.min</span>(rtree_classification<span class="sc">$</span>cptable[,<span class="st">"xerror"</span>]),<span class="st">"CP"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="variable-importance-1" class="level3">
<h3 class="anchored" data-anchor-id="variable-importance-1">Variable importance</h3>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>importance<span class="ot">&lt;-</span>model<span class="sc">$</span>variable.importance</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>importance<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">names=</span><span class="fu">names</span>(importance),<span class="at">importance=</span>importance)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>importance<span class="sc">$</span>names<span class="ot">&lt;-</span><span class="fu">factor</span>(importance<span class="sc">$</span>names,<span class="at">levels=</span><span class="fu">rev</span>(<span class="fu">as.character</span>(importance<span class="sc">$</span>names)))</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>plot_importance<span class="ot">&lt;-</span><span class="fu">ggplot</span>(importance,<span class="fu">aes</span>(<span class="at">x=</span>names,<span class="at">y=</span>importance))<span class="sc">+</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">'identity'</span>)<span class="sc">+</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Importance Plot"</span>,<span class="at">y=</span><span class="st">"Importance (sum of split improvements)"</span>,<span class="at">x=</span><span class="st">"Predictor"</span>)<span class="sc">+</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size=</span><span class="dv">10</span>)<span class="sc">+</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits=</span><span class="fu">rev</span>(<span class="fu">levels</span>(names)))<span class="sc">+</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>plot_importance</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="EXAMPLE_DECISION_TREE_files/figure-html/classification_importance-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="2100"></p>
</figure>
</div>
</div>
</div>
<p>Longer bars mean the predictor contributed more to reducing impurity across the tree’s splits (as primary splitter or as a surrogate). Here <strong>spontaneous</strong> dominates (importance 13.01), followed by <strong>parity</strong> and <strong>age</strong>, with <strong>education</strong> contributing least. Note that <code>infert</code> is a matched case-control study in which cases and controls were matched on age, parity and education, so the substantive signal is in the prior-abortion variables (<code>spontaneous</code>, <code>induced</code>); splits on age or parity largely reflect sampling noise in this training fold.</p>
</section>
<section id="the-full-unpruned-tree" class="level3">
<h3 class="anchored" data-anchor-id="the-full-unpruned-tree">The full, unpruned tree</h3>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>rtree_classification</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>n= 223 

node), split, n, loss, yval, (yprob)
      * denotes terminal node

 1) root 223 72 0 (0.6771300 0.3228700)  
   2) spontaneous&lt; 0.5 128 24 0 (0.8125000 0.1875000) *
   3) spontaneous&gt;=0.5 95 47 1 (0.4947368 0.5052632)  
     6) parity&gt;=3.5 21  5 0 (0.7619048 0.2380952) *
     7) parity&lt; 3.5 74 31 1 (0.4189189 0.5810811)  
      14) age&lt; 30.5 40 17 0 (0.5750000 0.4250000)  
        28) spontaneous&lt; 1.5 28  9 0 (0.6785714 0.3214286) *
        29) spontaneous&gt;=1.5 12  4 1 (0.3333333 0.6666667) *
      15) age&gt;=30.5 34  8 1 (0.2352941 0.7647059) *</code></pre>
</div>
</div>
<p>This is the text representation of the tree <em>before</em> pruning — every line is one node: its splitting rule, the number of observations that reach it (<code>n</code>), the misclassification loss, and the predicted class with its probability. Compare its size to the pruned <code>model</code> used in the plots below: in this run the full tree has 5 terminal nodes and the pruned tree 5. When the minimum <code>xerror</code> occurs at the largest tree in the <code>cptable</code>, pruning leaves the tree unchanged; with other data or a smaller <code>cp</code>, pruning would collapse some of these nodes.</p>
</section>
<section id="choosing-the-tree-size-via-cross-validation" class="level3">
<h3 class="anchored" data-anchor-id="choosing-the-tree-size-via-cross-validation">Choosing the tree size via cross-validation</h3>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>rpart<span class="sc">::</span><span class="fu">plotcp</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="EXAMPLE_DECISION_TREE_files/figure-html/classification_cv_size-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="2100"></p>
</figure>
</div>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>rpart<span class="sc">::</span><span class="fu">rsq.rpart</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
rpart::rpart(formula = infert_formula, data = train_test_classification$f$train$f1, 
    model = TRUE, x = TRUE, y = TRUE)

Variables actually used in tree construction:
[1] age         parity      spontaneous

Root node error: 72/223 = 0.32287

n= 223 

        CP nsplit rel error  xerror     xstd
1 0.083333      0   1.00000 1.00000 0.096977
2 0.055556      3   0.75000 1.00000 0.096977
3 0.010000      4   0.69444 0.86111 0.092923</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="EXAMPLE_DECISION_TREE_files/figure-html/classification_cv_size-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="2100"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="EXAMPLE_DECISION_TREE_files/figure-html/classification_cv_size-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="2100"></p>
</figure>
</div>
</div>
</div>
<p><code>plotcp()</code> plots cross-validated <strong>relative error</strong> (<code>xerror</code>, with one-SE error bars) against <code>CP</code> (bottom axis) and tree size (top axis) — the dotted horizontal line marks one standard error above the minimum, the usual reference for the “1-SE rule”. <code>rsq.rpart()</code> prints the <code>cptable</code> and adds two more panels: apparent vs.&nbsp;cross-validated <strong>R-squared</strong>, and cross-validated <strong>relative error</strong>, against the number of splits. Because this is a <em>classification</em> tree, these values are 1 minus the relative misclassification error (relative to the root node’s error of 72/223), not explained variance, so read them as relative predictive error rather than a literal R²; <code>rsq.rpart()</code> itself warns that it “may not be applicable for this method”. Here cross-validated error drops only from 1.00 to 0.86 of the root error (about 28% vs 32% misclassification) and is lowest at the largest tree in the <code>cptable</code>, which is why the minimum-<code>xerror</code> rule keeps the full tree.</p>
</section>
<section id="error-by-size-summary" class="level3">
<h3 class="anchored" data-anchor-id="error-by-size-summary">Error-by-size summary</h3>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>error<span class="ot">&lt;-</span><span class="fu">data.frame</span>(model<span class="sc">$</span>cptable)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>error<span class="sc">$</span>nsplit<span class="ot">&lt;-</span><span class="fu">factor</span>(error<span class="sc">$</span>nsplit<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>tree_size<span class="ot">&lt;-</span>error[<span class="fu">which.min</span>(error[,<span class="st">"xerror"</span>]),<span class="st">"nsplit"</span>]</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>error<span class="ot">&lt;-</span>reshape2<span class="sc">::</span><span class="fu">melt</span>(error,<span class="at">id.vars=</span><span class="st">"nsplit"</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(error)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"Split"</span>,<span class="st">"Metric"</span>,<span class="st">"value"</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>plot_prune<span class="ot">&lt;-</span><span class="fu">ggplot</span>(error,<span class="fu">aes</span>(<span class="at">x=</span>Split,<span class="at">y=</span>value,<span class="at">color=</span>Metric))<span class="sc">+</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group=</span>Metric))<span class="sc">+</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="fu">paste</span>(<span class="st">"Error Plot"</span>,<span class="st">"Suggested Size:"</span>,tree_size),<span class="at">y=</span><span class="st">"Metric value"</span>,<span class="at">x=</span><span class="st">"Size of Tree"</span>)<span class="sc">+</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size=</span><span class="dv">10</span>)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>plot_prune</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="EXAMPLE_DECISION_TREE_files/figure-html/classification_prune_plot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="2100"></p>
</figure>
</div>
</div>
</div>
<p>This re-plots all four <code>cptable</code> columns (<code>CP</code>, <code>rel error</code>, <code>xerror</code>, <code>xstd</code>) on one axis against tree size (number of terminal nodes = <code>nsplit + 1</code>), from a single node onward. The title reports the tree size at which <code>xerror</code> is minimized — the size the pruned <code>model</code> retains (here 5 terminal nodes, i.e.&nbsp;the full tree).</p>
</section>
<section id="the-pruned-tree-diagram" class="level3">
<h3 class="anchored" data-anchor-id="the-pruned-tree-diagram">The pruned tree diagram</h3>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>rpart.plot<span class="sc">::</span><span class="fu">rpart.plot</span>(model,<span class="at">type=</span><span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="EXAMPLE_DECISION_TREE_files/figure-html/classification_final_tree-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="2100"></p>
</figure>
</div>
</div>
</div>
<p>Each box is a node showing the predicted class (top), the fitted probability that <code>case = 1</code> (middle), and the percentage of the training sample in that node (bottom). Following the branches down from the root shows the sequence of yes/no rules — here the splits use, in order from the root, spontaneous, parity, age: first whether the woman had any prior spontaneous abortion, then parity, then age — that separate higher- from lower-risk groups.</p>
</section>
<section id="raw-model-components" class="level3">
<h3 class="anchored" data-anchor-id="raw-model-components">Raw model components</h3>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>frame<span class="ot">&lt;-</span><span class="fu">data.frame</span>(model<span class="sc">$</span>frame)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>cp<span class="ot">&lt;-</span><span class="fu">data.frame</span>(model<span class="sc">$</span>cptable)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>parameters<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">parameters=</span><span class="fu">unlist</span>(model<span class="sc">$</span>control))</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>splits<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">name=</span><span class="fu">row.names</span>(model<span class="sc">$</span>splits),model<span class="sc">$</span>splits,<span class="at">row.names=</span><span class="cn">NULL</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>importance<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">importance=</span>model<span class="sc">$</span>variable.importance)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>ordered<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">ordered=</span>model<span class="sc">$</span>ordered)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">y=</span>model<span class="sc">$</span>y,<span class="at">x=</span>model<span class="sc">$</span>x,<span class="at">model=</span>model<span class="sc">$</span>model)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>call<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">call=</span><span class="fu">call_to_string</span>(model))</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>result<span class="ot">&lt;-</span><span class="fu">list</span>(<span class="at">frame=</span>frame,<span class="at">cp=</span>cp,<span class="at">parameters=</span>parameters,<span class="at">splits=</span>splits,<span class="at">importance=</span>importance,<span class="at">ordered=</span>ordered,<span class="at">call=</span>call)</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(result)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>$frame
           var   n  wt dev yval complexity ncompete nsurrogate     yval2.V1     yval2.V2     yval2.V3     yval2.V4     yval2.V5 yval2.nodeprob
1  spontaneous 223 223  72    1 0.08333333        4          3   1.00000000 151.00000000  72.00000000   0.67713004   0.32286996     1.00000000
2       &lt;leaf&gt; 128 128  24    1 0.00000000        0          0   1.00000000 104.00000000  24.00000000   0.81250000   0.18750000     0.57399103
3       parity  95  95  47    2 0.08333333        4          2   2.00000000  47.00000000  48.00000000   0.49473684   0.50526316     0.42600897
6       &lt;leaf&gt;  21  21   5    1 0.00000000        0          0   1.00000000  16.00000000   5.00000000   0.76190476   0.23809524     0.09417040
7          age  74  74  31    2 0.08333333        4          2   2.00000000  31.00000000  43.00000000   0.41891892   0.58108108     0.33183857
14 spontaneous  40  40  17    1 0.05555556        4          0   1.00000000  23.00000000  17.00000000   0.57500000   0.42500000     0.17937220
28      &lt;leaf&gt;  28  28   9    1 0.00000000        0          0   1.00000000  19.00000000   9.00000000   0.67857143   0.32142857     0.12556054
29      &lt;leaf&gt;  12  12   4    2 0.01000000        0          0   2.00000000   4.00000000   8.00000000   0.33333333   0.66666667     0.05381166
15      &lt;leaf&gt;  34  34   8    2 0.00000000        0          0   2.00000000   8.00000000  26.00000000   0.23529412   0.76470588     0.15246637

$cp
          CP nsplit rel.error    xerror       xstd
1 0.08333333      0 1.0000000 1.0000000 0.09697723
2 0.05555556      3 0.7500000 1.0000000 0.09697723
3 0.01000000      4 0.6944444 0.8611111 0.09292314

$parameters
               parameters
minsplit            20.00
minbucket            7.00
cp                   0.01
maxcompete           4.00
maxsurrogate         5.00
usesurrogate         2.00
surrogatestyle       0.00
maxdepth            30.00
xval                10.00

$splits
          name count ncat      improve index        adj
1  spontaneous   223   -1 1.101199e+01   0.5 0.00000000
2          age   223    1 4.012376e-01  24.5 0.00000000
3       parity   223   -1 1.614884e-01   5.5 0.00000000
4      induced   223    1 1.074566e-01   0.5 0.00000000
5    education   223    3 5.389627e-02   1.0 0.00000000
6       parity     0   -1 6.367713e-01   3.5 0.14736842
7      induced     0    1 6.143498e-01   0.5 0.09473684
8          age     0    1 5.874439e-01  22.0 0.03157895
9       parity    95    1 3.848662e+00   3.5 0.00000000
10 spontaneous    95   -1 3.205054e+00   1.5 0.00000000
11         age    95   -1 2.794648e+00  30.5 0.00000000
12     induced    95    1 2.890226e-01   0.5 0.00000000
13   education    95    3 2.547368e-01   2.0 0.00000000
14     induced     0    1 8.210526e-01   1.5 0.19047619
15   education     0    3 8.105263e-01   3.0 0.14285714
16         age    74   -1 4.241733e+00  30.5 0.00000000
17 spontaneous    74   -1 4.006567e+00   1.5 0.00000000
18      parity    74    1 1.496324e-01   1.5 0.00000000
19   education    74    3 3.611794e-02   4.0 0.00000000
20     induced    74   -1 1.453066e-04   0.5 0.00000000
21   education     0    3 5.675676e-01   5.0 0.05882353
22      parity     0    1 5.540541e-01   1.5 0.02941176
23 spontaneous    40   -1 2.002381e+00   1.5 0.00000000
24         age    40    1 1.800000e+00  28.5 0.00000000
25   education    40    3 8.357143e-01   6.0 0.00000000
26      parity    40    1 2.423077e-01   1.5 0.00000000
27     induced    40   -1 1.125000e-01   0.5 0.00000000

$importance
            importance
spontaneous 13.0143706
parity       5.5962386
age          4.5894799
induced      1.7763196
education    0.7993226

$ordered
            ordered
age           FALSE
parity        FALSE
education     FALSE
spontaneous   FALSE
induced       FALSE

$call
                                                                                                      call
1 rpart::rpart(formula=infert_formula,data=train_test_classification$f$train$f1,,model=TRUE,x=TRUE,y=TRUE)</code></pre>
</div>
</div>
<p><code>result</code> bundles the pruned model’s internals — node <code>frame</code> (one row per node), the <code>cp</code> table, control <code>parameters</code>, raw <code>splits</code>, <code>importance</code>, factor-<code>ordered</code> flags, and the model <code>call</code> — for programmatic inspection or export, without needing to pick through <code>model</code>’s S3 structure directly.</p>
</section>
</section>
<section id="rpart-regression" class="level2">
<h2 class="anchored" data-anchor-id="rpart-regression">Rpart Regression</h2>
<p>The regression tree predicts <code>medv</code> (median owner-occupied home value, in $1000s) from the 13 other variables in the classic <code>MASS::Boston</code> housing dataset.</p>
<section id="growing-and-pruning-the-tree-1" class="level3">
<h3 class="anchored" data-anchor-id="growing-and-pruning-the-tree-1">Growing and pruning the tree</h3>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>result<span class="ot">&lt;-</span><span class="fu">data.frame</span>(rtree_regression<span class="sc">$</span>cptable)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>result<span class="sc">$</span>nsplit<span class="ot">&lt;-</span><span class="fu">factor</span>(result<span class="sc">$</span>nsplit<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>minimun_size<span class="ot">&lt;-</span><span class="fu">as.numeric</span>(<span class="fu">as.character</span>(result[<span class="fu">which.min</span>(result[,<span class="st">"xerror"</span>]),<span class="st">"nsplit"</span>]))</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>initial_model<span class="ot">&lt;-</span>rtree_regression</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>model<span class="ot">&lt;-</span>rpart<span class="sc">::</span><span class="fu">prune</span>(rtree_regression,<span class="at">cp=</span>rtree_regression<span class="sc">$</span>cptable[<span class="fu">which.min</span>(rtree_regression<span class="sc">$</span>cptable[,<span class="st">"xerror"</span>]),<span class="st">"CP"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>As with the classification tree, <code>rtree_regression</code> is pruned to the <code>CP</code> value that minimizes the cross-validated error — here, cross-validated sum-of-squares error rather than a classification loss. In this run the minimum <code>xerror</code> is again at the largest tree in the <code>cptable</code>, so the pruned tree keeps all 9 terminal nodes of the grown tree.</p>
</section>
<section id="variable-importance-2" class="level3">
<h3 class="anchored" data-anchor-id="variable-importance-2">Variable importance</h3>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>importance<span class="ot">&lt;-</span>model<span class="sc">$</span>variable.importance</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>importance<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">names=</span><span class="fu">names</span>(importance),<span class="at">importance=</span>importance)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>importance<span class="sc">$</span>names<span class="ot">&lt;-</span><span class="fu">factor</span>(importance<span class="sc">$</span>names,<span class="at">levels=</span><span class="fu">rev</span>(<span class="fu">as.character</span>(importance<span class="sc">$</span>names)))</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>plot_importance<span class="ot">&lt;-</span><span class="fu">ggplot</span>(importance,<span class="fu">aes</span>(<span class="at">x=</span>names,<span class="at">y=</span>importance))<span class="sc">+</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">'identity'</span>)<span class="sc">+</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Importance Plot"</span>,<span class="at">y=</span><span class="st">"Importance (sum of split improvements)"</span>,<span class="at">x=</span><span class="st">"Predictor"</span>)<span class="sc">+</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size=</span><span class="dv">10</span>)<span class="sc">+</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits=</span><span class="fu">rev</span>(<span class="fu">levels</span>(names)))<span class="sc">+</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>plot_importance</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="EXAMPLE_DECISION_TREE_files/figure-html/regression_importance-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="2100"></p>
</figure>
</div>
</div>
</div>
<p>For Boston housing, <code>rm</code> (average rooms per dwelling) and <code>lstat</code> (% lower-status population) are almost always the two dominant predictors of <code>medv</code> — this importance ranking is the tree-based analogue of the strong linear associations well known from OLS models fit to this same dataset.</p>
</section>
<section id="the-full-unpruned-tree-1" class="level3">
<h3 class="anchored" data-anchor-id="the-full-unpruned-tree-1">The full, unpruned tree</h3>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>rtree_regression</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>n= 455 

node), split, n, deviance, yval
      * denotes terminal node

 1) root 455 39028.0200 22.62110  
   2) rm&lt; 6.941 383 14615.6000 19.86214  
     4) lstat&gt;=14.4 154  2953.9890 14.98182  
       8) crim&gt;=6.99237 64  1004.3600 12.05156 *
       9) crim&lt; 6.99237 90  1009.3230 17.06556 *
     5) lstat&lt; 14.4 229  5527.0850 23.14410  
      10) lstat&gt;=9.715 105   658.5320 20.74000 *
      11) lstat&lt; 9.715 124  3747.8000 25.17984  
        22) age&lt; 89.45 116  1750.8600 24.44052  
          44) rm&lt; 6.543 73   676.5392 22.67945 *
          45) rm&gt;=6.543 43   463.5707 27.43023 *
        23) age&gt;=89.45 8  1014.1600 35.90000 *
   3) rm&gt;=6.941 72  5989.0990 37.29722  
     6) rm&lt; 7.435 43  1888.1360 31.99070  
      12) lstat&gt;=9.65 7   432.9971 23.05714 *
      13) lstat&lt; 9.65 36   787.8522 33.72778 *
     7) rm&gt;=7.435 29  1094.7260 45.16552 *</code></pre>
</div>
</div>
<p>The unpruned tree’s text form: each node reports its split rule, the number of training observations reaching it (<code>n</code>), the deviance (residual sum of squares) within the node, and the predicted <code>medv</code> (the node mean).</p>
</section>
<section id="choosing-the-tree-size-via-cross-validation-1" class="level3">
<h3 class="anchored" data-anchor-id="choosing-the-tree-size-via-cross-validation-1">Choosing the tree size via cross-validation</h3>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>rpart<span class="sc">::</span><span class="fu">plotcp</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="EXAMPLE_DECISION_TREE_files/figure-html/regression_cv_size-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="2100"></p>
</figure>
</div>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>rpart<span class="sc">::</span><span class="fu">rsq.rpart</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Regression tree:
rpart::rpart(formula = boston_formula, data = train_test_regression$f$train$f1, 
    model = TRUE, x = TRUE, y = TRUE)

Variables actually used in tree construction:
[1] age   crim  lstat rm   

Root node error: 39028/455 = 85.776

n= 455 

        CP nsplit rel error  xerror     xstd
1 0.472054      0   1.00000 1.00432 0.087594
2 0.157183      1   0.52795 0.58725 0.058026
3 0.077028      2   0.37076 0.43127 0.050213
4 0.028717      3   0.29374 0.33234 0.043749
5 0.025181      4   0.26502 0.34388 0.049606
6 0.024093      5   0.23984 0.33471 0.049507
7 0.017098      6   0.21574 0.31787 0.049487
8 0.015649      7   0.19865 0.32133 0.049491
9 0.010000      8   0.18300 0.30027 0.049051</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="EXAMPLE_DECISION_TREE_files/figure-html/regression_cv_size-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="2100"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="EXAMPLE_DECISION_TREE_files/figure-html/regression_cv_size-3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="2100"></p>
</figure>
</div>
</div>
</div>
<p>Here <code>rsq.rpart()</code>’s R² panel is a literal R²: the proportion of <code>medv</code>’s variance explained, both on the training data (apparent) and under cross-validation. The gap between the two lines is the model’s optimism — how much worse the tree performs on unseen data than on the data it was fit to. Here it grows from about 0.06 after one split to about 0.12 at the largest tree (apparent R² ≈ 0.82 vs.&nbsp;cross-validated ≈ 0.70), while cross-validated R² is still at its maximum at the largest tree, so no pruning was needed.</p>
</section>
<section id="error-by-size-summary-1" class="level3">
<h3 class="anchored" data-anchor-id="error-by-size-summary-1">Error-by-size summary</h3>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>error<span class="ot">&lt;-</span><span class="fu">data.frame</span>(model<span class="sc">$</span>cptable)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>error<span class="sc">$</span>nsplit<span class="ot">&lt;-</span><span class="fu">factor</span>(error<span class="sc">$</span>nsplit<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>tree_size<span class="ot">&lt;-</span>error[<span class="fu">which.min</span>(error[,<span class="st">"xerror"</span>]),<span class="st">"nsplit"</span>]</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>error<span class="ot">&lt;-</span>reshape2<span class="sc">::</span><span class="fu">melt</span>(error,<span class="at">id.vars=</span><span class="st">"nsplit"</span>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(error)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"Split"</span>,<span class="st">"Metric"</span>,<span class="st">"value"</span>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>plot_prune<span class="ot">&lt;-</span><span class="fu">ggplot</span>(error,<span class="fu">aes</span>(<span class="at">x=</span>Split,<span class="at">y=</span>value,<span class="at">color=</span>Metric))<span class="sc">+</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group=</span>Metric))<span class="sc">+</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="fu">paste</span>(<span class="st">"Error Plot"</span>,<span class="st">"Suggested Size:"</span>,tree_size),<span class="at">y=</span><span class="st">"Metric value"</span>,<span class="at">x=</span><span class="st">"Size of Tree"</span>)<span class="sc">+</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size=</span><span class="dv">10</span>)</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>plot_prune</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="EXAMPLE_DECISION_TREE_files/figure-html/regression_prune_plot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="2100"></p>
</figure>
</div>
</div>
</div>
<p>Same four <code>cptable</code> series (<code>CP</code>, <code>rel error</code>, <code>xerror</code>, <code>xstd</code>) as in the classification section, plotted against tree size (<code>nsplit + 1</code>), with the size at minimum <code>xerror</code> (9 terminal nodes) called out in the title.</p>
</section>
<section id="the-pruned-tree-diagram-1" class="level3">
<h3 class="anchored" data-anchor-id="the-pruned-tree-diagram-1">The pruned tree diagram</h3>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>rpart.plot<span class="sc">::</span><span class="fu">rpart.plot</span>(model,<span class="at">type=</span><span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="EXAMPLE_DECISION_TREE_files/figure-html/regression_final_tree-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="2100"></p>
</figure>
</div>
</div>
</div>
<p>Each box shows the node’s predicted <code>medv</code> and the percentage of observations it contains. Following the splits down — typically starting with <code>rm</code> or <code>lstat</code> — shows how the tree partitions the housing stock into progressively more homogeneous price segments, e.g.&nbsp;dwellings with the most rooms (the right-most branch on <code>rm</code>) land in the highest-value leaf (mean <code>medv</code> ≈ 45.2), while smaller homes in high-<code>lstat</code> areas land in the lowest (≈ 12.1).</p>
</section>
<section id="raw-model-components-1" class="level3">
<h3 class="anchored" data-anchor-id="raw-model-components-1">Raw model components</h3>
<div class="cell" data-layout-align="center">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>frame<span class="ot">&lt;-</span><span class="fu">data.frame</span>(model<span class="sc">$</span>frame)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>cp<span class="ot">&lt;-</span><span class="fu">data.frame</span>(model<span class="sc">$</span>cptable)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>parameters<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">parameters=</span><span class="fu">unlist</span>(model<span class="sc">$</span>control))</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>splits<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">name=</span><span class="fu">row.names</span>(model<span class="sc">$</span>splits),model<span class="sc">$</span>splits,<span class="at">row.names=</span><span class="cn">NULL</span>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>importance<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">importance=</span>model<span class="sc">$</span>variable.importance)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>ordered<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">ordered=</span>model<span class="sc">$</span>ordered)</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">y=</span>model<span class="sc">$</span>y,<span class="at">x=</span>model<span class="sc">$</span>x,<span class="at">model=</span>model<span class="sc">$</span>model)</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>call<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">call=</span><span class="fu">call_to_string</span>(model))</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>result<span class="ot">&lt;-</span><span class="fu">list</span>(<span class="at">frame=</span>frame,<span class="at">cp=</span>cp,<span class="at">parameters=</span>parameters,<span class="at">splits=</span>splits,<span class="at">importance=</span>importance,<span class="at">ordered=</span>ordered,<span class="at">call=</span>call)</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(result)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>$frame
      var   n  wt        dev     yval  complexity ncompete nsurrogate
1      rm 455 455 39028.0175 22.62110 0.472053621        4          5
2   lstat 383 383 14615.6010 19.86214 0.157182655        4          5
4    crim 154 154  2953.9891 14.98182 0.024093103        4          5
8  &lt;leaf&gt;  64  64  1004.3598 12.05156 0.008611929        0          0
9  &lt;leaf&gt;  90  90  1009.3232 17.06556 0.005709086        0          0
5   lstat 229 229  5527.0845 23.14410 0.028716625        4          5
10 &lt;leaf&gt; 105 105   658.5320 20.74000 0.001051925        0          0
11    age 124 124  3747.7996 25.17984 0.025181398        4          5
22     rm 116 116  1750.8596 24.44052 0.015649006        4          5
44 &lt;leaf&gt;  73  73   676.5392 22.67945 0.004513536        0          0
45 &lt;leaf&gt;  43  43   463.5707 27.43023 0.003416614        0          0
23 &lt;leaf&gt;   8   8  1014.1600 35.90000 0.010000000        0          0
3      rm  72  72  5989.0994 37.29722 0.077027680        4          5
6   lstat  43  43  1888.1363 31.99070 0.017097638        4          5
12 &lt;leaf&gt;   7   7   432.9971 23.05714 0.010000000        0          0
13 &lt;leaf&gt;  36  36   787.8522 33.72778 0.003580613        0          0
7  &lt;leaf&gt;  29  29  1094.7255 45.16552 0.009323713        0          0

$cp
          CP nsplit rel.error    xerror       xstd
1 0.47205362      0 1.0000000 1.0043157 0.08759429
2 0.15718266      1 0.5279464 0.5872495 0.05802625
3 0.07702768      2 0.3707637 0.4312720 0.05021296
4 0.02871663      3 0.2937360 0.3323424 0.04374889
5 0.02518140      4 0.2650194 0.3438781 0.04960597
6 0.02409310      5 0.2398380 0.3347075 0.04950675
7 0.01709764      6 0.2157449 0.3178695 0.04948660
8 0.01564901      7 0.1986473 0.3213327 0.04949119
9 0.01000000      8 0.1829983 0.3002653 0.04905131

$parameters
               parameters
minsplit            20.00
minbucket            7.00
cp                   0.01
maxcompete           4.00
maxsurrogate         5.00
usesurrogate         2.00
surrogatestyle       0.00
maxdepth            30.00
xval                10.00

$splits
      name count ncat    improve      index        adj
1       rm   455   -1 0.47205362   6.941000 0.00000000
2    lstat   455    1 0.43775919   9.725000 0.00000000
3    indus   455    1 0.26019021   6.660000 0.00000000
4  ptratio   455    1 0.24287674  19.650000 0.00000000
5      nox   455    1 0.21408796   0.669500 0.00000000
6    lstat     0    1 0.89010989   4.150000 0.30555556
7  ptratio     0    1 0.86593407  14.550000 0.15277778
8       zn     0   -1 0.85274725  81.250000 0.06944444
9    indus     0    1 0.85274725   1.605000 0.06944444
10    crim     0    1 0.84615385   0.013355 0.02777778
11   lstat   383    1 0.41972461  14.400000 0.00000000
12     nox   383    1 0.26937201   0.669500 0.00000000
13    crim   383    1 0.23890675   9.280695 0.00000000
14 ptratio   383    1 0.21640988  19.900000 0.00000000
15     age   383    1 0.21263549  75.750000 0.00000000
16     age     0    1 0.80939948  88.100000 0.52597403
17     dis     0   -1 0.77806789   2.239350 0.44805195
18     nox     0    1 0.77545692   0.576500 0.44155844
19   indus     0    1 0.77284595  16.570000 0.43506494
20     tax     0    1 0.77284595 434.500000 0.43506494
21    crim   154    1 0.31831737   6.992370 0.00000000
22     nox   154    1 0.31053788   0.607000 0.00000000
23     dis   154   -1 0.29028800   2.003700 0.00000000
24     tax   154    1 0.25291593 567.500000 0.00000000
25   lstat   154    1 0.24584057  19.830000 0.00000000
26     rad     0    1 0.87012987  16.000000 0.68750000
27     tax     0    1 0.85714286 567.500000 0.65625000
28     nox     0    1 0.74675325   0.661500 0.39062500
29     dis     0   -1 0.74025974   2.202000 0.37500000
30     age     0    1 0.69480519  98.600000 0.26562500
31   lstat   229    1 0.20277471   9.715000 0.00000000
32      rm   229   -1 0.18504482   6.543000 0.00000000
33     dis   229    1 0.14439126   1.600900 0.00000000
34   indus   229    1 0.06429180   4.100000 0.00000000
35     tax   229    1 0.06289683 222.500000 0.00000000
36     nox     0    1 0.73799127   0.519000 0.42857143
37   indus     0    1 0.72489083   7.625000 0.40000000
38      rm     0   -1 0.72052402   6.260000 0.39047619
39     dis     0   -1 0.69868996   4.480250 0.34285714
40    crim     0    1 0.68995633   0.130245 0.32380952
41     age   124   -1 0.26222854  89.450000 0.00000000
42     nox   124   -1 0.25623370   0.618000 0.00000000
43     dis   124    1 0.23254331   2.149100 0.00000000
44    crim   124   -1 0.21670627   1.383930 0.00000000
45     tax   124   -1 0.19648951 426.000000 0.00000000
46     dis     0    1 0.98387097   2.149100 0.75000000
47     nox     0   -1 0.97580645   0.589000 0.62500000
48 ptratio     0    1 0.96774194  14.750000 0.50000000
49    crim     0   -1 0.95967742   1.163695 0.37500000
50   indus     0   -1 0.95967742  16.570000 0.37500000
51      rm   116   -1 0.34882849   6.543000 0.00000000
52   lstat   116    1 0.25126720   5.410000 0.00000000
53 ptratio   116    1 0.14390779  15.750000 0.00000000
54     tax   116    1 0.07743844 267.500000 0.00000000
55     nox   116    1 0.07722395   0.512500 0.00000000
56   lstat     0    1 0.74137931   5.055000 0.30232558
57      zn     0   -1 0.68965517  31.500000 0.16279070
58 ptratio     0    1 0.68965517  15.750000 0.16279070
59    crim     0    1 0.67241379   0.017895 0.11627907
60     age     0   -1 0.66379310  68.650000 0.09302326
61      rm    72   -1 0.50195153   7.435000 0.00000000
62   lstat    72    1 0.37062504   4.680000 0.00000000
63 ptratio    72    1 0.25679102  19.700000 0.00000000
64     rad    72    1 0.21966661  16.000000 0.00000000
65    crim    72    1 0.21966661   2.742235 0.00000000
66   lstat     0    1 0.79166667   4.330000 0.48275862
67 ptratio     0    1 0.66666667  14.750000 0.17241379
68   indus     0   -1 0.63888889  18.840000 0.10344828
69    chas     0   -1 0.63888889   0.500000 0.10344828
70   black     0    1 0.63888889 389.885000 0.10344828
71   lstat    43    1 0.35341036   9.650000 0.00000000
72 ptratio    43    1 0.24469424  19.700000 0.00000000
73     rad    43    1 0.17534867   7.500000 0.00000000
74     nox    43    1 0.16270057   0.639000 0.00000000
75   indus    43    1 0.14847490   9.500000 0.00000000
76    crim     0    1 0.90697674   0.724605 0.42857143
77     nox     0    1 0.90697674   0.659000 0.42857143
78     rad     0    1 0.88372093  16.000000 0.28571429
79     tax     0    1 0.88372093 534.500000 0.28571429
80   indus     0    1 0.86046512  15.015000 0.14285714

$importance
        importance
rm      22477.9316
lstat   15187.8465
indus    5171.4753
age      4515.9648
nox      4456.5997
dis      4222.5449
ptratio  3923.8046
tax      3476.6470
crim     2540.5153
zn       1378.8214
rad       837.1138
black     310.9901
chas      310.9901

$ordered
        ordered
crim      FALSE
zn        FALSE
indus     FALSE
chas      FALSE
nox       FALSE
rm        FALSE
age       FALSE
dis       FALSE
rad       FALSE
tax       FALSE
ptratio   FALSE
black     FALSE
lstat     FALSE

$call
                                                                                                  call
1 rpart::rpart(formula=boston_formula,data=train_test_regression$f$train$f1,,model=TRUE,x=TRUE,y=TRUE)</code></pre>
</div>
</div>
<p>Same bundling as the classification section — the pruned regression model’s <code>frame</code>, <code>cp</code> table, <code>parameters</code>, <code>splits</code>, <code>importance</code>, <code>ordered</code> flags, and <code>call</code>.</p>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/sedzinfo\.github\.io\/vignettes\/example\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<input type="hidden" id="giscus-base-theme" value="light">
<input type="hidden" id="giscus-alt-theme" value="light">
<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "sedzinfo/vignettes";
    script.dataset.repoId = "R_kgDOU6AfOA";
    script.dataset.category = "Announcements";
    script.dataset.categoryId = "DIC_kwDOU6AfOM4DG8ZY";
    script.dataset.mapping = "pathname";
    script.dataset.reactionsEnabled = "1";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "top";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb32" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Regression and Classification Trees"</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> ""</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="an">output:</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="co">  html_document:</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="co">    css: styles.css</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="co">    theme: flatly</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="co">    highlight: tango</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="co">    toc_float: true</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code_folding: show</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a><span class="co">    self_contained: true</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="an">vignette:</span><span class="co"> &gt;</span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a><span class="co">  %\VignetteIndexEntry{RPART}</span></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a><span class="co">  %\VignetteEngine{knitr::rmarkdown}</span></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a><span class="co">  %\VignetteEncoding{UTF-8}</span></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a><span class="in">```{r options,echo=FALSE,warning=FALSE,message=FALSE}</span></span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>directory<span class="ot">&lt;-</span><span class="cf">if</span> (rstudioapi<span class="sc">::</span><span class="fu">isAvailable</span>()) <span class="fu">paste0</span>(<span class="fu">dirname</span>(rstudioapi<span class="sc">::</span><span class="fu">getActiveDocumentContext</span>()<span class="sc">$</span>path),<span class="st">"/"</span>) <span class="cf">else</span> <span class="st">""</span></span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="fu">paste0</span>(directory, <span class="st">"R/code_options.R"</span>))</span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="fu">paste0</span>(directory, <span class="st">"R/code_rwf.R"</span>))</span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a><span class="fu">## Description</span></span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a>This page reproduces the steps of rwf's <span class="in">`report_rtree()`</span> using <span class="in">`rpart`</span> directly; both models are fit on the training part of the first of 10 folds created by rwf's <span class="in">`k_fold()`</span>.</span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a>Installation instructions for rwf can be found <span class="co">[</span><span class="ot">here</span><span class="co">](https://github.com/sedzinfo/rwf)</span></span>
<span id="cb32-28"><a href="#cb32-28" aria-hidden="true" tabindex="-1"></a><span class="in">`report_rtree()`</span> is not installed by default; it is in /rwf/working_functions/OTHER/ML_TREE_RPART.R</span>
<span id="cb32-29"><a href="#cb32-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-30"><a href="#cb32-30" aria-hidden="true" tabindex="-1"></a><span class="fu">## Theoretical Background</span></span>
<span id="cb32-31"><a href="#cb32-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-32"><a href="#cb32-32" aria-hidden="true" tabindex="-1"></a><span class="fu">### Recursive partitioning</span></span>
<span id="cb32-33"><a href="#cb32-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-34"><a href="#cb32-34" aria-hidden="true" tabindex="-1"></a><span class="in">`rpart`</span> implements **CART** (Classification and Regression Trees, Breiman et al., 1984). Starting from the full dataset at the root node, the algorithm searches every predictor and every possible split point on that predictor, and picks the single split that most improves node purity. Each resulting child node is then split again, recursively, until a stopping rule is reached (a minimum number of observations per node, a minimum improvement threshold, or a maximum depth). The result is a **binary tree**: every internal node asks a yes/no question about one predictor, and every terminal node ("leaf") gives a prediction.</span>
<span id="cb32-35"><a href="#cb32-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-36"><a href="#cb32-36" aria-hidden="true" tabindex="-1"></a><span class="fu">### Splitting criteria</span></span>
<span id="cb32-37"><a href="#cb32-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-38"><a href="#cb32-38" aria-hidden="true" tabindex="-1"></a>The measure of "improvement" depends on the outcome type:</span>
<span id="cb32-39"><a href="#cb32-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-40"><a href="#cb32-40" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Classification** (`method = "class"`, used below for `case`) — by default `rpart` uses the **Gini impurity** of the class distribution within a node; a split is chosen to make the two child nodes as class-pure as possible.</span>
<span id="cb32-41"><a href="#cb32-41" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Regression** (`method = "anova"`, used below for `medv`) — the criterion is the reduction in **within-node sum of squares**, i.e. the split that most reduces the variance of the outcome within each child node.</span>
<span id="cb32-42"><a href="#cb32-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-43"><a href="#cb32-43" aria-hidden="true" tabindex="-1"></a><span class="fu">### Cost-complexity pruning</span></span>
<span id="cb32-44"><a href="#cb32-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-45"><a href="#cb32-45" aria-hidden="true" tabindex="-1"></a>A tree grown to full depth almost always **overfits** — it captures noise along with signal. `rpart` addresses this with **cost-complexity pruning**: every subtree $T$ is scored as</span>
<span id="cb32-46"><a href="#cb32-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-47"><a href="#cb32-47" aria-hidden="true" tabindex="-1"></a>$$R_\alpha(T) = R(T) + \alpha \, |T|$$</span>
<span id="cb32-48"><a href="#cb32-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-49"><a href="#cb32-49" aria-hidden="true" tabindex="-1"></a>where $R(T)$ is the tree's error (relative to the root), $|T|$ is the number of terminal nodes, and $\alpha$ (called <span class="in">`CP`</span> in <span class="in">`rpart`</span>'s output) penalizes tree size. Varying $\alpha$ from 0 to 1 produces a nested sequence of subtrees, from the grown tree (stopped at <span class="in">`rpart`</span>'s default <span class="in">`cp = 0.01`</span>) down to a single root node — this sequence is stored in <span class="in">`model$cptable`</span>.</span>
<span id="cb32-50"><a href="#cb32-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-51"><a href="#cb32-51" aria-hidden="true" tabindex="-1"></a><span class="fu">### Cross-validated tree size</span></span>
<span id="cb32-52"><a href="#cb32-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-53"><a href="#cb32-53" aria-hidden="true" tabindex="-1"></a>Because the *apparent* error of a tree always decreases as it grows (a larger tree can always fit the training data at least as well), `rpart` estimates each subtree's error via internal **k-fold cross-validation**. `cptable` reports, for every candidate `CP` value: the relative error on the training data (`rel error`), the cross-validated error (`xerror`), and its standard deviation (`xstd`). The code below selects the tree whose `CP` gives the **minimum `xerror`** — a common, more conservative alternative is the "1-SE rule" (the smallest tree whose <span class="in">`xerror`</span> is within one standard error of the minimum), which favors a simpler tree.</span>
<span id="cb32-54"><a href="#cb32-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-55"><a href="#cb32-55" aria-hidden="true" tabindex="-1"></a><span class="fu">### Variable importance</span></span>
<span id="cb32-56"><a href="#cb32-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-57"><a href="#cb32-57" aria-hidden="true" tabindex="-1"></a>A predictor's importance is the sum of the goodness-of-split (improvement in Gini impurity for classification, or in sum-of-squares for regression) for every split where it is the *primary* splitter, plus, for every split where it serves as a **surrogate** (a stand-in used when the primary splitting variable is missing), the primary split's improvement weighted by the surrogate's adjusted agreement. This is why a variable can show non-trivial importance even if it never appears as a labeled split in the final tree diagram.</span>
<span id="cb32-58"><a href="#cb32-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-59"><a href="#cb32-59" aria-hidden="true" tabindex="-1"></a><span class="in">```{r create_models,include=TRUE}</span></span>
<span id="cb32-60"><a href="#cb32-60" aria-hidden="true" tabindex="-1"></a>infert_formula<span class="ot">&lt;-</span><span class="fu">formula</span>(<span class="fu">factor</span>(case)<span class="sc">~</span>age<span class="sc">+</span>parity<span class="sc">+</span>education<span class="sc">+</span>spontaneous<span class="sc">+</span>induced)</span>
<span id="cb32-61"><a href="#cb32-61" aria-hidden="true" tabindex="-1"></a>boston_formula<span class="ot">&lt;-</span><span class="fu">formula</span>(<span class="fu">c</span>(<span class="st">"medv~"</span>,<span class="fu">paste</span>(<span class="fu">names</span>(MASS<span class="sc">::</span>Boston)[<span class="dv">1</span><span class="sc">:</span><span class="dv">13</span>],<span class="at">collapse=</span><span class="st">"+"</span>)))</span>
<span id="cb32-62"><a href="#cb32-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-63"><a href="#cb32-63" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(infert_formula)</span>
<span id="cb32-64"><a href="#cb32-64" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(boston_formula)</span>
<span id="cb32-65"><a href="#cb32-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-66"><a href="#cb32-66" aria-hidden="true" tabindex="-1"></a><span class="co"># kfolding (seed fixed so folds, rpart's internal cross-validation and the prose below are reproducible)</span></span>
<span id="cb32-67"><a href="#cb32-67" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb32-68"><a href="#cb32-68" aria-hidden="true" tabindex="-1"></a>train_test_classification<span class="ot">&lt;-</span><span class="fu">k_fold</span>(<span class="at">df=</span>infert,</span>
<span id="cb32-69"><a href="#cb32-69" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">model_formula=</span>infert_formula)</span>
<span id="cb32-70"><a href="#cb32-70" aria-hidden="true" tabindex="-1"></a>train_test_regression<span class="ot">&lt;-</span><span class="fu">k_fold</span>(<span class="at">df=</span>MASS<span class="sc">::</span>Boston,</span>
<span id="cb32-71"><a href="#cb32-71" aria-hidden="true" tabindex="-1"></a>                              <span class="at">model_formula=</span>boston_formula)</span>
<span id="cb32-72"><a href="#cb32-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-73"><a href="#cb32-73" aria-hidden="true" tabindex="-1"></a><span class="co"># rpart models</span></span>
<span id="cb32-74"><a href="#cb32-74" aria-hidden="true" tabindex="-1"></a>rtree_classification<span class="ot">&lt;-</span>rpart<span class="sc">::</span><span class="fu">rpart</span>(infert_formula,</span>
<span id="cb32-75"><a href="#cb32-75" aria-hidden="true" tabindex="-1"></a>                                   train_test_classification<span class="sc">$</span>f<span class="sc">$</span>train<span class="sc">$</span>f1,</span>
<span id="cb32-76"><a href="#cb32-76" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">model=</span><span class="cn">TRUE</span>,<span class="at">x=</span><span class="cn">TRUE</span>,<span class="at">y=</span><span class="cn">TRUE</span>)</span>
<span id="cb32-77"><a href="#cb32-77" aria-hidden="true" tabindex="-1"></a>rtree_regression<span class="ot">&lt;-</span>rpart<span class="sc">::</span><span class="fu">rpart</span>(boston_formula,</span>
<span id="cb32-78"><a href="#cb32-78" aria-hidden="true" tabindex="-1"></a>                               train_test_regression<span class="sc">$</span>f<span class="sc">$</span>train<span class="sc">$</span>f1,</span>
<span id="cb32-79"><a href="#cb32-79" aria-hidden="true" tabindex="-1"></a>                               <span class="at">model=</span><span class="cn">TRUE</span>,<span class="at">x=</span><span class="cn">TRUE</span>,<span class="at">y=</span><span class="cn">TRUE</span>)</span>
<span id="cb32-80"><a href="#cb32-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-81"><a href="#cb32-81" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-82"><a href="#cb32-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-83"><a href="#cb32-83" aria-hidden="true" tabindex="-1"></a><span class="fu">## Rpart Classification</span></span>
<span id="cb32-84"><a href="#cb32-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-85"><a href="#cb32-85" aria-hidden="true" tabindex="-1"></a>The classification tree predicts <span class="in">`case`</span> (secondary infertility, from the classic <span class="in">`infert`</span> case-control study) from <span class="in">`age`</span>, <span class="in">`parity`</span>, <span class="in">`education`</span>, <span class="in">`spontaneous`</span>, and <span class="in">`induced`</span> (prior abortions).</span>
<span id="cb32-86"><a href="#cb32-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-87"><a href="#cb32-87" aria-hidden="true" tabindex="-1"></a><span class="fu">### Growing and pruning the tree</span></span>
<span id="cb32-88"><a href="#cb32-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-89"><a href="#cb32-89" aria-hidden="true" tabindex="-1"></a><span class="in">`rtree_classification`</span> was grown with rpart's default stopping rules (<span class="in">`cp = 0.01`</span>, <span class="in">`minsplit = 20`</span>, <span class="in">`minbucket = 7`</span>) in the <span class="in">`create_models`</span> chunk above. Here it is pruned back to the <span class="in">`CP`</span> value that minimizes the cross-validated error (<span class="in">`xerror`</span>) in its <span class="in">`cptable`</span>.</span>
<span id="cb32-90"><a href="#cb32-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-91"><a href="#cb32-91" aria-hidden="true" tabindex="-1"></a><span class="in">```{r classification_prune,echo=TRUE}</span></span>
<span id="cb32-92"><a href="#cb32-92" aria-hidden="true" tabindex="-1"></a>result<span class="ot">&lt;-</span><span class="fu">data.frame</span>(rtree_classification<span class="sc">$</span>cptable)</span>
<span id="cb32-93"><a href="#cb32-93" aria-hidden="true" tabindex="-1"></a>result<span class="sc">$</span>nsplit<span class="ot">&lt;-</span><span class="fu">factor</span>(result<span class="sc">$</span>nsplit<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb32-94"><a href="#cb32-94" aria-hidden="true" tabindex="-1"></a>minimun_size<span class="ot">&lt;-</span><span class="fu">as.numeric</span>(<span class="fu">as.character</span>(result[<span class="fu">which.min</span>(result[,<span class="st">"xerror"</span>]),<span class="st">"nsplit"</span>]))</span>
<span id="cb32-95"><a href="#cb32-95" aria-hidden="true" tabindex="-1"></a>initial_model<span class="ot">&lt;-</span>rtree_classification</span>
<span id="cb32-96"><a href="#cb32-96" aria-hidden="true" tabindex="-1"></a>model<span class="ot">&lt;-</span>rpart<span class="sc">::</span><span class="fu">prune</span>(rtree_classification,</span>
<span id="cb32-97"><a href="#cb32-97" aria-hidden="true" tabindex="-1"></a>                    <span class="at">cp=</span>rtree_classification<span class="sc">$</span>cptable[<span class="fu">which.min</span>(rtree_classification<span class="sc">$</span>cptable[,<span class="st">"xerror"</span>]),<span class="st">"CP"</span>])</span>
<span id="cb32-98"><a href="#cb32-98" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-99"><a href="#cb32-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-100"><a href="#cb32-100" aria-hidden="true" tabindex="-1"></a><span class="fu">### Variable importance</span></span>
<span id="cb32-101"><a href="#cb32-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-102"><a href="#cb32-102" aria-hidden="true" tabindex="-1"></a><span class="in">```{r classification_importance,echo=TRUE,dev='png'}</span></span>
<span id="cb32-103"><a href="#cb32-103" aria-hidden="true" tabindex="-1"></a>importance<span class="ot">&lt;-</span>model<span class="sc">$</span>variable.importance</span>
<span id="cb32-104"><a href="#cb32-104" aria-hidden="true" tabindex="-1"></a>importance<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">names=</span><span class="fu">names</span>(importance),<span class="at">importance=</span>importance)</span>
<span id="cb32-105"><a href="#cb32-105" aria-hidden="true" tabindex="-1"></a>importance<span class="sc">$</span>names<span class="ot">&lt;-</span><span class="fu">factor</span>(importance<span class="sc">$</span>names,<span class="at">levels=</span><span class="fu">rev</span>(<span class="fu">as.character</span>(importance<span class="sc">$</span>names)))</span>
<span id="cb32-106"><a href="#cb32-106" aria-hidden="true" tabindex="-1"></a>plot_importance<span class="ot">&lt;-</span><span class="fu">ggplot</span>(importance,<span class="fu">aes</span>(<span class="at">x=</span>names,<span class="at">y=</span>importance))<span class="sc">+</span></span>
<span id="cb32-107"><a href="#cb32-107" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">'identity'</span>)<span class="sc">+</span></span>
<span id="cb32-108"><a href="#cb32-108" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Importance Plot"</span>,<span class="at">y=</span><span class="st">"Importance (sum of split improvements)"</span>,<span class="at">x=</span><span class="st">"Predictor"</span>)<span class="sc">+</span></span>
<span id="cb32-109"><a href="#cb32-109" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size=</span><span class="dv">10</span>)<span class="sc">+</span></span>
<span id="cb32-110"><a href="#cb32-110" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits=</span><span class="fu">rev</span>(<span class="fu">levels</span>(names)))<span class="sc">+</span></span>
<span id="cb32-111"><a href="#cb32-111" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb32-112"><a href="#cb32-112" aria-hidden="true" tabindex="-1"></a>plot_importance</span>
<span id="cb32-113"><a href="#cb32-113" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-114"><a href="#cb32-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-115"><a href="#cb32-115" aria-hidden="true" tabindex="-1"></a>Longer bars mean the predictor contributed more to reducing impurity across the tree's splits (as primary splitter or as a surrogate). Here **`r names(model$variable.importance)[1]`** dominates (importance `r round(model$variable.importance[1],2)`), followed by **`r names(model$variable.importance)[2]`** and **`r names(model$variable.importance)[3]`**, with **`r names(model$variable.importance)[length(model$variable.importance)]`** contributing least. Note that <span class="in">`infert`</span> is a matched case-control study in which cases and controls were matched on age, parity and education, so the substantive signal is in the prior-abortion variables (<span class="in">`spontaneous`</span>, <span class="in">`induced`</span>); splits on age or parity largely reflect sampling noise in this training fold.</span>
<span id="cb32-116"><a href="#cb32-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-117"><a href="#cb32-117" aria-hidden="true" tabindex="-1"></a><span class="fu">### The full, unpruned tree</span></span>
<span id="cb32-118"><a href="#cb32-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-119"><a href="#cb32-119" aria-hidden="true" tabindex="-1"></a><span class="in">```{r classification_full_tree_text,echo=TRUE}</span></span>
<span id="cb32-120"><a href="#cb32-120" aria-hidden="true" tabindex="-1"></a>rtree_classification</span>
<span id="cb32-121"><a href="#cb32-121" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-122"><a href="#cb32-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-123"><a href="#cb32-123" aria-hidden="true" tabindex="-1"></a>This is the text representation of the tree *before* pruning — every line is one node: its splitting rule, the number of observations that reach it (<span class="in">`n`</span>), the misclassification loss, and the predicted class with its probability. Compare its size to the pruned <span class="in">`model`</span> used in the plots below: in this run the full tree has <span class="in">`r sum(rtree_classification$frame$var=="&lt;leaf&gt;")`</span> terminal nodes and the pruned tree <span class="in">`r sum(model$frame$var=="&lt;leaf&gt;")`</span>. When the minimum <span class="in">`xerror`</span> occurs at the largest tree in the <span class="in">`cptable`</span>, pruning leaves the tree unchanged; with other data or a smaller <span class="in">`cp`</span>, pruning would collapse some of these nodes.</span>
<span id="cb32-124"><a href="#cb32-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-125"><a href="#cb32-125" aria-hidden="true" tabindex="-1"></a><span class="fu">### Choosing the tree size via cross-validation</span></span>
<span id="cb32-126"><a href="#cb32-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-127"><a href="#cb32-127" aria-hidden="true" tabindex="-1"></a><span class="in">```{r classification_cv_size,echo=TRUE,dev='png'}</span></span>
<span id="cb32-128"><a href="#cb32-128" aria-hidden="true" tabindex="-1"></a>rpart<span class="sc">::</span><span class="fu">plotcp</span>(model)</span>
<span id="cb32-129"><a href="#cb32-129" aria-hidden="true" tabindex="-1"></a>rpart<span class="sc">::</span><span class="fu">rsq.rpart</span>(model)</span>
<span id="cb32-130"><a href="#cb32-130" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-131"><a href="#cb32-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-132"><a href="#cb32-132" aria-hidden="true" tabindex="-1"></a><span class="in">`plotcp()`</span> plots cross-validated **relative error** (`xerror`, with one-SE error bars) against `CP` (bottom axis) and tree size (top axis) — the dotted horizontal line marks one standard error above the minimum, the usual reference for the "1-SE rule". `rsq.rpart()` prints the `cptable` and adds two more panels: apparent vs. cross-validated **R-squared**, and cross-validated **relative error**, against the number of splits. Because this is a *classification* tree, these values are 1 minus the relative misclassification error (relative to the root node's error of `r model$frame$dev[1]`/`r model$frame$n[1]`), not explained variance, so read them as relative predictive error rather than a literal R²; `rsq.rpart()` itself warns that it "may not be applicable for this method". Here cross-validated error drops only from 1.00 to `r round(min(model$cptable[,"xerror"]),2)` of the root error (about `r round(100*min(model$cptable[,"xerror"])*model$frame$dev[1]/model$frame$n[1])`% vs `r round(100*model$frame$dev<span class="co">[</span><span class="ot">1</span><span class="co">]</span>/model$frame$n<span class="co">[</span><span class="ot">1</span><span class="co">]</span>)<span class="in">`% misclassification) and is lowest at the largest tree in the `</span>cptable<span class="in">`, which is why the minimum-`</span>xerror` rule keeps the full tree.</span>
<span id="cb32-133"><a href="#cb32-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-134"><a href="#cb32-134" aria-hidden="true" tabindex="-1"></a><span class="fu">### Error-by-size summary</span></span>
<span id="cb32-135"><a href="#cb32-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-136"><a href="#cb32-136" aria-hidden="true" tabindex="-1"></a><span class="in">```{r classification_prune_plot,echo=TRUE,dev='png'}</span></span>
<span id="cb32-137"><a href="#cb32-137" aria-hidden="true" tabindex="-1"></a>error<span class="ot">&lt;-</span><span class="fu">data.frame</span>(model<span class="sc">$</span>cptable)</span>
<span id="cb32-138"><a href="#cb32-138" aria-hidden="true" tabindex="-1"></a>error<span class="sc">$</span>nsplit<span class="ot">&lt;-</span><span class="fu">factor</span>(error<span class="sc">$</span>nsplit<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb32-139"><a href="#cb32-139" aria-hidden="true" tabindex="-1"></a>tree_size<span class="ot">&lt;-</span>error[<span class="fu">which.min</span>(error[,<span class="st">"xerror"</span>]),<span class="st">"nsplit"</span>]</span>
<span id="cb32-140"><a href="#cb32-140" aria-hidden="true" tabindex="-1"></a>error<span class="ot">&lt;-</span>reshape2<span class="sc">::</span><span class="fu">melt</span>(error,<span class="at">id.vars=</span><span class="st">"nsplit"</span>)</span>
<span id="cb32-141"><a href="#cb32-141" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(error)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"Split"</span>,<span class="st">"Metric"</span>,<span class="st">"value"</span>)</span>
<span id="cb32-142"><a href="#cb32-142" aria-hidden="true" tabindex="-1"></a>plot_prune<span class="ot">&lt;-</span><span class="fu">ggplot</span>(error,<span class="fu">aes</span>(<span class="at">x=</span>Split,<span class="at">y=</span>value,<span class="at">color=</span>Metric))<span class="sc">+</span></span>
<span id="cb32-143"><a href="#cb32-143" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group=</span>Metric))<span class="sc">+</span></span>
<span id="cb32-144"><a href="#cb32-144" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb32-145"><a href="#cb32-145" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="fu">paste</span>(<span class="st">"Error Plot"</span>,<span class="st">"Suggested Size:"</span>,tree_size),<span class="at">y=</span><span class="st">"Metric value"</span>,<span class="at">x=</span><span class="st">"Size of Tree"</span>)<span class="sc">+</span></span>
<span id="cb32-146"><a href="#cb32-146" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size=</span><span class="dv">10</span>)</span>
<span id="cb32-147"><a href="#cb32-147" aria-hidden="true" tabindex="-1"></a>plot_prune</span>
<span id="cb32-148"><a href="#cb32-148" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-149"><a href="#cb32-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-150"><a href="#cb32-150" aria-hidden="true" tabindex="-1"></a>This re-plots all four <span class="in">`cptable`</span> columns (<span class="in">`CP`</span>, <span class="in">`rel error`</span>, <span class="in">`xerror`</span>, <span class="in">`xstd`</span>) on one axis against tree size (number of terminal nodes = <span class="in">`nsplit + 1`</span>), from a single node onward. The title reports the tree size at which <span class="in">`xerror`</span> is minimized — the size the pruned <span class="in">`model`</span> retains (here <span class="in">`r as.character(tree_size)`</span> terminal nodes, i.e. the full tree).</span>
<span id="cb32-151"><a href="#cb32-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-152"><a href="#cb32-152" aria-hidden="true" tabindex="-1"></a><span class="fu">### The pruned tree diagram</span></span>
<span id="cb32-153"><a href="#cb32-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-154"><a href="#cb32-154" aria-hidden="true" tabindex="-1"></a><span class="in">```{r classification_final_tree,echo=TRUE,dev='png'}</span></span>
<span id="cb32-155"><a href="#cb32-155" aria-hidden="true" tabindex="-1"></a>rpart.plot<span class="sc">::</span><span class="fu">rpart.plot</span>(model,<span class="at">type=</span><span class="dv">1</span>)</span>
<span id="cb32-156"><a href="#cb32-156" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-157"><a href="#cb32-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-158"><a href="#cb32-158" aria-hidden="true" tabindex="-1"></a>Each box is a node showing the predicted class (top), the fitted probability that <span class="in">`case = 1`</span> (middle), and the percentage of the training sample in that node (bottom). Following the branches down from the root shows the sequence of yes/no rules — here the splits use, in order from the root, <span class="in">`r paste(setdiff(unique(as.character(model$frame$var)),"&lt;leaf&gt;"),collapse=", ")`</span>: first whether the woman had any prior spontaneous abortion, then parity, then age — that separate higher- from lower-risk groups.</span>
<span id="cb32-159"><a href="#cb32-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-160"><a href="#cb32-160" aria-hidden="true" tabindex="-1"></a><span class="fu">### Raw model components</span></span>
<span id="cb32-161"><a href="#cb32-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-162"><a href="#cb32-162" aria-hidden="true" tabindex="-1"></a><span class="in">```{r classification_export,echo=TRUE}</span></span>
<span id="cb32-163"><a href="#cb32-163" aria-hidden="true" tabindex="-1"></a>frame<span class="ot">&lt;-</span><span class="fu">data.frame</span>(model<span class="sc">$</span>frame)</span>
<span id="cb32-164"><a href="#cb32-164" aria-hidden="true" tabindex="-1"></a>cp<span class="ot">&lt;-</span><span class="fu">data.frame</span>(model<span class="sc">$</span>cptable)</span>
<span id="cb32-165"><a href="#cb32-165" aria-hidden="true" tabindex="-1"></a>parameters<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">parameters=</span><span class="fu">unlist</span>(model<span class="sc">$</span>control))</span>
<span id="cb32-166"><a href="#cb32-166" aria-hidden="true" tabindex="-1"></a>splits<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">name=</span><span class="fu">row.names</span>(model<span class="sc">$</span>splits),model<span class="sc">$</span>splits,<span class="at">row.names=</span><span class="cn">NULL</span>)</span>
<span id="cb32-167"><a href="#cb32-167" aria-hidden="true" tabindex="-1"></a>importance<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">importance=</span>model<span class="sc">$</span>variable.importance)</span>
<span id="cb32-168"><a href="#cb32-168" aria-hidden="true" tabindex="-1"></a>ordered<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">ordered=</span>model<span class="sc">$</span>ordered)</span>
<span id="cb32-169"><a href="#cb32-169" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">y=</span>model<span class="sc">$</span>y,<span class="at">x=</span>model<span class="sc">$</span>x,<span class="at">model=</span>model<span class="sc">$</span>model)</span>
<span id="cb32-170"><a href="#cb32-170" aria-hidden="true" tabindex="-1"></a>call<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">call=</span><span class="fu">call_to_string</span>(model))</span>
<span id="cb32-171"><a href="#cb32-171" aria-hidden="true" tabindex="-1"></a>result<span class="ot">&lt;-</span><span class="fu">list</span>(<span class="at">frame=</span>frame,<span class="at">cp=</span>cp,<span class="at">parameters=</span>parameters,<span class="at">splits=</span>splits,<span class="at">importance=</span>importance,<span class="at">ordered=</span>ordered,<span class="at">call=</span>call)</span>
<span id="cb32-172"><a href="#cb32-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-173"><a href="#cb32-173" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(result)</span>
<span id="cb32-174"><a href="#cb32-174" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-175"><a href="#cb32-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-176"><a href="#cb32-176" aria-hidden="true" tabindex="-1"></a><span class="in">`result`</span> bundles the pruned model's internals — node <span class="in">`frame`</span> (one row per node), the <span class="in">`cp`</span> table, control <span class="in">`parameters`</span>, raw <span class="in">`splits`</span>, <span class="in">`importance`</span>, factor-<span class="in">`ordered`</span> flags, and the model <span class="in">`call`</span> — for programmatic inspection or export, without needing to pick through <span class="in">`model`</span>'s S3 structure directly.</span>
<span id="cb32-177"><a href="#cb32-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-178"><a href="#cb32-178" aria-hidden="true" tabindex="-1"></a><span class="fu">## Rpart Regression</span></span>
<span id="cb32-179"><a href="#cb32-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-180"><a href="#cb32-180" aria-hidden="true" tabindex="-1"></a>The regression tree predicts <span class="in">`medv`</span> (median owner-occupied home value, in $1000s) from the 13 other variables in the classic <span class="in">`MASS::Boston`</span> housing dataset.</span>
<span id="cb32-181"><a href="#cb32-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-182"><a href="#cb32-182" aria-hidden="true" tabindex="-1"></a><span class="fu">### Growing and pruning the tree</span></span>
<span id="cb32-183"><a href="#cb32-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-184"><a href="#cb32-184" aria-hidden="true" tabindex="-1"></a><span class="in">```{r regression_prune,echo=TRUE}</span></span>
<span id="cb32-185"><a href="#cb32-185" aria-hidden="true" tabindex="-1"></a>result<span class="ot">&lt;-</span><span class="fu">data.frame</span>(rtree_regression<span class="sc">$</span>cptable)</span>
<span id="cb32-186"><a href="#cb32-186" aria-hidden="true" tabindex="-1"></a>result<span class="sc">$</span>nsplit<span class="ot">&lt;-</span><span class="fu">factor</span>(result<span class="sc">$</span>nsplit<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb32-187"><a href="#cb32-187" aria-hidden="true" tabindex="-1"></a>minimun_size<span class="ot">&lt;-</span><span class="fu">as.numeric</span>(<span class="fu">as.character</span>(result[<span class="fu">which.min</span>(result[,<span class="st">"xerror"</span>]),<span class="st">"nsplit"</span>]))</span>
<span id="cb32-188"><a href="#cb32-188" aria-hidden="true" tabindex="-1"></a>initial_model<span class="ot">&lt;-</span>rtree_regression</span>
<span id="cb32-189"><a href="#cb32-189" aria-hidden="true" tabindex="-1"></a>model<span class="ot">&lt;-</span>rpart<span class="sc">::</span><span class="fu">prune</span>(rtree_regression,<span class="at">cp=</span>rtree_regression<span class="sc">$</span>cptable[<span class="fu">which.min</span>(rtree_regression<span class="sc">$</span>cptable[,<span class="st">"xerror"</span>]),<span class="st">"CP"</span>])</span>
<span id="cb32-190"><a href="#cb32-190" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-191"><a href="#cb32-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-192"><a href="#cb32-192" aria-hidden="true" tabindex="-1"></a>As with the classification tree, <span class="in">`rtree_regression`</span> is pruned to the <span class="in">`CP`</span> value that minimizes the cross-validated error — here, cross-validated sum-of-squares error rather than a classification loss. In this run the minimum <span class="in">`xerror`</span> is again at the largest tree in the <span class="in">`cptable`</span>, so the pruned tree keeps all <span class="in">`r sum(model$frame$var=="&lt;leaf&gt;")`</span> terminal nodes of the grown tree.</span>
<span id="cb32-193"><a href="#cb32-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-194"><a href="#cb32-194" aria-hidden="true" tabindex="-1"></a><span class="fu">### Variable importance</span></span>
<span id="cb32-195"><a href="#cb32-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-196"><a href="#cb32-196" aria-hidden="true" tabindex="-1"></a><span class="in">```{r regression_importance,echo=TRUE,dev='png'}</span></span>
<span id="cb32-197"><a href="#cb32-197" aria-hidden="true" tabindex="-1"></a>importance<span class="ot">&lt;-</span>model<span class="sc">$</span>variable.importance</span>
<span id="cb32-198"><a href="#cb32-198" aria-hidden="true" tabindex="-1"></a>importance<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">names=</span><span class="fu">names</span>(importance),<span class="at">importance=</span>importance)</span>
<span id="cb32-199"><a href="#cb32-199" aria-hidden="true" tabindex="-1"></a>importance<span class="sc">$</span>names<span class="ot">&lt;-</span><span class="fu">factor</span>(importance<span class="sc">$</span>names,<span class="at">levels=</span><span class="fu">rev</span>(<span class="fu">as.character</span>(importance<span class="sc">$</span>names)))</span>
<span id="cb32-200"><a href="#cb32-200" aria-hidden="true" tabindex="-1"></a>plot_importance<span class="ot">&lt;-</span><span class="fu">ggplot</span>(importance,<span class="fu">aes</span>(<span class="at">x=</span>names,<span class="at">y=</span>importance))<span class="sc">+</span></span>
<span id="cb32-201"><a href="#cb32-201" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">'identity'</span>)<span class="sc">+</span></span>
<span id="cb32-202"><a href="#cb32-202" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Importance Plot"</span>,<span class="at">y=</span><span class="st">"Importance (sum of split improvements)"</span>,<span class="at">x=</span><span class="st">"Predictor"</span>)<span class="sc">+</span></span>
<span id="cb32-203"><a href="#cb32-203" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size=</span><span class="dv">10</span>)<span class="sc">+</span></span>
<span id="cb32-204"><a href="#cb32-204" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits=</span><span class="fu">rev</span>(<span class="fu">levels</span>(names)))<span class="sc">+</span></span>
<span id="cb32-205"><a href="#cb32-205" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span>
<span id="cb32-206"><a href="#cb32-206" aria-hidden="true" tabindex="-1"></a>plot_importance</span>
<span id="cb32-207"><a href="#cb32-207" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-208"><a href="#cb32-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-209"><a href="#cb32-209" aria-hidden="true" tabindex="-1"></a>For Boston housing, <span class="in">`rm`</span> (average rooms per dwelling) and <span class="in">`lstat`</span> (% lower-status population) are almost always the two dominant predictors of <span class="in">`medv`</span> — this importance ranking is the tree-based analogue of the strong linear associations well known from OLS models fit to this same dataset.</span>
<span id="cb32-210"><a href="#cb32-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-211"><a href="#cb32-211" aria-hidden="true" tabindex="-1"></a><span class="fu">### The full, unpruned tree</span></span>
<span id="cb32-212"><a href="#cb32-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-213"><a href="#cb32-213" aria-hidden="true" tabindex="-1"></a><span class="in">```{r regression_full_tree_text,echo=TRUE}</span></span>
<span id="cb32-214"><a href="#cb32-214" aria-hidden="true" tabindex="-1"></a>rtree_regression</span>
<span id="cb32-215"><a href="#cb32-215" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-216"><a href="#cb32-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-217"><a href="#cb32-217" aria-hidden="true" tabindex="-1"></a>The unpruned tree's text form: each node reports its split rule, the number of training observations reaching it (<span class="in">`n`</span>), the deviance (residual sum of squares) within the node, and the predicted <span class="in">`medv`</span> (the node mean).</span>
<span id="cb32-218"><a href="#cb32-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-219"><a href="#cb32-219" aria-hidden="true" tabindex="-1"></a><span class="fu">### Choosing the tree size via cross-validation</span></span>
<span id="cb32-220"><a href="#cb32-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-221"><a href="#cb32-221" aria-hidden="true" tabindex="-1"></a><span class="in">```{r regression_cv_size,echo=TRUE,dev='png'}</span></span>
<span id="cb32-222"><a href="#cb32-222" aria-hidden="true" tabindex="-1"></a>rpart<span class="sc">::</span><span class="fu">plotcp</span>(model)</span>
<span id="cb32-223"><a href="#cb32-223" aria-hidden="true" tabindex="-1"></a>rpart<span class="sc">::</span><span class="fu">rsq.rpart</span>(model)</span>
<span id="cb32-224"><a href="#cb32-224" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-225"><a href="#cb32-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-226"><a href="#cb32-226" aria-hidden="true" tabindex="-1"></a>Here <span class="in">`rsq.rpart()`</span>'s R² panel is a literal R²: the proportion of <span class="in">`medv`</span>'s variance explained, both on the training data (apparent) and under cross-validation. The gap between the two lines is the model's optimism — how much worse the tree performs on unseen data than on the data it was fit to. Here it grows from about <span class="in">`r round(diff(rev(1-model$cptable[2,c("rel error","xerror")])),2)`</span> after one split to about <span class="in">`r round(diff(rev(1-model$cptable[nrow(model$cptable),c("rel error","xerror")])),2)`</span> at the largest tree (apparent R² ≈ <span class="in">`r sprintf("%.2f",1-model$cptable[nrow(model$cptable),"rel error"])`</span> vs. cross-validated ≈ <span class="in">`r sprintf("%.2f",1-model$cptable[nrow(model$cptable),"xerror"])`</span>), while cross-validated R² is still at its maximum at the largest tree, so no pruning was needed.</span>
<span id="cb32-227"><a href="#cb32-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-228"><a href="#cb32-228" aria-hidden="true" tabindex="-1"></a><span class="fu">### Error-by-size summary</span></span>
<span id="cb32-229"><a href="#cb32-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-230"><a href="#cb32-230" aria-hidden="true" tabindex="-1"></a><span class="in">```{r regression_prune_plot,echo=TRUE,dev='png'}</span></span>
<span id="cb32-231"><a href="#cb32-231" aria-hidden="true" tabindex="-1"></a>error<span class="ot">&lt;-</span><span class="fu">data.frame</span>(model<span class="sc">$</span>cptable)</span>
<span id="cb32-232"><a href="#cb32-232" aria-hidden="true" tabindex="-1"></a>error<span class="sc">$</span>nsplit<span class="ot">&lt;-</span><span class="fu">factor</span>(error<span class="sc">$</span>nsplit<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb32-233"><a href="#cb32-233" aria-hidden="true" tabindex="-1"></a>tree_size<span class="ot">&lt;-</span>error[<span class="fu">which.min</span>(error[,<span class="st">"xerror"</span>]),<span class="st">"nsplit"</span>]</span>
<span id="cb32-234"><a href="#cb32-234" aria-hidden="true" tabindex="-1"></a>error<span class="ot">&lt;-</span>reshape2<span class="sc">::</span><span class="fu">melt</span>(error,<span class="at">id.vars=</span><span class="st">"nsplit"</span>)</span>
<span id="cb32-235"><a href="#cb32-235" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(error)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"Split"</span>,<span class="st">"Metric"</span>,<span class="st">"value"</span>)</span>
<span id="cb32-236"><a href="#cb32-236" aria-hidden="true" tabindex="-1"></a>plot_prune<span class="ot">&lt;-</span><span class="fu">ggplot</span>(error,<span class="fu">aes</span>(<span class="at">x=</span>Split,<span class="at">y=</span>value,<span class="at">color=</span>Metric))<span class="sc">+</span></span>
<span id="cb32-237"><a href="#cb32-237" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group=</span>Metric))<span class="sc">+</span></span>
<span id="cb32-238"><a href="#cb32-238" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb32-239"><a href="#cb32-239" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="fu">paste</span>(<span class="st">"Error Plot"</span>,<span class="st">"Suggested Size:"</span>,tree_size),<span class="at">y=</span><span class="st">"Metric value"</span>,<span class="at">x=</span><span class="st">"Size of Tree"</span>)<span class="sc">+</span></span>
<span id="cb32-240"><a href="#cb32-240" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size=</span><span class="dv">10</span>)</span>
<span id="cb32-241"><a href="#cb32-241" aria-hidden="true" tabindex="-1"></a>plot_prune</span>
<span id="cb32-242"><a href="#cb32-242" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-243"><a href="#cb32-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-244"><a href="#cb32-244" aria-hidden="true" tabindex="-1"></a>Same four <span class="in">`cptable`</span> series (<span class="in">`CP`</span>, <span class="in">`rel error`</span>, <span class="in">`xerror`</span>, <span class="in">`xstd`</span>) as in the classification section, plotted against tree size (<span class="in">`nsplit + 1`</span>), with the size at minimum <span class="in">`xerror`</span> (<span class="in">`r as.character(tree_size)`</span> terminal nodes) called out in the title.</span>
<span id="cb32-245"><a href="#cb32-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-246"><a href="#cb32-246" aria-hidden="true" tabindex="-1"></a><span class="fu">### The pruned tree diagram</span></span>
<span id="cb32-247"><a href="#cb32-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-248"><a href="#cb32-248" aria-hidden="true" tabindex="-1"></a><span class="in">```{r regression_final_tree,echo=TRUE,dev='png'}</span></span>
<span id="cb32-249"><a href="#cb32-249" aria-hidden="true" tabindex="-1"></a>rpart.plot<span class="sc">::</span><span class="fu">rpart.plot</span>(model,<span class="at">type=</span><span class="dv">1</span>)</span>
<span id="cb32-250"><a href="#cb32-250" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-251"><a href="#cb32-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-252"><a href="#cb32-252" aria-hidden="true" tabindex="-1"></a>Each box shows the node's predicted <span class="in">`medv`</span> and the percentage of observations it contains. Following the splits down — typically starting with <span class="in">`rm`</span> or <span class="in">`lstat`</span> — shows how the tree partitions the housing stock into progressively more homogeneous price segments, e.g. dwellings with the most rooms (the right-most branch on <span class="in">`rm`</span>) land in the highest-value leaf (mean <span class="in">`medv`</span> ≈ <span class="in">`r round(max(model$frame$yval[model$frame$var=="&lt;leaf&gt;"]),1)`</span>), while smaller homes in high-<span class="in">`lstat`</span> areas land in the lowest (≈ <span class="in">`r round(min(model$frame$yval[model$frame$var=="&lt;leaf&gt;"]),1)`</span>).</span>
<span id="cb32-253"><a href="#cb32-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-254"><a href="#cb32-254" aria-hidden="true" tabindex="-1"></a><span class="fu">### Raw model components</span></span>
<span id="cb32-255"><a href="#cb32-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-256"><a href="#cb32-256" aria-hidden="true" tabindex="-1"></a><span class="in">```{r regression_export,echo=TRUE}</span></span>
<span id="cb32-257"><a href="#cb32-257" aria-hidden="true" tabindex="-1"></a>frame<span class="ot">&lt;-</span><span class="fu">data.frame</span>(model<span class="sc">$</span>frame)</span>
<span id="cb32-258"><a href="#cb32-258" aria-hidden="true" tabindex="-1"></a>cp<span class="ot">&lt;-</span><span class="fu">data.frame</span>(model<span class="sc">$</span>cptable)</span>
<span id="cb32-259"><a href="#cb32-259" aria-hidden="true" tabindex="-1"></a>parameters<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">parameters=</span><span class="fu">unlist</span>(model<span class="sc">$</span>control))</span>
<span id="cb32-260"><a href="#cb32-260" aria-hidden="true" tabindex="-1"></a>splits<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">name=</span><span class="fu">row.names</span>(model<span class="sc">$</span>splits),model<span class="sc">$</span>splits,<span class="at">row.names=</span><span class="cn">NULL</span>)</span>
<span id="cb32-261"><a href="#cb32-261" aria-hidden="true" tabindex="-1"></a>importance<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">importance=</span>model<span class="sc">$</span>variable.importance)</span>
<span id="cb32-262"><a href="#cb32-262" aria-hidden="true" tabindex="-1"></a>ordered<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">ordered=</span>model<span class="sc">$</span>ordered)</span>
<span id="cb32-263"><a href="#cb32-263" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">y=</span>model<span class="sc">$</span>y,<span class="at">x=</span>model<span class="sc">$</span>x,<span class="at">model=</span>model<span class="sc">$</span>model)</span>
<span id="cb32-264"><a href="#cb32-264" aria-hidden="true" tabindex="-1"></a>call<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">call=</span><span class="fu">call_to_string</span>(model))</span>
<span id="cb32-265"><a href="#cb32-265" aria-hidden="true" tabindex="-1"></a>result<span class="ot">&lt;-</span><span class="fu">list</span>(<span class="at">frame=</span>frame,<span class="at">cp=</span>cp,<span class="at">parameters=</span>parameters,<span class="at">splits=</span>splits,<span class="at">importance=</span>importance,<span class="at">ordered=</span>ordered,<span class="at">call=</span>call)</span>
<span id="cb32-266"><a href="#cb32-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-267"><a href="#cb32-267" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(result)</span>
<span id="cb32-268"><a href="#cb32-268" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb32-269"><a href="#cb32-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-270"><a href="#cb32-270" aria-hidden="true" tabindex="-1"></a>Same bundling as the classification section — the pruned regression model's <span class="in">`frame`</span>, <span class="in">`cp`</span> table, <span class="in">`parameters`</span>, <span class="in">`splits`</span>, <span class="in">`importance`</span>, <span class="in">`ordered`</span> flags, and <span class="in">`call`</span>.</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>