---
comments: false
title: "Worked Examples in R"
---

Worked examples of statistical modelling, machine learning and psychometrics in R.

| Topic | Tutorial |
|---|---|
| Machine learning | [Regression and Classification Trees](EXAMPLE_DECISION_TREE.rmd) |
| Machine learning | [Linear Discriminant Analysis](EXAMPLE_LDA.rmd) |
| Machine learning | [Regularized Regression: Ridge, Heteroscedastic Ridge, Lasso, and Elastic Net](EXAMPLE_REGULARIZED_REGRESSION.Rmd) |
| Machine learning | [MNIST in Keras](EXAMPLE_MNIST.rmd) |
| Psychometrics    | [Measurement Invariance](EXAMPLE_MEASUREMENT_INVARIANCE.rmd) |
| Psychometrics    | [Multitrait Multimethod](EXAMPLE_MULTITRAIT_MULTIMETHOD.rmd) |
| Psychometrics    | [Thurstonian IRT Example](EXAMPLE_TIRT.rmd) |
| Psychometrics    | [Βαθμολόγηση Thurstonian IRT — Θεωρία και Εφαρμογή](EXAMPLE_TIRT_SCORING_GR.Rmd) |
| Adaptive testing | [CAT Simulation](EXAMPLE_SIMULATION_catR.rmd) |
| Adaptive testing | [Multistage Testing (MST)](EXAMPLE_MSTR.rmd) |
| Statistics       | [A Gallery of Statistical Paradoxes](EXAMPLE_PARADOX.Rmd) |
| Statustics       | [Generalized Linead Models](EXAMPLE_GENERALIZED.rmd) |
