{
  "hash": "6e41080b7beb9147944153ceeca988d8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"EAP Modified GRM Ability Estimation in base R\"\ndescription: \"Muraki's modified graded response model (catR MGRM, mirt grsm): GRM slopes with shared category thresholds.\"\n---\n\n\n\n# Background\n\n## Acknowledgement\n\nThe functions in [`cat_eap_common.R`](https://github.com/sedzinfo/rwf/blob/main/working_examples/cat_eap_common.R) and [`cat_eap_ggrm.R`](https://github.com/sedzinfo/rwf/blob/main/working_examples/cat_eap_ggrm.R) are adapted from the source code of the **catR** package by David Magis, Gilles Raîche and Juan Ramón Barrada (Magis & Raîche, 2012; Magis & Barrada, 2017). The model parameterisations, the formulas for the response probabilities and their derivatives, the item information, maximum-information item selection and the trapezoidal EAP integration all follow catR's `Pi()`, `Ii()`, `nextItem()`, `eapEst()`, `eapSem()` and `integrate.catR()`, and much of the code keeps catR's structure line for line. The purpose of the rewrite is teaching, not replacement: every step is written out in plain base R so that it can be read, and catR remains the reference implementation that every function is checked against below. catR is free software distributed under the GNU General Public License (version 3 or later).\n\n## Description\n\nThe companion vignette on dichotomous items builds the whole EAP pipeline, item information and next-item selection included, for items scored right/wrong under the 4PL model. This vignette does the same job for **polytomous** items — a Likert scale scored 0, 1, 2, 3, 4 — under Muraki's **modified graded response model**.\n\nThe model goes by several names, so it is worth fixing them once. Muraki (1990) introduced it as a modification of Samejima's (1969) **graded response model (GRM)**. `catR` calls it `\"MGRM\"`. `mirt` calls it the **graded rating scale model** (`itemtype = \"grsm\"`). And `cat_eap_ggrm.R` calls it the **generalized graded response model**, which is where the `_ggrm` suffix of its function names comes from. Despite that name the model is not a generalisation of the GRM but a **restriction** of it: every item keeps its own discrimination, but the spacing between its thresholds is shared by all the items that use the same rating scale. The vignette keeps the file's function names and otherwise calls the model the modified GRM, or MGRM.\n\n[`working_examples/cat_eap_ggrm.R`](https://github.com/sedzinfo/rwf/blob/main/working_examples/cat_eap_ggrm.R) implements the model-specific part of the pipeline in six small functions, and [`working_examples/cat_eap_common.R`](https://github.com/sedzinfo/rwf/blob/main/working_examples/cat_eap_common.R) supplies the two helpers every model shares. All eight are written in base R with no runtime dependency on `catR`:\n\n| Function | File | Purpose | `catR` equivalent it mirrors |\n|---|---|---|---|\n| `density_function()` | `cat_eap_common.R` | Normal density (the prior) | `stats::dnorm()` |\n| `integrate_cat()` | `cat_eap_common.R` | Numerical integration (trapezoidal rule) | `catR::integrate.catR()` |\n| `compute_pi_ggrm()` | `cat_eap_ggrm.R` | Category response probabilities and their first three derivatives | `catR::Pi(model=\"MGRM\")` |\n| `compute_ii_ggrm()` | `cat_eap_ggrm.R` | Item information and its first two derivatives | `catR::Ii(model=\"MGRM\")` |\n| `compute_next_item_ggrm()` | `cat_eap_ggrm.R` | Maximum Fisher information item selection, with randomesque exposure control | `catR::nextItem(model=\"MGRM\", criterion=\"MFI\")` |\n| `compute_likelihood_ggrm()` | `cat_eap_ggrm.R` | Likelihood of a polytomous response pattern | *(internal to `catR::eapEst()`)* |\n| `compute_eap_ggrm()` | `cat_eap_ggrm.R` | EAP ability estimate | `catR::eapEst(model=\"MGRM\")` |\n| `compute_eap_se_ggrm()` | `cat_eap_ggrm.R` | EAP standard error | `catR::eapSem(model=\"MGRM\")` |\n\nThe sections below walk through the theory behind each function, validate every one of them against its `catR` counterpart, work through four properties that follow from the model's restricted form, run a small adaptive test end to end, and close with the numerical side: the integration settings and the floating-point precision of the category probabilities.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(catR)\nsource(\"R/cat_eap_common.R\", local = knitr::knit_global())\nsource(\"R/cat_eap_ggrm.R\", local = knitr::knit_global())\n# the graded response model functions, needed only for the comparison with the GRM\nsource(\"R/cat_eap_grm.R\", local = knitr::knit_global())\n```\n:::\n\n\n---\n\n## Theoretical Background\n\n### Cumulative curves first, categories second\n\nA dichotomous model needs one curve per item: the probability of a correct response. A polytomous item scored $0,1,\\ldots,m$ needs $m+1$ curves — one per category — that sum to 1 at every ability level. The graded response family builds them in two steps. First, for each $k = 1,\\ldots,m$ it models the **cumulative** probability of responding in category $k$ *or above* with a 2PL curve,\n\n$$P^*_{jk}(\\theta) = P(X_j \\ge k \\mid \\theta) = \\frac{\\exp\\big[D\\alpha_j(\\theta - \\beta_{jk})\\big]}{1 + \\exp\\big[D\\alpha_j(\\theta - \\beta_{jk})\\big]},$$\n\nwith the two boundary curves fixed at $P^*_{j0} = 1$ (every response is in category 0 or above) and $P^*_{j,m+1} = 0$. Second, the probability of category $k$ is the difference between two adjacent cumulative curves:\n\n$$P_{jk}(\\theta) = P(X_j = k \\mid \\theta) = P^*_{jk}(\\theta) - P^*_{j,k+1}(\\theta), \\qquad k = 0,\\ldots,m,$$\n\nso the lowest category has $P_{j0} = 1 - P^*_{j1}$ and the highest $P_{jm} = P^*_{jm}$. This makes the model **cumulative**: the threshold $\\beta_{jk}$ is the ability at which \"category $k$ or above\" becomes more likely than \"below $k$\". The rating scale and partial credit models are **adjacent-category** models instead: they compare each category with its neighbour and divide by a normalising total. For every difference to be a positive probability the cumulative curves must never cross or coincide, and since all $m$ curves of an item share the slope $\\alpha_j$, that means the thresholds must be strictly increasing, $\\beta_{j1} < \\beta_{j2} < \\cdots < \\beta_{jm}$.\n\n### The modified GRM: a location and shared category parameters\n\nIn Samejima's GRM every item has its own $m$ thresholds. Muraki's modification writes each threshold as an item location minus a category parameter,\n\n$$\\beta_{jk} = b_j - c_k, \\qquad\nP^*_{jk}(\\theta) = \\frac{\\exp\\big[D\\alpha_j(\\theta - b_j + c_k)\\big]}{1 + \\exp\\big[D\\alpha_j(\\theta - b_j + c_k)\\big]}.$$\n\n- $\\alpha_j$ — the **item discrimination**, item specific: the common slope of all $m$ cumulative curves of item $j$.\n- $b_j$ — the **item location**, item specific: it moves all the thresholds of item $j$ together.\n- $c_1,\\ldots,c_m$ — the **category parameters**, shared by every item of a **block**, a set of items answered on the same rating scale. They fix the spacing of the thresholds, which is therefore the same for every item of the block.\n- $D$ — the usual metric constant (1, or 1.702 for the normal-ogive metric).\n\nBecause $\\beta_{jk} = b_j - c_k$ must increase with $k$, the category parameters must be **strictly decreasing**, $c_1 > c_2 > \\cdots > c_m$.\n\nThe restriction relates the MGRM to the GRM the way the rating scale model relates to the partial credit model: one set of step parameters per block instead of one per item. Unlike the rating scale model it keeps the item discrimination. For a single block of $n$ items with $m+1$ categories the GRM has $n(m+1)$ item parameters and the MGRM $2n + m - 1$; the $-1$ is the identifiability constraint.\n\n**Identifiability.** Only the differences $b_j - c_k$ enter the model, so adding the same constant $t$ to every $b_j$ and every $c_k$ of a block leaves every threshold, and therefore every probability, unchanged:\n\n$$\\big(b_j + t\\big) - \\big(c_k + t\\big) = b_j - c_k = \\beta_{jk}.$$\n\nOne constraint per block pins the parameters down. Muraki centres the $c_k$ of each block at zero, $\\sum_{k=1}^{m} c_k = 0$, which any solution reaches with $t = -\\bar c$, $\\bar c = \\frac{1}{m}\\sum_{k=1}^{m} c_k$; `mirt` instead sets $b_j = 0$ for the first item of each block, which any solution reaches with $t$ equal to minus that item's location. Both conventions describe the same model and give the same probabilities, which a worked example below demonstrates.\n\n### The bank layout\n\n`cat_eap_ggrm.R` expects one row per item:\n\n| Column | Holds |\n|---|---|\n| 1 | the item discrimination $\\alpha_j$ |\n| 2 | the item location $b_j$ |\n| 3 to $m+2$ | the category parameters $c_1,\\ldots,c_m$ |\n\nA bank for items with $m+1$ categories therefore has $m+2$ columns, and the number of categories is `ncol(bank) - 1`: a five-point Likert scale scored 0 to 4 has $m = 4$ category parameters and needs a six-column bank. The category columns are identical down every row of a block, and a bank with a single block has the same $c_k$ in every row. Items answered on a different rating scale form a block of their own with their own $c_k$ — always the case for items with a different number of categories — and the shorter rows are padded with `NA` on the right. In such a bank $m$ is the number of category parameters of the widest item; item $j$ has $m_j \\le m$ non-`NA` category parameters and the categories $0,\\ldots,m_j$, and every formula below applies to item $j$ with $m$ replaced by $m_j$.\n\nThe columns are read by position, not by name, and each row is read on its own: nothing in the code checks that the rows of a block really share their $c_k$, and a bank in which every row had its own $c_k$ would simply be a GRM bank written in another form. `compute_pi_ggrm()`, which every other model function calls directly or through another one, begins with `bank <- rbind(bank)`, so a single item may also be passed as a plain vector `c(alpha, b, c1, ..., cm)`.\n\n### Derivatives\n\nItem information needs the first derivative of each category probability, and its own derivatives need the second and third. All of them come from the cumulative curves, using the logistic identity $\\frac{d}{d\\theta}P^* = D\\alpha_j P^*(1-P^*)$ repeatedly. `compute_pi_ggrm()` evaluates them recursively, as `catR::Pi()` does:\n\n$$\\frac{dP^*_{jk}}{d\\theta} = D\\alpha_j P^*_{jk}\\big(1-P^*_{jk}\\big), \\qquad\n\\frac{d^2P^*_{jk}}{d\\theta^2} = D\\alpha_j \\frac{dP^*_{jk}}{d\\theta}\\big(1-2P^*_{jk}\\big),$$\n\n$$\\frac{d^3P^*_{jk}}{d\\theta^3} = D\\alpha_j\\left[\\frac{d^2P^*_{jk}}{d\\theta^2} - 2\\left(\\frac{dP^*_{jk}}{d\\theta}\\right)^2 - 2P^*_{jk}\\,\\frac{d^2P^*_{jk}}{d\\theta^2}\\right].$$\n\nSubstituting each line into the next gives the closed forms, with $W_{jk} = P^*_{jk}\\big(1-P^*_{jk}\\big)$:\n\n$$\\frac{dP^*_{jk}}{d\\theta} = D\\alpha_j W_{jk}, \\qquad\n\\frac{d^2P^*_{jk}}{d\\theta^2} = D^2\\alpha_j^2 W_{jk}\\big(1-2P^*_{jk}\\big), \\qquad\n\\frac{d^3P^*_{jk}}{d\\theta^3} = D^3\\alpha_j^3 W_{jk}\\big(1-6P^*_{jk}+6P^{*2}_{jk}\\big).$$\n\nThe boundary curves $P^*_{j0}=1$ and $P^*_{j,m+1}=0$ are constants with zero derivatives of every order ($W_{j0} = W_{j,m+1} = 0$), and differentiation is linear, so every derivative of a category probability is the same difference of two adjacent cumulative derivatives. Writing primes for derivatives with respect to $\\theta$, for $k = 0,\\ldots,m$:\n\n$$\n\\begin{aligned}\nP'_{jk} &= D\\alpha_j\\big[W_{jk} - W_{j,k+1}\\big],\\\\\nP''_{jk} &= D^2\\alpha_j^2\\big[W_{jk}\\big(1-2P^*_{jk}\\big) - W_{j,k+1}\\big(1-2P^*_{j,k+1}\\big)\\big],\\\\\nP'''_{jk} &= D^3\\alpha_j^3\\big[W_{jk}\\big(1-6P^*_{jk}+6P^{*2}_{jk}\\big) - W_{j,k+1}\\big(1-6P^*_{j,k+1}+6P^{*2}_{j,k+1}\\big)\\big].\n\\end{aligned}\n$$\n\n`compute_pi_ggrm()` returns the four matrices `Pi`, `dPi`, `d2Pi` and `d3Pi`, holding $P_{jk}$, $P'_{jk}$, $P''_{jk}$ and $P'''_{jk}$, one row per item and one column per category: column $k+1$ (named `cat0`, `cat1`, …) holds category $k$. For an item with $m_j < m$ category parameters, the entries for the categories $k = m_j+1,\\ldots,m$ are `NA` in all four matrices.\n\n### No probability floor\n\nThe dichotomous code replaces a probability of exactly 0 or 1 by $10^{-10}$ or $1-10^{-10}$, as `catR::Pi()` does for dichotomous items. For the MGRM neither `compute_pi_ggrm()` nor `catR::Pi()` floors, clips or renormalises anything: the category probabilities are exactly the differences above. They are positive and sum to 1 when the category parameters are strictly decreasing, but far above an item's thresholds every category except the highest is the difference of two cumulative probabilities close to 1, so it loses precision and can come out as exactly 0; a worked example below measures the error. The only numerical guard is in `compute_ii_ggrm()`, which sums the information terms with `na.rm = TRUE`. That skips the `NA` entries of padded categories, and also any term that is $0/0$ because $P_{jk}$ has rounded to exactly 0 (its derivatives, computed from the same rounded cumulative probabilities, are then exactly 0 as well), so the information stays finite.\n\n### The metric constant $D$\n\n$D$ appears only in the product $D\\alpha_j$, so for every $\\theta$\n\n$$P_{jk}\\big(\\theta;\\,D,\\,\\alpha_j\\big) = P_{jk}\\big(\\theta;\\,1,\\,D\\alpha_j\\big).$$\n\nSetting $D = 1.702$ is therefore exactly the same model as keeping $D = 1$ and multiplying every discrimination by 1.702: it rescales the slopes and leaves the locations and category parameters alone. `catR::Pi(model = \"MGRM\")` applies $D$ in the same place, and every function that takes $D$ is checked against `catR` at both values below. $D$ must match the metric on which the item parameters were calibrated; parameters from `mirt` are on the $D = 1$ metric.\n\n### Item information\n\nFor a dichotomous item Fisher information is $I_j(\\theta) = P'^2/\\big(P(1-P)\\big)$. The polytomous generalisation sums the same quantity over categories, and **test information** is the sum of the item informations:\n\n$$I_j(\\theta) = \\sum_{k=0}^{m} \\frac{\\big[P'_{jk}(\\theta)\\big]^2}{P_{jk}(\\theta)}, \\qquad I(\\theta) = \\sum_{j=1}^{n} I_j(\\theta).$$\n\n`compute_ii_ggrm()` evaluates $I_j$ in exactly this form from the matrices of `compute_pi_ggrm()` and returns one value per item, so test information is the sum of its `Ii`. For $m = 1$ the two categories are $P$ and $1-P$ with derivatives $P'$ and $-P'$, and the sum collapses to the dichotomous formula: the item is a 2PL item with difficulty $b_j - c_1$, and $I_j = D^2\\alpha_j^2\\,P^*_{j1}\\big(1-P^*_{j1}\\big)$. `compute_ii_ggrm()` also returns the first and second derivatives of the item information with respect to $\\theta$, obtained by differentiating each category term $P'^2_{jk}/P_{jk}$ and summing:\n\n$$I'_j = \\sum_{k} \\left[\\frac{2P'_{jk}P''_{jk}}{P_{jk}} - \\frac{P'^3_{jk}}{P^2_{jk}}\\right], \\qquad\nI''_j = \\sum_{k} \\left[\\frac{2P''^2_{jk} + 2P'_{jk}P'''_{jk}}{P_{jk}} - \\frac{5P'^2_{jk}P''_{jk}}{P^2_{jk}} + \\frac{2P'^4_{jk}}{P^3_{jk}}\\right].$$\n\nNeither EAP scoring nor MFI selection uses $I'_j$ and $I''_j$; they are returned because `catR::Ii()` returns them.\n\nWriting $\\Psi$ for the logistic function and $\\psi = \\Psi(1-\\Psi)$ for its derivative, the information of an MGRM item can be written as\n\n$$I_j(\\theta) = D^2\\alpha_j^2 \\sum_{k=0}^{m} \\frac{\\big[\\psi(z_{jk}) - \\psi(z_{j,k+1})\\big]^2}{\\Psi(z_{jk}) - \\Psi(z_{j,k+1})},\n\\qquad z_{jk} = D\\alpha_j\\,(\\theta - b_j + c_k),$$\n\nwith the boundary conventions $z_{j0} = +\\infty$ and $z_{j,m+1} = -\\infty$, so that $\\Psi(z_{j0}) = 1$, $\\Psi(z_{j,m+1}) = 0$ and $\\psi(z_{j0}) = \\psi(z_{j,m+1}) = 0$. Two things can be read off. The ability enters only through $\\theta - b_j$, and the $c_k$ are shared, so **two items of a block with the same $\\alpha_j$ have the same information curve, shifted by the difference of their $b_j$**. And $\\alpha_j$ enters twice: as the factor $\\alpha_j^2$ in front, and inside $z_{jk}$, where it sets how far apart the thresholds are relative to the width of each logistic step. So a larger $\\alpha_j$ gives a taller curve whose height grows *roughly*, not exactly, with $\\alpha_j^2$, and a curve that is narrower around each threshold. Both statements are checked numerically in a worked example below.\n\n### Next-item selection\n\nAn adaptive test picks, at each step, the unadministered item that is most informative at the current ability estimate — the **Maximum Fisher Information (MFI)** criterion. `compute_next_item_ggrm()` takes the indices of the items already administered in `out` and chooses among the rest:\n\n$$j^{*} = \\arg\\max_{j\\notin\\texttt{out}} I_j(\\hat\\theta)$$\n\nIt returns the index $j^*$ as `item`, its information $I_{j^*}(\\hat\\theta)$ as `info`, and the indices of the items that were available as `available`; when `out` already holds every item it stops with an error.\n\nWithin a block of equal discriminations the information curves are shifted copies of one another, so the choice depends only on where $\\theta$ sits relative to each $b_j$. With different discriminations the curves differ in height and shape as well, so there is no such shortcut: the information of every available item has to be computed at $\\theta$, and an item with a large $\\alpha_j$ whose thresholds cover the current estimate tends to win most comparisons. That is why the `randomesque` argument matters: instead of always taking the single best item it draws at random from the $k$ most informative ones, the standard way to keep a few items from being administered to almost everyone. Precisely, with\n\n$$k = \\max\\Big(1,\\ \\min\\big(\\lfloor\\texttt{randomesque}\\rfloor,\\ \\text{number of available items}\\big)\\Big),$$\n\nthe next item is drawn with equal probabilities from the $k$ available items with the largest $I_j(\\hat\\theta)$, ties broken by item order as `order()` does; the default `randomesque = 1` is pure MFI and draws no random number.\n\nTwo documented differences from `catR::nextItem()` matter only for exact ties. When several items tie for the maximum, `catR` draws one of them at random while `compute_next_item_ggrm()` takes the first; and with `randomesque` above 1, `catR` also keeps every item tied with the last one kept, so it can draw from more than $k$ items. With `randomesque = 1` and no exact tie the two always choose the same item.\n\n### Likelihood of a response pattern\n\nUnder **local independence**, the likelihood of a response pattern $\\mathbf{x} = (x_1,\\ldots,x_n)$, with each response coded from 0, $x_j \\in \\{0,\\ldots,m\\}$, is\n\n$$L(\\theta) = \\prod_{j=1}^{n} P_{j x_j}(\\theta).$$\n\nThis is the polytomous counterpart of $\\prod_j P_j^{x_j}(1-P_j)^{1-x_j}$: with more than two categories there is nothing for the exponents to switch between, so the response simply indexes a column of the probability matrix. The `x[i]+1` in `compute_likelihood_ggrm()` is index bookkeeping — categories start at 0, R columns at 1 — so $P_{jx_j}$ is read from column $x_j+1$ of row $j$.\n\n### EAP and its standard error\n\nA **prior** $\\pi(\\theta)$ on ability (standard normal by default) turns the likelihood into a posterior, and EAP (Bock & Mislevy, 1982) reports its mean and standard deviation:\n\n$$\\hat\\theta_{EAP} = \\frac{\\displaystyle\\int \\theta\\,\\pi(\\theta)\\,L(\\theta)\\,d\\theta}{\\displaystyle\\int \\pi(\\theta)\\,L(\\theta)\\,d\\theta}\n\\qquad\nSE(\\hat\\theta_{EAP}) = \\sqrt{\\frac{\\displaystyle\\int (\\theta-\\hat\\theta_{EAP})^2\\,\\pi(\\theta)\\,L(\\theta)\\,d\\theta}{\\displaystyle\\int \\pi(\\theta)\\,L(\\theta)\\,d\\theta}}$$\n\nFor a response pattern $\\mathbf{x}$ with likelihood $L$, the three integrands are\n\n$$\n\\begin{aligned}\ng(s) &= s\\,\\pi(s)\\,L(s),\\\\\nh(s) &= \\pi(s)\\,L(s),\\\\\ng_{SE}(s) &= (s-\\hat\\theta_{EAP})^2\\,\\pi(s)\\,L(s).\n\\end{aligned}\n$$\n\nOn the quadrature grid $X=(\\theta_1,\\ldots,\\theta_Q)$, where $Q=\\texttt{nqp}$ and $\\theta_q=\\texttt{lower}+(q-1)(\\texttt{upper}-\\texttt{lower})/(Q-1)$ (by default 33 points from $-4$ to $4$, as in `catR`), the two quantities are approximated by\n\n$$\n\\hat\\theta_{EAP} \\approx \\frac{\\operatorname{Trap}(X,\\,g(X))}{\\operatorname{Trap}(X,\\,h(X))}\n\\qquad\nSE(\\hat\\theta_{EAP}) \\approx \\sqrt{\\frac{\\operatorname{Trap}(X,\\,g_{SE}(X))}{\\operatorname{Trap}(X,\\,h(X))}},\n$$\n\nwhere $g(X)=(g(\\theta_1),\\ldots,g(\\theta_Q))$, likewise for $h$ and $g_{SE}$, and `Trap` denotes the trapezoidal integration implemented by `integrate_cat()` below. `compute_eap_ggrm()` computes the first ratio. `compute_eap_se_ggrm()` computes the second with its `theta` argument in place of $\\hat\\theta_{EAP}$ in $g_{SE}$: passing the EAP estimate gives the posterior standard deviation, and any other value gives the larger root mean squared deviation around that value.\n\nMaximum Likelihood has no finite maximum for a pattern in which every response sits in the lowest category, or every response in the highest: the likelihood keeps increasing towards $\\theta = -\\infty$ or $\\theta = +\\infty$. As long as the category parameters are strictly decreasing, $0 < L(\\theta) \\le 1$; since the normal prior has a finite mean and variance, all three integrals are then finite and the denominator positive for every response pattern, which is how the prior keeps the estimate and its standard error finite.\n\n### Numerical integration and the prior\n\nNone of these integrals has a closed form, so the integrands are evaluated at the `nqp` quadrature points $\\theta_1<\\cdots<\\theta_Q$ and integrated with the **trapezoidal rule**, which approximates the area between two adjacent points by a trapezoid, the width times the average of the two heights:\n\n$$\\int f(\\theta)\\,d\\theta \\approx \\operatorname{Trap}(X,\\,f(X)) = \\sum_{q=1}^{Q-1} (\\theta_{q+1}-\\theta_q)\\,\\frac{f(\\theta_q)+f(\\theta_{q+1})}{2}$$\n\n`integrate_cat()` implements exactly this sum. The prior is the normal density, which `density_function()` writes out longhand:\n\n$$\\pi(\\theta) = \\frac{1}{\\sigma\\sqrt{2\\pi}}\\exp\\!\\left(-\\frac{(\\theta-\\mu)^2}{2\\sigma^2}\\right), \\qquad (\\mu,\\sigma) = \\texttt{priorPar}$$\n\nwith the default `priorPar = c(0, 1)`, the standard normal.\n\n---\n\n# Validation\n\n## The item bank\n\nThe bank from the examples in `cat_eap_ggrm.R`: five items on one five-point rating scale. $\\alpha_j$ and $b_j$ vary across items; the four category parameters are common to all of them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalphaj <- c(1.227, 0.845, 1.694, 1.012, 2.103)\nbj     <- c(-0.482, 0.137, 0.715, -0.936, 0.298)\nc1     <- rep( 1.812, 5)\nc2     <- rep( 0.603, 5)\nc3     <- rep(-0.452, 5)\nc4     <- rep(-1.963, 5)\n\nbank <- matrix(c(alphaj, bj, c1, c2, c3, c4), nrow = 5,\n               dimnames = list(1:5, c(\"alphaj\", \"bj\", \"c1\", \"c2\", \"c3\", \"c4\")))\nbank\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  alphaj     bj    c1    c2     c3     c4\n1  1.227 -0.482 1.812 0.603 -0.452 -1.963\n2  0.845  0.137 1.812 0.603 -0.452 -1.963\n3  1.694  0.715 1.812 0.603 -0.452 -1.963\n4  1.012 -0.936 1.812 0.603 -0.452 -1.963\n5  2.103  0.298 1.812 0.603 -0.452 -1.963\n```\n\n\n:::\n:::\n\n\nThe bank has 6 columns for 5 response categories. The category parameters $1.812 > 0.603 > -0.452 > -1.963$ are strictly decreasing and sum to zero, Muraki's convention.\n\n---\n\n## Validating each piece against `catR`\n\n### Normal density\n\n\n::: {.cell}\n\n```{.r .cell-code}\nv <- seq(-3, 3, by = 0.1)\ncomparison <- data.frame(x = v, density_function = density_function(v), dnorm = dnorm(v))\nhead(comparison)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     x density_function       dnorm\n1 -3.0      0.004431848 0.004431848\n2 -2.9      0.005952532 0.005952532\n3 -2.8      0.007915452 0.007915452\n4 -2.7      0.010420935 0.010420935\n5 -2.6      0.013582969 0.013582969\n6 -2.5      0.017528300 0.017528300\n```\n\n\n:::\n\n```{.r .cell-code}\nall.equal(comparison$density_function, comparison$dnorm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(comparison, aes(x = x)) +\n  geom_line(aes(y = density_function, color = \"density_function()\"), linewidth = 1) +\n  geom_point(aes(y = dnorm, color = \"dnorm()\"), shape = 1) +\n  labs(title = \"Hand-written normal density vs. dnorm()\",\n       x = expression(theta), y = \"density\", color = NULL) +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_ggrm_files/figure-html/density_plot-1.png){width=60%}\n:::\n:::\n\n\nThe function writes out the textbook normal density longhand. It uses `exp(1)` rather than a hard-coded `2.71828`, which is accurate to only six significant digits and, according to its documentation, shifts the EAP estimate in the seventh decimal.\n\n### Numerical integration\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- seq(from = -3, to = 3, length = 33)\ny <- round(exp(x), 2)\nc(integrate_cat = integrate_cat(x, y), integrate.catR = catR::integrate.catR(x, y))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n integrate_cat integrate.catR \n      20.09437       20.09437 \n```\n\n\n:::\n\n```{.r .cell-code}\nall.equal(integrate_cat(x, y), catR::integrate.catR(x, y))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\nBoth approximate $\\int_{-3}^{3} e^x\\,dx$ on the same 33-point trapezoidal grid and return the same number.\n\n### Category response probabilities and derivatives\n\nAt $\\theta = 0$, the probabilities; then, at nine abilities from $-6$ to $6$ and at both metric constants, the largest absolute difference from `catR::Pi()` in each of the four returned matrices, and whether the whole returned list, dimension names included, is identical to `catR`'s:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(compute_pi_ggrm(theta = 0, bank)$Pi, 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          cat0     cat1     cat2     cat3     cat4\nItem1 0.056533 0.152412 0.281853 0.369430 0.139772\nItem2 0.195388 0.207422 0.219110 0.233097 0.144984\nItem3 0.134899 0.412391 0.331060 0.111053 0.010597\nItem4 0.058361 0.115649 0.205929 0.358781 0.261280\nItem5 0.039775 0.305152 0.483888 0.162649 0.008536\n```\n\n\n:::\n\n```{.r .cell-code}\ntheta_check <- c(-6, -4, -2.5, -1, 0, 0.7, 2, 4, 6)\n\npi_diff <- do.call(rbind, lapply(c(1, 1.702), function(D) {\n  do.call(rbind, lapply(theta_check, function(th) {\n    mine   <- compute_pi_ggrm(theta = th, bank, D = D)\n    theirs <- catR::Pi(th = th, bank, model = \"MGRM\", D = D)\n    data.frame(D = D, theta = th,\n               Pi   = max(abs(mine$Pi   - theirs$Pi)),\n               dPi  = max(abs(mine$dPi  - theirs$dPi)),\n               d2Pi = max(abs(mine$d2Pi - theirs$d2Pi)),\n               d3Pi = max(abs(mine$d3Pi - theirs$d3Pi)),\n               identical = identical(mine, theirs))\n  }))\n}))\npi_diff\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       D theta Pi dPi d2Pi d3Pi identical\n1  1.000  -6.0  0   0    0    0      TRUE\n2  1.000  -4.0  0   0    0    0      TRUE\n3  1.000  -2.5  0   0    0    0      TRUE\n4  1.000  -1.0  0   0    0    0      TRUE\n5  1.000   0.0  0   0    0    0      TRUE\n6  1.000   0.7  0   0    0    0      TRUE\n7  1.000   2.0  0   0    0    0      TRUE\n8  1.000   4.0  0   0    0    0      TRUE\n9  1.000   6.0  0   0    0    0      TRUE\n10 1.702  -6.0  0   0    0    0      TRUE\n11 1.702  -4.0  0   0    0    0      TRUE\n12 1.702  -2.5  0   0    0    0      TRUE\n13 1.702  -1.0  0   0    0    0      TRUE\n14 1.702   0.0  0   0    0    0      TRUE\n15 1.702   0.7  0   0    0    0      TRUE\n16 1.702   2.0  0   0    0    0      TRUE\n17 1.702   4.0  0   0    0    0      TRUE\n18 1.702   6.0  0   0    0    0      TRUE\n```\n\n\n:::\n:::\n\n\nThe largest difference over all 18 comparisons and all four matrices is 0, and 18 of the 18 returned lists are identical to `catR`'s: the arithmetic is the same as `catR`'s, operation for operation.\n\nItems answered on a different rating scale form a block with its own category parameters, and a scale with fewer categories leaves its rows padded with `NA`. Here three four-category items (scored 0 to 3, so three category parameters, centred at zero) are added to the bank and compared with `catR` on the same grid:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbank_two_blocks <- rbind(bank,\n                         \"6\" = c(1.400, -0.300, 1.2, 0, -1.2, NA),\n                         \"7\" = c(0.900,  0.500, 1.2, 0, -1.2, NA),\n                         \"8\" = c(1.100,  0.100, 1.2, 0, -1.2, NA))\nP_two_blocks <- compute_pi_ggrm(theta = 0, bank_two_blocks)$Pi\nround(P_two_blocks, 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          cat0     cat1     cat2     cat3     cat4\nItem1 0.056533 0.152412 0.281853 0.369430 0.139772\nItem2 0.195388 0.207422 0.219110 0.233097 0.144984\nItem3 0.134899 0.412391 0.331060 0.111053 0.010597\nItem4 0.058361 0.115649 0.205929 0.358781 0.261280\nItem5 0.039775 0.305152 0.483888 0.162649 0.008536\nItem6 0.109097 0.287420 0.382509 0.220974       NA\nItem7 0.347511 0.263129 0.211367 0.177994       NA\nItem8 0.229701 0.297771 0.279429 0.193099       NA\n```\n\n\n:::\n\n```{.r .cell-code}\nrowSums(P_two_blocks, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nItem1 Item2 Item3 Item4 Item5 Item6 Item7 Item8 \n    1     1     1     1     1     1     1     1 \n```\n\n\n:::\n\n```{.r .cell-code}\nall(sapply(c(1, 1.702), function(D) sapply(theta_check, function(th)\n  identical(compute_pi_ggrm(theta = th, bank_two_blocks, D = D),\n            catR::Pi(th = th, bank_two_blocks, model = \"MGRM\", D = D)))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\nItems 6 to 8 have `NA` for `cat4` — the category does not exist — and the probabilities of every item still sum to 1. All four matrices, `NA`s included, are identical to `catR`'s at every point of the grid; the EAP check below scores a pattern on this bank as well.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheta_grid <- seq(-5, 5, by = 0.05)\ncurves <- t(sapply(theta_grid, function(th) compute_pi_ggrm(theta = th, bank)$Pi[1, ]))\ncumulative <- t(apply(curves, 1, function(p) rev(cumsum(rev(p)))[-1]))   # P(X >= k), k = 1..4\n\ndf_category <- data.frame(theta = theta_grid, curves)\nnames(df_category)[-1] <- paste0(\"category \", 0:4)\ndf_cumulative <- data.frame(theta = theta_grid, cumulative)\nnames(df_cumulative)[-1] <- paste0(\"X >= \", 1:4)\n\ndf_long <- rbind(\n  transform(reshape2::melt(df_cumulative, id.vars = \"theta\",\n                           variable.name = \"curve\", value.name = \"P\"),\n            panel = \"cumulative curves P(X >= k)\"),\n  transform(reshape2::melt(df_category, id.vars = \"theta\",\n                           variable.name = \"curve\", value.name = \"P\"),\n            panel = \"category curves P(X = k)\"))\ndf_long$panel <- factor(df_long$panel, levels = unique(df_long$panel))\n\nggplot(df_long, aes(x = theta, y = P, color = curve)) +\n  geom_line(linewidth = 1) +\n  facet_wrap(~ panel, ncol = 1) +\n  labs(title = \"Item 1: cumulative curves and the category curves they produce\",\n       subtitle = \"each category curve is the gap between two adjacent cumulative curves\",\n       x = expression(theta), y = expression(P(theta)), color = NULL) +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_ggrm_files/figure-html/pi_plot-1.png){width=60%}\n:::\n:::\n\n\nThe top panel shows four parallel 2PL curves, one per threshold of item 1, all with the slope $\\alpha_1$; the bottom panel shows the gaps between them.\n\n### Item information\n\nAt $\\theta = 0$, the information of each item next to `catR::Ii()`; then every element — `Ii`, `dIi` and `d2Ii` — on the same grid of abilities and metric constants, as the largest absolute difference in each:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(mine = compute_ii_ggrm(theta = 0, bank)$Ii,\n           catR = catR::Ii(th = 0, bank, model = \"MGRM\")$Ii)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       mine      catR\n1 0.4620661 0.4620661\n2 0.2278655 0.2278655\n3 0.8510921 0.8510921\n4 0.3159488 0.3159488\n5 1.2588474 1.2588474\n```\n\n\n:::\n\n```{.r .cell-code}\nii_diff <- do.call(rbind, lapply(c(1, 1.702), function(D) {\n  do.call(rbind, lapply(theta_check, function(th) {\n    mine   <- compute_ii_ggrm(theta = th, bank, D = D)\n    theirs <- catR::Ii(th = th, bank, model = \"MGRM\", D = D)\n    data.frame(D = D, theta = th,\n               Ii   = max(abs(mine$Ii   - theirs$Ii)),\n               dIi  = max(abs(mine$dIi  - theirs$dIi)),\n               d2Ii = max(abs(mine$d2Ii - theirs$d2Ii)))\n  }))\n}))\nii_diff\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       D theta Ii dIi d2Ii\n1  1.000  -6.0  0   0    0\n2  1.000  -4.0  0   0    0\n3  1.000  -2.5  0   0    0\n4  1.000  -1.0  0   0    0\n5  1.000   0.0  0   0    0\n6  1.000   0.7  0   0    0\n7  1.000   2.0  0   0    0\n8  1.000   4.0  0   0    0\n9  1.000   6.0  0   0    0\n10 1.702  -6.0  0   0    0\n11 1.702  -4.0  0   0    0\n12 1.702  -2.5  0   0    0\n13 1.702  -1.0  0   0    0\n14 1.702   0.0  0   0    0\n15 1.702   0.7  0   0    0\n16 1.702   2.0  0   0    0\n17 1.702   4.0  0   0    0\n18 1.702   6.0  0   0    0\n```\n\n\n:::\n\n```{.r .cell-code}\nmax(ii_diff[, c(\"Ii\", \"dIi\", \"d2Ii\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninfo_grid <- seq(-4, 4, by = 0.01)\ninfo <- t(sapply(info_grid, function(th) compute_ii_ggrm(th, bank)$Ii))\ndf_info <- data.frame(theta = info_grid, info)\nnames(df_info)[-1] <- paste0(\"item \", 1:5, \" (α=\", alphaj, \", b=\", bj, \")\")\ndf_info_long <- reshape2::melt(df_info, id.vars = \"theta\",\n                               variable.name = \"item\", value.name = \"information\")\n\nggplot(df_info_long, aes(x = theta, y = information, color = item)) +\n  geom_line(linewidth = 1) +\n  labs(title = \"Item information curves\",\n       subtitle = \"height set mainly by the discrimination, position by the item location\",\n       x = expression(theta), y = \"information\", color = NULL) +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_ggrm_files/figure-html/ii_plot-1.png){width=60%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_test <- data.frame(theta = info_grid, information = rowSums(info))\n\nggplot(df_test, aes(x = theta, y = information)) +\n  geom_line(linewidth = 1, color = \"steelblue\") +\n  labs(title = \"Test information\", x = expression(theta), y = \"information\") +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_ggrm_files/figure-html/test_info_plot-1.png){width=60%}\n:::\n:::\n\n\nThe curves differ in height and in shape, not only in position; the worked example on the information curves below separates the part of that caused by the discriminations from the part caused by the shared category parameters.\n\n### Next-item selection\n\nAt $\\theta = 0$, and then across a grid of abilities at both metric constants:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmine   <- compute_next_item_ggrm(theta = 0, bank)\ntheirs <- catR::nextItem(bank, model = \"MGRM\", theta = 0, criterion = \"MFI\")\nc(mine_item = mine$item, catR_item = theirs$item,\n  mine_info = mine$info, catR_info = theirs$info)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmine_item catR_item mine_info catR_info \n 5.000000  5.000000  1.258847  1.258847 \n```\n\n\n:::\n\n```{.r .cell-code}\nnext_diff <- do.call(rbind, lapply(c(1, 1.702), function(D) {\n  do.call(rbind, lapply(seq(-3, 3, by = 0.5), function(th) {\n    mine   <- compute_next_item_ggrm(theta = th, bank, D = D)\n    theirs <- catR::nextItem(bank, model = \"MGRM\", theta = th, criterion = \"MFI\", D = D)\n    data.frame(D = D, theta = th, mine = mine$item, catR = theirs$item,\n               info_difference = abs(mine$info - theirs$info))\n  }))\n}))\nc(agreements = sum(next_diff$mine == next_diff$catR), comparisons = nrow(next_diff),\n  max_info_difference = max(next_diff$info_difference))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         agreements         comparisons max_info_difference \n                 26                  26                   0 \n```\n\n\n:::\n:::\n\n\nWith items already administered excluded via `out`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nout_sets <- list(5, c(5, 3), c(5, 3, 1), c(5, 3, 1, 4))\ndo.call(rbind, lapply(out_sets, function(o) data.frame(\n  out  = paste(o, collapse = \", \"),\n  mine = compute_next_item_ggrm(theta = 0.5, bank, out = o)$item,\n  catR = catR::nextItem(bank, model = \"MGRM\", theta = 0.5, out = o, criterion = \"MFI\")$item)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         out mine catR\n1          5    3    3\n2       5, 3    1    1\n3    5, 3, 1    4    4\n4 5, 3, 1, 4    2    2\n```\n\n\n:::\n:::\n\n\nThe documented differences are in the handling of exact ties, and the first one is easy to show. A bank in which the first two rows are the same item makes the most informative item tied by construction. `catR::nextItem()` re-seeds the random-number generator with `set.seed(NULL)` before it returns, so its draws are made reproducible here with its own `random.seed` argument, one seed per call:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbank_tied_items <- bank[c(1, 1, 2), ]\ntable(mine = replicate(200, compute_next_item_ggrm(theta = -0.8, bank_tied_items)$item))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmine\n  1 \n200 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(catR = sapply(1:200, function(s)\n  catR::nextItem(bank_tied_items, model = \"MGRM\", theta = -0.8, criterion = \"MFI\",\n                 random.seed = s)$item))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncatR\n  1   2 \n107  93 \n```\n\n\n:::\n:::\n\n\n`compute_next_item_ggrm()` takes the first of the tied items every time; `catR` draws between them at random. With continuous item parameters exact ties are rare, which is why the grid comparison above agrees everywhere.\n\n### Likelihood\n\n`catR` has no exported likelihood function to compare against, so the check reconstructs the same product from `catR`'s own probability matrix, $\\prod_j P_{jx_j}$ with $P_{jx_j}$ taken from column $x_j + 1$, at several abilities and both metric constants:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresponse <- c(4, 3, 2, 1, 0)\n\nlik_check <- do.call(rbind, lapply(c(1, 1.702), function(D) {\n  do.call(rbind, lapply(c(-4, -1, 0.3, 2, 4), function(th) {\n    P_catR <- catR::Pi(th = th, bank, model = \"MGRM\", D = D)$Pi\n    mine   <- compute_likelihood_ggrm(theta = th, bank = bank, x = response, D = D)\n    manual <- prod(P_catR[cbind(1:5, response + 1)])\n    data.frame(D = D, theta = th, compute_likelihood_ggrm = mine, from_catR_Pi = manual,\n               relative_difference = abs(mine - manual) / manual)\n  }))\n}))\nlik_check\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       D theta compute_likelihood_ggrm from_catR_Pi relative_difference\n1  1.000  -4.0            1.948919e-09 1.948919e-09        0.000000e+00\n2  1.000  -1.0            3.799937e-05 3.799937e-05        1.783257e-16\n3  1.000   0.3            3.793332e-05 3.793332e-05        0.000000e+00\n4  1.000   2.0            3.458956e-07 3.458956e-07        0.000000e+00\n5  1.000   4.0            1.763794e-11 1.763794e-11        1.831945e-16\n6  1.702  -4.0            7.784494e-15 7.784494e-15        2.026749e-16\n7  1.702  -1.0            5.420947e-07 5.420947e-07        0.000000e+00\n8  1.702   0.3            7.590095e-07 7.590095e-07        1.394964e-16\n9  1.702   2.0            1.674812e-10 1.674812e-10        1.543421e-16\n10 1.702   4.0            2.435776e-18 2.435776e-18        1.581368e-16\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlik_grid <- seq(-4, 4, by = 0.05)\ndf_lik <- data.frame(theta = lik_grid,\n                     likelihood = sapply(lik_grid, function(th)\n                       compute_likelihood_ggrm(th, bank, response)))\n\nggplot(df_lik, aes(x = theta, y = likelihood)) +\n  geom_line(linewidth = 1, color = \"steelblue\") +\n  labs(title = \"Likelihood of the response pattern (4, 3, 2, 1, 0)\",\n       x = expression(theta), y = \"likelihood\") +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_ggrm_files/figure-html/likelihood_plot-1.png){width=60%}\n:::\n:::\n\n\n### EAP ability estimate and standard error\n\nEight patterns on the five-item bank — the five uniform ones, including the two extremes, and three mixed ones — and one on the two-block bank with its `NA` padding, where items 6 to 8 can only be scored 0 to 3, at both metric constants:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npatterns <- list(c(0, 0, 0, 0, 0), c(1, 1, 1, 1, 1), c(2, 2, 2, 2, 2),\n                 c(3, 3, 3, 3, 3), c(4, 4, 4, 4, 4), c(4, 3, 2, 1, 0),\n                 c(0, 1, 2, 3, 4), c(0, 4, 0, 4, 0),\n                 c(4, 3, 2, 1, 0, 3, 0, 2))   # eight responses: the two-block bank\n\nvalidation <- do.call(rbind, lapply(c(1, 1.702), function(D) {\n  do.call(rbind, lapply(patterns, function(x) {\n    b <- if (length(x) == nrow(bank)) bank else bank_two_blocks\n    th_mine <- compute_eap_ggrm(b, x, D = D)\n    th_catR <- catR::eapEst(b, x, model = \"MGRM\", D = D)\n    data.frame(D = D,\n               pattern  = paste(x, collapse = \" \"),\n               eap_mine = th_mine,\n               eap_catR = th_catR,\n               se_mine  = compute_eap_se_ggrm(th_mine, b, x, D = D),\n               se_catR  = catR::eapSem(th_mine, b, x, model = \"MGRM\", D = D))\n  }))\n}))\nvalidation\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       D         pattern    eap_mine    eap_catR   se_mine   se_catR\n1  1.000       0 0 0 0 0 -2.27647790 -2.27647790 0.6028025 0.6028025\n2  1.000       1 1 1 1 1 -0.84240021 -0.84240021 0.4640510 0.4640510\n3  1.000       2 2 2 2 2  0.05112909  0.05112909 0.4575643 0.4575643\n4  1.000       3 3 3 3 3  1.02361816  1.02361816 0.4823409 0.4823409\n5  1.000       4 4 4 4 4  2.53802232  2.53802232 0.5611965 0.5611965\n6  1.000       4 3 2 1 0 -0.22803539 -0.22803539 0.5956929 0.5956929\n7  1.000       0 1 2 3 4  0.47500791  0.47500791 0.5852100 0.5852100\n8  1.000       0 4 0 4 0 -1.25298213 -1.25298213 0.6013998 0.6013998\n9  1.000 4 3 2 1 0 3 0 2  0.04939176  0.04939176 0.5112199 0.5112199\n10 1.702       0 0 0 0 0 -2.53355463 -2.53355463 0.5102942 0.5102942\n11 1.702       1 1 1 1 1 -0.97536710 -0.97536710 0.3390033 0.3390033\n12 1.702       2 2 2 2 2  0.03840348  0.03840348 0.3280065 0.3280065\n13 1.702       3 3 3 3 3  1.12627363  1.12627363 0.3525305 0.3525305\n14 1.702       4 4 4 4 4  2.76338499  2.76338499 0.4365596 0.4365596\n15 1.702       4 3 2 1 0 -0.19980307 -0.19980307 0.5021662 0.5021662\n16 1.702       0 1 2 3 4  0.50665081  0.50665081 0.4545588 0.4545588\n17 1.702       0 4 0 4 0 -1.44666657 -1.44666657 0.4397063 0.4397063\n18 1.702 4 3 2 1 0 3 0 2  0.15770594  0.15770594 0.3906113 0.3906113\n```\n\n\n:::\n\n```{.r .cell-code}\nc(max_eap_difference = max(abs(validation$eap_mine - validation$eap_catR)),\n  max_se_difference  = max(abs(validation$se_mine  - validation$se_catR)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmax_eap_difference  max_se_difference \n      4.440892e-16       1.110223e-16 \n```\n\n\n:::\n:::\n\n\nBoth the point estimate and the standard error reproduce `catR` to machine precision for every pattern, at both metric constants — the largest differences are 4.4e-16 for the estimate and 1.1e-16 for the standard error — including the all-lowest and all-highest patterns, where Maximum Likelihood would have failed outright, and the `NA`-padded items of the two-block bank.\n\n---\n\n# Examples\n\n## Worked example: a restricted graded response model\n\nComputing the thresholds $\\beta_{jk} = b_j - c_k$ turns an MGRM bank into an ordinary GRM bank, laid out the way `cat_eap_grm.R` expects (discrimination, then the $m$ thresholds), with the discriminations unchanged:\n\n$$\\big(\\alpha_j,\\ b_j,\\ c_1,\\ldots,c_m\\big) \\;\\longmapsto\\; \\big(\\alpha_j,\\ b_j - c_1,\\ \\ldots,\\ b_j - c_m\\big).$$\n\nThe thresholds of the bank, and the gaps between consecutive thresholds:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbank_as_grm <- cbind(bank[, \"alphaj\"], bank[, \"bj\"] - bank[, c(\"c1\", \"c2\", \"c3\", \"c4\")])\ncolnames(bank_as_grm) <- c(\"alphaj\", \"betaj1\", \"betaj2\", \"betaj3\", \"betaj4\")\nbank_as_grm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  alphaj betaj1 betaj2 betaj3 betaj4\n1  1.227 -2.294 -1.085 -0.030  1.481\n2  0.845 -1.675 -0.466  0.589  2.100\n3  1.694 -1.097  0.112  1.167  2.678\n4  1.012 -2.748 -1.539 -0.484  1.027\n5  2.103 -1.514 -0.305  0.750  2.261\n```\n\n\n:::\n\n```{.r .cell-code}\nround(t(apply(bank_as_grm[, -1], 1, diff)), 12)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  betaj2 betaj3 betaj4\n1  1.209  1.055  1.511\n2  1.209  1.055  1.511\n3  1.209  1.055  1.511\n4  1.209  1.055  1.511\n5  1.209  1.055  1.511\n```\n\n\n:::\n:::\n\n\nEvery item has its own thresholds, but the gaps between them are the same in every row — 1.209, 1.055, 1.511, the differences $c_k - c_{k+1}$. That is the restriction made concrete: each item's set of thresholds is the same ladder, slid along the ability axis by $b_j$. Passed to `compute_pi_grm()`, the converted bank gives the same output as the original bank passed to `compute_pi_ggrm()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrm_grid <- seq(-4, 4, by = 0.25)\nsame_output <- sapply(grm_grid, function(th)\n  identical(compute_pi_ggrm(th, bank), compute_pi_grm(th, bank_as_grm)))\nc(identical = sum(same_output), grid_points = length(grm_grid))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  identical grid_points \n         33          33 \n```\n\n\n:::\n:::\n\n\nThe two functions return **identical** results — all four matrices, bit for bit — at every one of the 33 grid points. That is not a coincidence of rounding: `compute_pi_ggrm()` forms $b_j - c_k$ as its first step and then runs exactly the code of `compute_pi_grm()`. Scoring agrees as well, both here and in `catR`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(4, 3, 2, 1, 0)\nc(compute_eap_ggrm = compute_eap_ggrm(bank, x),\n  compute_eap_grm  = compute_eap_grm(bank_as_grm, x),\n  catR_MGRM        = catR::eapEst(bank, x, model = \"MGRM\"),\n  catR_GRM         = catR::eapEst(bank_as_grm, x, model = \"GRM\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncompute_eap_ggrm  compute_eap_grm        catR_MGRM         catR_GRM \n      -0.2280354       -0.2280354       -0.2280354       -0.2280354 \n```\n\n\n:::\n:::\n\n\nThe conversion only runs one way. A GRM bank can be written as an MGRM bank only if the gaps between consecutive thresholds are the same for every item of a block, $\\beta_{j,k+1} - \\beta_{jk} = c_k - c_{k+1}$ for every item $j$ of the block. The bank from the examples of `cat_eap_grm.R` shows the usual situation:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrm_example <- matrix(c(1.227, 0.845, 1.694, 1.012, 2.103,\n                        -2.183, -1.542, -1.021, -2.460, -0.812,\n                        -0.874, -0.415, -0.231, -1.105, 0.094,\n                        0.316, 0.783, 0.652, 0.047, 0.881,\n                        1.592, 2.064, 1.438, 1.271, 1.736), nrow = 5,\n                      dimnames = list(1:5, c(\"alphaj\", \"betaj1\", \"betaj2\", \"betaj3\", \"betaj4\")))\nt(apply(grm_example[, 2:5], 1, diff))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  betaj2 betaj3 betaj4\n1  1.309  1.190  1.276\n2  1.127  1.198  1.281\n3  0.790  0.883  0.786\n4  1.355  1.152  1.224\n5  0.906  0.787  0.855\n```\n\n\n:::\n:::\n\n\nEvery item has its own gaps, so no choice of $b_j$ and shared $c_k$ can reproduce these thresholds. The MGRM spends 13 item parameters on a five-item, five-category block where the GRM spends 25, and the price is exactly this assumption: the rating scale is used with the same spacing on every item.\n\n### What the restriction does not buy: a sufficient raw score\n\nUnder the rating scale model the raw score is a sufficient statistic, so patterns with the same total get the same estimate. The MGRM shares the rating scale model's idea of a common set of step parameters, but not that property. Five patterns that all sum to 10, scored with the bank as given and with a copy in which every discrimination is set to the same value:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsame_total <- list(c(2, 2, 2, 2, 2), c(4, 3, 2, 1, 0), c(0, 1, 2, 3, 4),\n                   c(4, 4, 2, 0, 0), c(0, 0, 2, 4, 4))\n\nbank_equal_alpha <- bank\nbank_equal_alpha[, \"alphaj\"] <- 1.227\n\nsufficiency <- data.frame(\n  pattern     = sapply(same_total, paste, collapse = \" \"),\n  raw_score   = sapply(same_total, sum),\n  theta_EAP   = sapply(same_total, function(x) compute_eap_ggrm(bank, x)),\n  theta_EAP_equal_alpha = sapply(same_total, function(x) compute_eap_ggrm(bank_equal_alpha, x)))\nsufficiency\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    pattern raw_score   theta_EAP theta_EAP_equal_alpha\n1 2 2 2 2 2        10  0.05112909           -0.09334225\n2 4 3 2 1 0        10 -0.22803539            0.03429957\n3 0 1 2 3 4        10  0.47500791           -0.02287911\n4 4 4 2 0 0        10 -0.20461383            0.14801315\n5 0 0 2 4 4        10  0.64529845            0.11013245\n```\n\n\n:::\n:::\n\n\nWith the discriminations as given the five estimates range from -0.228 to 0.645: which items the high responses fall on matters, through both their discriminations and their locations. Making the discriminations equal narrows the range to -0.093 to 0.148 but does not close it. The reason is the cumulative form: a category probability is a difference of two logistic curves, not an exponential of a linear function of $\\theta$, so the likelihood does not depend on the pattern only through its total, whatever the discriminations are.\n\n---\n\n## Worked example: shared category parameters and the information curves\n\nThe theory section showed that, within a block, an item's information depends on $\\theta$ only through $\\theta - b_j$ and on $\\alpha_j$. The copy of the bank with equal discriminations isolates the first part. If the claim holds, each item's curve is item 1's curve shifted by $b_j - b_1$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninfo_item <- function(b, j, th) sapply(th, function(t) compute_ii_ggrm(t, b[j, , drop = FALSE])$Ii)\n\nshift_check <- sapply(2:5, function(j)\n  max(abs(info_item(bank_equal_alpha, j, info_grid) -\n          info_item(bank_equal_alpha, 1, info_grid - (bj[j] - bj[1])))))\nnames(shift_check) <- paste(\"item\", 2:5)\nshift_check\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      item 2       item 3       item 4       item 5 \n2.220446e-16 2.775558e-16 2.498002e-16 2.775558e-16 \n```\n\n\n:::\n:::\n\n\nTo rounding error they are. The peaks and heights make the same point:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npeak_summary <- function(b) {\n  I <- t(sapply(info_grid, function(th) compute_ii_ggrm(th, b)$Ii))\n  data.frame(alphaj = b[, \"alphaj\"], bj = b[, \"bj\"],\n             peak   = info_grid[apply(I, 2, which.max)],\n             max_information = apply(I, 2, max),\n             local_maxima = apply(I, 2, function(y) sum(diff(sign(diff(y))) == -2)))\n}\n\npeaks_equal <- peak_summary(bank_equal_alpha)\npeaks_equal$offset <- peaks_equal$peak - peaks_equal$bj\npeaks_equal\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  alphaj     bj  peak max_information local_maxima offset\n1  1.227 -0.482 -0.78       0.4699391            1 -0.298\n2  1.227  0.137 -0.16       0.4699391            1 -0.297\n3  1.227  0.715  0.42       0.4699391            1 -0.295\n4  1.227 -0.936 -1.23       0.4699391            1 -0.294\n5  1.227  0.298  0.00       0.4699391            1 -0.298\n```\n\n\n:::\n:::\n\n\nWith equal discriminations every item reaches the same maximum information, at the same offset of about -0.3 from its own $b_j$ (the offset is not zero because the category parameters are not symmetric around zero, and it is only resolved to the 0.01 spacing of the grid). The bank then has no strong and weak items, only items aimed at different parts of the scale — and MFI selection among them depends only on where $\\theta$ sits relative to the $b_j$. On this grid it is exactly a nearest-neighbour rule on $b_j$ plus the offset:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmfi_equal <- sapply(info_grid, function(th) compute_next_item_ggrm(th, bank_equal_alpha)$item)\nnearest   <- sapply(info_grid, function(th) which.min(abs(th - mean(peaks_equal$offset) - bj)))\nc(agreements = sum(mfi_equal == nearest), grid_points = length(info_grid))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n agreements grid_points \n        801         801 \n```\n\n\n:::\n:::\n\n\nWith the discriminations as given, the picture changes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npeaks_given <- peak_summary(bank)\npeaks_given$offset <- peaks_given$peak - peaks_given$bj\npeaks_given$max_over_alpha2 <- peaks_given$max_information / peaks_given$alphaj^2\npeaks_given\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  alphaj     bj  peak max_information local_maxima offset max_over_alpha2\n1  1.227 -0.482 -0.78       0.4699391            1 -0.298       0.3121421\n2  0.845  0.137  0.04       0.2278741            1 -0.097       0.3191402\n3  1.694  0.715  0.37       0.8578726            2 -0.345       0.2989482\n4  1.012 -0.936 -1.16       0.3243571            1 -0.224       0.3167104\n5  2.103  0.298 -0.19       1.2653538            4 -0.488       0.2861103\n```\n\n\n:::\n:::\n\n\n- The maximum information now ranges from 0.228 (item 2, $\\alpha_j =$ 0.845) to 1.265 (item 5, $\\alpha_j =$ 2.103). Divided by $\\alpha_j^2$ the heights fall in the narrow band 0.286 to 0.319: the height grows roughly, not exactly, with $\\alpha_j^2$.\n- The offset of the peak from $b_j$ is no longer constant: -0.3, -0.1, -0.34, -0.22, -0.49. The discrimination changes the shape of the curve, not just its height.\n- The steepest items have more than one local maximum: item 5, with the largest $\\alpha_j$, has 4, one per threshold. A large $\\alpha_j$ makes each logistic step narrow compared with the gaps between thresholds, and the information separates into one bump per threshold.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninfo_long <- function(b, label) {\n  I <- t(sapply(info_grid, function(th) compute_ii_ggrm(th, b)$Ii))\n  d <- data.frame(theta = info_grid, I)\n  names(d)[-1] <- paste0(\"item \", 1:5, \" (b=\", bj, \")\")\n  out <- reshape2::melt(d, id.vars = \"theta\", variable.name = \"item\", value.name = \"information\")\n  out$discriminations <- label\n  out\n}\n\ninfo_both <- rbind(info_long(bank_equal_alpha, \"all equal (α = 1.227)\"),\n                   info_long(bank,             \"as given\"))\n\nggplot(info_both, aes(x = theta, y = information, color = item)) +\n  geom_line(linewidth = 0.9) +\n  facet_wrap(~ discriminations, ncol = 1, scales = \"free_y\") +\n  labs(title = \"Item information curves under shared category parameters\",\n       subtitle = \"equal discriminations give shifted copies; unequal ones change height and shape\",\n       x = expression(theta), y = \"information\", color = NULL) +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_ggrm_files/figure-html/info_shape_plot-1.png){width=60%}\n:::\n:::\n\n\n---\n\n## Worked example: identifiability and the ordering of the category parameters\n\n### Adding a constant changes nothing\n\nAdding the same constant to every $b_j$ and every $c_k$ ($t = 0.75$ below), or moving to `mirt`'s convention of $b_1 = 0$ ($t = -b_1$), leaves every threshold, and therefore every probability, where it was:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbank_shifted <- bank\nbank_shifted[, 2:6] <- bank[, 2:6] + 0.75\n\nbank_mirt_convention <- bank\nbank_mirt_convention[, 2:6] <- bank[, 2:6] - bank[1, \"bj\"]\nbank_mirt_convention\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  alphaj     bj    c1    c2   c3     c4\n1  1.227  0.000 2.294 1.085 0.03 -1.481\n2  0.845  0.619 2.294 1.085 0.03 -1.481\n3  1.694  1.197 2.294 1.085 0.03 -1.481\n4  1.012 -0.454 2.294 1.085 0.03 -1.481\n5  2.103  0.780 2.294 1.085 0.03 -1.481\n```\n\n\n:::\n\n```{.r .cell-code}\nmax_pi_difference <- function(b1, b2) max(sapply(seq(-4, 4, by = 0.25), function(th) {\n  p1 <- compute_pi_ggrm(th, b1)\n  p2 <- compute_pi_ggrm(th, b2)\n  max(sapply(names(p1), function(k) max(abs(p1[[k]] - p2[[k]]))))\n}))\n\nc(shifted_by_0.75 = max_pi_difference(bank, bank_shifted),\n  mirt_convention = max_pi_difference(bank, bank_mirt_convention))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nshifted_by_0.75 mirt_convention \n   7.771561e-16    4.718448e-16 \n```\n\n\n:::\n\n```{.r .cell-code}\nx <- c(4, 3, 2, 1, 0)\nsprintf(\"%.12f\", c(Muraki  = compute_eap_ggrm(bank, x),\n                   shifted = compute_eap_ggrm(bank_shifted, x),\n                   mirt    = compute_eap_ggrm(bank_mirt_convention, x)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"-0.228035393373\" \"-0.228035393373\" \"-0.228035393373\"\n```\n\n\n:::\n:::\n\n\nThe differences are floating-point rounding in $b_j - c_k$, never more than 7.8e-16 across all four matrices, and the EAP estimates agree to twelve decimals. The practical consequence: parameters from two calibrations can look very different and still describe the same items. Before comparing $b_j$ or $c_k$ across sources, put them on the same convention — for example centre the $c_k$ of each block at zero, as this bank already is.\n\n### The category parameters must be strictly decreasing\n\nNeither `compute_pi_ggrm()` nor `catR::Pi()` checks the order of the category parameters. Two equal category parameters make two cumulative curves coincide, and the category between them gets probability zero:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbank_tied <- bank\nbank_tied[, \"c2\"] <- bank[, \"c3\"]   # c2 = c3\nround(compute_pi_ggrm(theta = 0, bank_tied)$Pi, 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          cat0     cat1 cat2     cat3     cat4\nItem1 0.056533 0.434266    0 0.369430 0.139772\nItem2 0.195388 0.426532    0 0.233097 0.144984\nItem3 0.134899 0.743451    0 0.111053 0.010597\nItem4 0.058361 0.321578    0 0.358781 0.261280\nItem5 0.039775 0.789040    0 0.162649 0.008536\n```\n\n\n:::\n\n```{.r .cell-code}\nc(mine = compute_eap_ggrm(bank_tied, c(2, 2, 2, 2, 2)),\n  catR = catR::eapEst(bank_tied, c(2, 2, 2, 2, 2), model = \"MGRM\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmine catR \n NaN  NaN \n```\n\n\n:::\n:::\n\n\nCategory 2 is impossible for every item, so a pattern that uses it has likelihood zero everywhere; both integrals are zero and the EAP is `0/0`, which is `NaN` in both implementations. An increasing pair is worse, because nothing fails visibly:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbank_crossed <- bank\nbank_crossed[, c(\"c2\", \"c3\")] <- bank[, c(\"c3\", \"c2\")]   # c2 < c3\nP_crossed <- compute_pi_ggrm(theta = 0, bank_crossed)$Pi\nround(P_crossed, 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          cat0     cat1      cat2     cat3     cat4\nItem1 0.056533 0.434266 -0.281853 0.651283 0.139772\nItem2 0.195388 0.426532 -0.219110 0.452206 0.144984\nItem3 0.134899 0.743451 -0.331060 0.442113 0.010597\nItem4 0.058361 0.321578 -0.205929 0.564709 0.261280\nItem5 0.039775 0.789040 -0.483888 0.646537 0.008536\n```\n\n\n:::\n\n```{.r .cell-code}\nrowSums(P_crossed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nItem1 Item2 Item3 Item4 Item5 \n    1     1     1     1     1 \n```\n\n\n:::\n:::\n\n\nThe cumulative curves cross, category 2 gets a negative \"probability\", and the rows still sum to 1 because the differences telescope, so a check of the row sums would not catch it. The order has to be checked when the bank is built:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_order <- function(b) all(apply(b[, -(1:2), drop = FALSE], 1,\n                                     function(ck) all(diff(ck[!is.na(ck)]) < 0)))\nc(bank = check_order(bank), two_blocks = check_order(bank_two_blocks),\n  tied = check_order(bank_tied), crossed = check_order(bank_crossed))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      bank two_blocks       tied    crossed \n      TRUE       TRUE      FALSE      FALSE \n```\n\n\n:::\n:::\n\n\n---\n\n## Worked example: converting a `mirt` graded rating scale fit\n\nThe documentation of `compute_pi_ggrm()` gives a recipe for turning a `mirt` model fitted with `itemtype = \"grsm\"` into a bank. `mirt` writes the cumulative curve as\n\n$$P^*_{jk} = \\Psi\\big(a_{j}(\\theta + c_j + b_k)\\big)$$\n\n— note that the letters swap roles: `mirt`'s item parameter is `c` and its category parameters are `b1` to `bm`. Matching that with $\\Psi\\big(D\\alpha_j(\\theta - b_j + c_k)\\big)$ at $D = 1$ gives the conversion, with `mirt`'s parameters on the right-hand sides:\n\n$$\\alpha_j = a_j, \\qquad b_j = -c_j, \\qquad c_k = b_k \\qquad (D = 1).$$\n\nTo check the recipe, 1000 examinees are simulated from the bank, the model is fitted with `mirt`, and the converted bank is compared with `mirt`'s own trace lines.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nn_examinees <- 1000\ntheta_sim <- rnorm(n_examinees)\nresponses_sim <- t(sapply(theta_sim, function(th) {\n  p <- compute_pi_ggrm(th, bank)$Pi\n  apply(p, 1, function(pr) sample(0:4, size = 1, prob = pr))\n}))\ncolnames(responses_sim) <- paste0(\"item\", 1:5)\n\nfit <- mirt::mirt(as.data.frame(responses_sim), 1, itemtype = \"grsm\", verbose = FALSE)\npars <- mirt::coef(fit, simplify = TRUE)$items\nround(pars, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         a1    b1    b2     b3     b4      c\nitem1 1.190 2.086 0.947 -0.053 -1.508  0.000\nitem2 0.925 2.086 0.947 -0.053 -1.508 -0.403\nitem3 1.737 2.086 0.947 -0.053 -1.508 -1.059\nitem4 1.075 2.086 0.947 -0.053 -1.508  0.605\nitem5 2.249 2.086 0.947 -0.053 -1.508 -0.681\n```\n\n\n:::\n\n```{.r .cell-code}\nmirt::coef(fit, simplify = TRUE)[c(\"means\", \"cov\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$means\nF1 \n 0 \n\n$cov\n   F1\nF1  1\n```\n\n\n:::\n:::\n\n\n`mirt` has fixed $c_j = 0$ for the first item — its identifiability convention — and in this fit the latent distribution has mean 0 and variance 1, the same standard normal the EAP functions use as their default prior. The conversion:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbank_mirt <- cbind(pars[, \"a1\"], -pars[, \"c\"], pars[, grep(\"^b[0-9]\", colnames(pars))])\ncolnames(bank_mirt) <- colnames(bank)\nround(bank_mirt, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      alphaj     bj    c1    c2     c3     c4\nitem1  1.190  0.000 2.086 0.947 -0.053 -1.508\nitem2  0.925  0.403 2.086 0.947 -0.053 -1.508\nitem3  1.737  1.059 2.086 0.947 -0.053 -1.508\nitem4  1.075 -0.605 2.086 0.947 -0.053 -1.508\nitem5  2.249  0.681 2.086 0.947 -0.053 -1.508\n```\n\n\n:::\n\n```{.r .cell-code}\ntrace_grid <- seq(-4, 4, by = 0.1)\ntrace_difference <- sapply(1:5, function(j) {\n  mirt_trace <- mirt::probtrace(mirt::extract.item(fit, j), matrix(trace_grid))\n  mine <- t(sapply(trace_grid, function(th) compute_pi_ggrm(th, bank_mirt[j, , drop = FALSE])$Pi[1, ]))\n  max(abs(mirt_trace - mine))\n})\nnames(trace_difference) <- paste(\"item\", 1:5)\ntrace_difference\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      item 1       item 2       item 3       item 4       item 5 \n3.330669e-16 2.220446e-16 2.220446e-16 2.220446e-16 2.220446e-16 \n```\n\n\n:::\n:::\n\n\nThe converted bank reproduces `mirt`'s trace lines for every item to within 3.3e-16 over the whole grid, so the recipe is right. The converted bank uses `mirt`'s convention, $b_1 = 0$; re-centring its category parameters at zero, as in the generating bank (the shift by $t = -\\bar c$ from the theory section, $b_j - \\bar c$ and $c_k - \\bar c$), makes the estimates directly comparable with the values they were simulated from:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbank_mirt_centred <- bank_mirt\nbank_mirt_centred[, 2:6] <- bank_mirt[, 2:6] - mean(bank_mirt[1, 3:6])\n\nrecovery <- data.frame(alphaj_true = bank[, \"alphaj\"], alphaj_mirt = bank_mirt_centred[, \"alphaj\"],\n                       bj_true     = bank[, \"bj\"],     bj_mirt     = bank_mirt_centred[, \"bj\"])\nround(recovery, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  alphaj_true alphaj_mirt bj_true bj_mirt\n1       1.227       1.190  -0.482  -0.368\n2       0.845       0.925   0.137   0.035\n3       1.694       1.737   0.715   0.691\n4       1.012       1.075  -0.936  -0.973\n5       2.103       2.249   0.298   0.313\n```\n\n\n:::\n\n```{.r .cell-code}\nround(rbind(true = bank[1, 3:6], mirt = bank_mirt_centred[1, 3:6]), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        c1    c2     c3     c4\ntrue 1.812 0.603 -0.452 -1.963\nmirt 1.718 0.579 -0.421 -1.876\n```\n\n\n:::\n\n```{.r .cell-code}\nc(max_difference = max(abs(bank_mirt_centred - bank)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmax_difference \n     0.1457183 \n```\n\n\n:::\n:::\n\n\nOn a common convention the estimates are close to the generating values, the largest difference being 0.146 — the sampling error of a calibration on 1000 simulated examinees. Without the re-centring the locations would appear to disagree by the arbitrary constant that the two conventions differ by.\n\n---\n\n## Worked example: a short adaptive test\n\nEverything above assembles into an adaptive loop. At each step, pick the most informative unadministered item at the current estimate, collect a response, rescore, repeat.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\ntrue_theta <- 1.0\n\n# simulate a response to item j from an examinee at true_theta\nsimulate_response <- function(j, theta) {\n  p <- compute_pi_ggrm(theta, bank[j, , drop = FALSE])$Pi[1, ]\n  p <- p[!is.na(p)]\n  sample(0:(length(p) - 1), size = 1, prob = p)\n}\n\ntheta <- 0\nadministered <- integer(0)\nresponses <- integer(0)\ntrace <- data.frame()\n\nfor (step in 1:5) {\n  sel <- compute_next_item_ggrm(theta, bank, out = administered)\n  administered <- c(administered, sel$item)\n  responses <- c(responses, simulate_response(sel$item, true_theta))\n\n  sub_bank <- bank[administered, , drop = FALSE]\n  theta <- compute_eap_ggrm(sub_bank, responses)\n  se <- compute_eap_se_ggrm(theta, sub_bank, responses)\n\n  trace <- rbind(trace, data.frame(step = step, item = sel$item,\n                                   alphaj = bank[sel$item, \"alphaj\"],\n                                   bj = bank[sel$item, \"bj\"],\n                                   information = sel$info,\n                                   response = tail(responses, 1),\n                                   theta_EAP = theta, SE = se))\n}\ntrace\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  step item alphaj     bj information response theta_EAP        SE\n1    1    5  2.103  0.298   1.2588474        3 0.8101377 0.6945743\n2    2    3  1.694  0.715   0.8529470        2 0.7625553 0.5622521\n3    3    1  1.227 -0.482   0.4454313        4 1.0046814 0.5311685\n4    4    4  1.012 -0.936   0.2880002        2 0.8103683 0.5148317\n5    5    2  0.845  0.137   0.2251844        3 0.8512289 0.4938620\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(trace, aes(x = step, y = theta_EAP)) +\n  geom_hline(yintercept = true_theta, linetype = \"dashed\", color = \"grey40\") +\n  geom_ribbon(aes(ymin = theta_EAP - SE, ymax = theta_EAP + SE),\n              alpha = 0.2, fill = \"steelblue\") +\n  geom_line(color = \"steelblue\", linewidth = 1) +\n  geom_point(size = 2, color = \"steelblue\") +\n  annotate(\"text\", x = 1, y = true_theta + 0.08, hjust = 0,\n           label = \"true theta\", color = \"grey40\", size = 3.5) +\n  scale_x_continuous(breaks = trace$step) +\n  labs(title = \"Adaptive test: EAP estimate (± 1 SE) after each item\",\n       x = \"item administered\", y = expression(hat(theta)[EAP])) +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_ggrm_files/figure-html/adaptive_plot-1.png){width=60%}\n:::\n:::\n\n\nThe loop opens with item 5, the most discriminating item in the bank, and then takes the items in the order 5, 3, 1, 4, 2, which is also the order of decreasing discrimination (2.103, 1.694, 1.227, 1.012, 0.845). The standard error falls at every step, from 0.695 after one item to 0.494 after five, and the final estimate is 0.851 for a true ability of 1. Unlike a rating scale bank, where every item is equally good and only the targeting differs, the discrimination dominates the choice here.\n\n### Exposure control\n\nPure MFI is deterministic: every examinee starting at $\\theta = 0$ receives the same first item. Across the whole ability range the steepest item is chosen most of the time:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmfi_given <- sapply(info_grid, function(th) compute_next_item_ggrm(th, bank)$item)\nround(table(mfi_given) / length(mfi_given), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmfi_given\n    1     3     4     5 \n0.114 0.135 0.065 0.687 \n```\n\n\n:::\n:::\n\n\nItem 5 is the MFI choice at 68.7% of the grid points between $-4$ and $4$, and item 2 is never the first choice anywhere on the grid. The `randomesque` argument draws at random from the $k$ best instead:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\ntable(replicate(2000, compute_next_item_ggrm(theta = 0, bank, randomesque = 1)$item))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   5 \n2000 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(replicate(2000, compute_next_item_ggrm(theta = 0, bank, randomesque = 3)$item))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  1   3   5 \n679 664 657 \n```\n\n\n:::\n:::\n\n\nWith `randomesque = 1` the same item is chosen 2000 times out of 2000; with `randomesque = 3` the load is spread over three items. Because the items here differ in how informative they can be, the cost is much larger than in a bank with equal discriminations:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrandomesque_cost <- function(b) {\n  info_at_0 <- compute_ii_ggrm(theta = 0, b)$Ii\n  top3 <- sort(info_at_0, decreasing = TRUE)[1:3]\n  c(best_item = max(info_at_0), mean_of_top_3 = mean(top3),\n    proportion_of_best = mean(top3) / max(info_at_0))\n}\nrbind(as_given = randomesque_cost(bank), equal_alpha = randomesque_cost(bank_equal_alpha))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            best_item mean_of_top_3 proportion_of_best\nas_given    1.2588474     0.8573352          0.6810477\nequal_alpha 0.4699391     0.4690481          0.9981041\n```\n\n\n:::\n:::\n\n\nDrawing from the top three keeps 68% of the information of the best item with the discriminations as given, against 100% when they are equal. That is the usual trade-off between measurement efficiency and item security, and in an MGRM bank with a wide spread of discriminations it is a real trade.\n\n---\n\n## Worked example: the numerical settings\n\nThe EAP integrals are approximations, and four arguments control them. None of these is a free choice to make casually.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(4, 4, 4, 4, 4)   # the hardest case for numerical integration\n\nsettings <- rbind(\n  data.frame(setting = \"quadrature points\", value = c(11, 33, 101, 501),\n             theta = sapply(c(11, 33, 101, 501),\n                            function(n) compute_eap_ggrm(bank, x, nqp = n))),\n  data.frame(setting = \"integration bound\", value = c(3, 4, 6),\n             theta = sapply(c(3, 4, 6),\n                            function(b) compute_eap_ggrm(bank, x, lower = -b, upper = b))),\n  data.frame(setting = \"prior SD\", value = c(1, 2),\n             theta = sapply(c(1, 2),\n                            function(s) compute_eap_ggrm(bank, x, priorPar = c(0, s)))),\n  data.frame(setting = \"metric constant D\", value = c(1, 1.702),\n             theta = sapply(c(1, 1.702),\n                            function(d) compute_eap_ggrm(bank, x, D = d)))\n)\nsettings\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             setting   value    theta\n1  quadrature points  11.000 2.530149\n2  quadrature points  33.000 2.538022\n3  quadrature points 101.000 2.538743\n4  quadrature points 501.000 2.538822\n5  integration bound   3.000 2.334881\n6  integration bound   4.000 2.538022\n7  integration bound   6.000 2.554846\n8           prior SD   1.000 2.538022\n9           prior SD   2.000 3.196944\n10 metric constant D   1.000 2.538022\n11 metric constant D   1.702 2.763385\n```\n\n\n:::\n:::\n\n\n\n\nThree different kinds of effect are visible here, and they should not be confused with one another:\n\n- **Quadrature points** are pure approximation error. Moving from 11 to 33 points changes the estimate by 0.0079, from 33 to 101 by 0.00072, and from 101 to 501 by 7.9e-05. The default of 33 is a reasonable accuracy/speed compromise and matches `catR`.\n- **Integration bounds** are also approximation error, but of a more dangerous kind. Truncating at $\\pm 3$ moves the estimate by 0.203, because for an all-highest pattern the posterior still has real mass beyond $\\theta = 3$ and cutting it off silently biases the estimate downward. Widening from $\\pm 4$ to $\\pm 6$ moves it by 0.017. Bounds must be wide enough for the *most extreme pattern the bank can produce*, not for a typical one.\n- **The prior SD and the metric constant are not approximation error at all** — they are different models. Doubling the prior SD to 2 weakens the shrinkage and moves the estimate from 2.54 to 3.2; setting $D = 1.702$ multiplies every discrimination by 1.702 and moves it to 2.76. Both belong in the model specification and must match whatever was used to calibrate the item parameters — for a `mirt` calibration, $D = 1$.\n\n---\n\n## Worked example: numerical precision of the category probabilities\n\nA category probability is a difference of two cumulative probabilities. Far above an item's thresholds both are close to 1, and their difference loses precision. The documentation of `compute_pi_ggrm()` warns about this, and it is easy to see on the steepest item: category 0 of item 5 is $1 - P^*_{51}$, which can also be computed accurately as the upper tail of the logistic distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheta_far <- c(4, 8, 12, 16, 20)\nbeta_51 <- bank[5, \"bj\"] - bank[5, \"c1\"]\n\nprecision <- data.frame(\n  theta    = theta_far,\n  computed = sapply(theta_far, function(t) compute_pi_ggrm(t, bank[5, , drop = FALSE])$Pi[1, \"cat0\"]),\n  catR     = sapply(theta_far, function(t) catR::Pi(t, bank[5, , drop = FALSE], model = \"MGRM\")$Pi[1, \"cat0\"]),\n  accurate = plogis(bank[5, \"alphaj\"] * (theta_far - beta_51), lower.tail = FALSE))\nprecision$relative_error <- abs(precision$computed - precision$accurate) / precision$accurate\nprecision\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  theta     computed         catR     accurate relative_error\n1     4 9.203275e-06 9.203275e-06 9.203275e-06   4.380915e-13\n2     8 2.044849e-09 2.044849e-09 2.044849e-09   1.646362e-08\n3    12 4.543033e-13 4.543033e-13 4.543348e-13   6.944019e-05\n4    16 0.000000e+00 0.000000e+00 1.009464e-16   1.000000e+00\n5    20 0.000000e+00 0.000000e+00 2.242878e-20   1.000000e+00\n```\n\n\n:::\n:::\n\n\nAt $\\theta = 4$, the upper integration bound, the relative error is 4.4e-13. It grows as the true probability shrinks towards the size of the rounding error in numbers close to 1: at $\\theta = 12$ it is 6.9e-05, and further out the computed value is 0 at $\\theta = 16$ and 0 at $\\theta = 20$, where the accurate values are 1e-16 and 2.2e-20. `catR` computes these probabilities the same way and returns the same values. The problem only arises for a response far below what $\\theta$ predicts on a steep item, at abilities far outside the default integration range of this bank, so it has no visible effect on any EAP result in this vignette.\n\n---\n\n# Conclusion\n\nAll eight functions used here reproduce their `catR` counterparts: the normal density, the trapezoidal integrator, the MGRM category probabilities with all three derivatives (for items padded with `NA` as well), the item information with both derivatives, MFI item selection with and without excluded items, the likelihood (rebuilt from `catR`'s probabilities, since `catR` does not export one), and the two integrals that define EAP scoring, at both metric constants and for extreme patterns as well as ordinary ones. The only documented differences, both in the handling of exactly tied items in selection, show up only when a tie is built in on purpose.\n\nWritten out, the model's character is easy to see. The MGRM is the graded response model with its thresholds split into an item location and category parameters shared across a block — a restriction, which `compute_pi_ggrm()` makes literal by forming $b_j - c_k$ and then running the GRM code unchanged. Sharing the category parameters makes the information curves of equally discriminating items shifted copies of one another, but because the model keeps the item discrimination, a real bank has strong and weak items, the most discriminating item dominates adaptive selection, and exposure control has a visible cost. The split between locations and category parameters is not identified without a constraint, so parameters from different sources must be put on one convention before they are compared, and the category parameters must be strictly decreasing, which nothing in the code checks. Finally, a `mirt` graded rating scale fit converts into this layout with a three-column recipe that reproduces `mirt`'s trace lines to machine precision.\n\n---\n\n# References\n\n- Bock, R. D., & Mislevy, R. J. (1982). Adaptive EAP estimation of ability in a microcomputer environment. *Applied Psychological Measurement, 6*(4), 431–444.\n- Magis, D., & Barrada, J. R. (2017). Computerized adaptive testing with R: Recent updates of the package catR. *Journal of Statistical Software, Code Snippets, 76*(1), 1–19. https://doi.org/10.18637/jss.v076.c01\n- Magis, D., & Raîche, G. (2012). Random generation of response patterns under computerized adaptive testing with the R package catR. *Journal of Statistical Software, 48*(8), 1–31. https://doi.org/10.18637/jss.v048.i08\n- Muraki, E. (1990). Fitting a polytomous item response model to Likert-type data. *Applied Psychological Measurement, 14*(1), 59–71.\n- Samejima, F. (1969). Estimation of latent ability using a response pattern of graded scores. *Psychometrika Monograph Supplement, 34*(4, Pt. 2), No. 17.\n\n---\n\n*Rendered with R 4.6.1 · validated against catR 3.17*\n\n---\n\n# Comments\n\nQuestions, corrections and suggestions are welcome below (sign in with GitHub to post).\n\n```{=html}\n<div class=\"giscus\"></div>\n<script>\n(function () {\n  var s = document.createElement(\"script\");\n  s.src = \"https://giscus.app/client.js\";\n  s.setAttribute(\"data-repo\", \"sedzinfo/rwf\");\n  s.setAttribute(\"data-repo-id\", \"REPLACE_WITH_REPO_ID\");\n  s.setAttribute(\"data-category\", \"Comments\");\n  s.setAttribute(\"data-category-id\", \"REPLACE_WITH_CATEGORY_ID\");\n  s.setAttribute(\"data-mapping\", \"specific\");\n  s.setAttribute(\"data-term\", \"EAP MGRM Ability Estimation in base R\");\n  s.setAttribute(\"data-strict\", \"1\");\n  s.setAttribute(\"data-reactions-enabled\", \"1\");\n  s.setAttribute(\"data-emit-metadata\", \"0\");\n  s.setAttribute(\"data-input-position\", \"top\");\n  s.setAttribute(\"data-theme\", \"light\");\n  s.setAttribute(\"data-lang\", \"en\");\n  s.setAttribute(\"data-loading\", \"lazy\");\n  s.crossOrigin = \"anonymous\";\n  s.async = true;\n  document.querySelector(\".giscus\").appendChild(s);\n})();\n</script>\n```\n",
    "supporting": [
      "eap_ggrm_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}