{
  "hash": "1c4d2f5daf4f694a2f82aa25653d6402",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"EAP PCM Ability Estimation in base R\"\ndescription: \"Masters' Partial Credit Model: ordered categories with item-specific step parameters.\"\n---\n\n\n\n# Background\n\n## Acknowledgement\n\nThe functions in [`cat_eap_common.R`](https://github.com/sedzinfo/rwf/blob/main/working_examples/cat_eap_common.R) and [`cat_eap_pcm.R`](https://github.com/sedzinfo/rwf/blob/main/working_examples/cat_eap_pcm.R) are adapted from the source code of the **catR** package by David Magis, Gilles Raîche and Juan Ramón Barrada (Magis & Raîche, 2012; Magis & Barrada, 2017). The model parameterisations, the formulas for the response probabilities and their derivatives, the item information, maximum-information item selection and the trapezoidal EAP integration all follow catR's `Pi()`, `Ii()`, `nextItem()`, `eapEst()`, `eapSem()` and `integrate.catR()`, and much of the code keeps catR's structure line for line. The purpose of the rewrite is teaching, not replacement: every step is written out in plain base R so that it can be read, and catR remains the reference implementation that every function is checked against below. catR is free software distributed under the GNU General Public License (version 3 or later).\n\n## Description\n\nThe **Partial Credit Model (PCM)** of Masters (1982) is a Rasch model for items scored in ordered categories $0, 1, \\ldots, m_j$, where each item has its **own** set of step parameters. It was designed for tasks that award partial credit — a multi-step problem scored by the number of steps completed, a rubric-scored essay — and it is equally usable for rating-scale items whose response options cannot be assumed to work the same way on every item. That last point is what separates it from the Rating Scale Model (RSM), in which every item shares one set of category thresholds. The PCM keeps the Rasch-family properties of the RSM — no discrimination parameter, and a raw score that is a sufficient statistic for ability — while letting each item have its own category curves and its own information curve.\n\n[`working_examples/cat_eap_pcm.R`](https://github.com/sedzinfo/rwf/blob/main/working_examples/cat_eap_pcm.R) implements the EAP pipeline for the PCM in six functions, which call the two general helpers in [`working_examples/cat_eap_common.R`](https://github.com/sedzinfo/rwf/blob/main/working_examples/cat_eap_common.R). Everything is plain base R, with no runtime dependency on `catR`:\n\n| Function | File | Purpose | `catR` equivalent it mirrors |\n|---|---|---|---|\n| `density_function()` | `cat_eap_common.R` | Normal density | `stats::dnorm()` |\n| `integrate_cat()` | `cat_eap_common.R` | Numerical integration (trapezoidal rule) | `catR::integrate.catR()` |\n| `compute_pi_pcm()` | `cat_eap_pcm.R` | Category response probabilities and their first three derivatives | `catR::Pi(model=\"PCM\")` |\n| `compute_ii_pcm()` | `cat_eap_pcm.R` | Item information and its first two derivatives | `catR::Ii(model=\"PCM\")` |\n| `compute_next_item_pcm()` | `cat_eap_pcm.R` | Maximum Fisher information item selection, with optional randomesque exposure control | `catR::nextItem(model=\"PCM\", criterion=\"MFI\")` |\n| `compute_likelihood_pcm()` | `cat_eap_pcm.R` | Likelihood of a polytomous response pattern | *(internal to `catR::eapEst()`)* |\n| `compute_eap_pcm()` | `cat_eap_pcm.R` | EAP ability estimate | `catR::eapEst(model=\"PCM\")` |\n| `compute_eap_se_pcm()` | `cat_eap_pcm.R` | EAP standard error | `catR::eapSem(model=\"PCM\")` |\n\n`cat_eap_common.R` is sourced first because the PCM functions call `density_function()` and `integrate_cat()`. `cat_eap_rsm.R` is only needed for the comparison with the Rating Scale Model further down.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(catR)\nsource(\"R/cat_eap_common.R\", local = knitr::knit_global())\nsource(\"R/cat_eap_pcm.R\", local = knitr::knit_global())\nsource(\"R/cat_eap_rsm.R\", local = knitr::knit_global())\n```\n:::\n\n\n---\n\n## Theoretical Background\n\n### From steps to categories\n\nA polytomous item scored $0,1,\\ldots,m_j$ needs $m_j+1$ category response curves that sum to 1 at every ability level. The PCM builds them from $m_j$ **steps**: to reach category $k$ a respondent has to complete steps $1$ to $k$, and step $t$ of item $j$ has its own difficulty $\\delta_{jt}$.\n\n$$P_{jk}(\\theta) = P(X_j = k \\mid \\theta) = \\frac{\\exp\\left[\\sum_{t=1}^{k} D(\\theta - \\delta_{jt})\\right]}{\\sum_{h=0}^{m_j}\\exp\\left[\\sum_{t=1}^{h} D(\\theta - \\delta_{jt})\\right]}, \\qquad k = 0, 1, \\ldots, m_j$$\n\nwith the empty sum for $k=0$ taken to be zero.\n\n- $\\delta_{jk}$ — the **step parameter** of step $k$ of item $j$. Every item has its own set, and nothing forces them to increase with $k$.\n- $m_j$ — the number of steps of item $j$, one fewer than its number of categories. Items in the same bank may have different $m_j$.\n- $D$ — the usual metric constant (1, or 1.702 for the normal-ogive metric).\n\nThere is no discrimination parameter: every step of every item has the same slope $D$, which is what makes the PCM a Rasch model.\n\nThe meaning of a step parameter is clearest in the ratio of two adjacent categories, where the common denominator cancels:\n\n$$\\log\\frac{P(X_j = k \\mid \\theta)}{P(X_j = k-1 \\mid \\theta)} = D(\\theta - \\delta_{jk})$$\n\nGiven that the response is either $k-1$ or $k$, the item behaves like a dichotomous Rasch item with difficulty $\\delta_{jk}$. In particular the curves of categories $k-1$ and $k$ **cross at $\\theta = \\delta_{jk}$**, which is checked numerically in the worked example on threshold ordering.\n\nThe **Rating Scale Model** is the special case $\\delta_{jk} = \\lambda_j + \\delta_k$: one location per item plus one set of thresholds shared by the whole bank (Andrich, 1978). A bank of $n$ items with $m$ steps each needs $n \\times m$ step parameters under the PCM but only $n + m - 1$ free parameters under the RSM: $n$ locations and $m$ thresholds, less one, because adding a constant to every $\\lambda_j$ and subtracting it from every $\\delta_k$ leaves every $\\delta_{jk}$ unchanged. Adding an item-specific discrimination $a_j$, that is replacing every $D(\\theta - \\delta_{jt})$ above by $Da_j(\\theta - \\delta_{jt})$, gives the generalised partial credit model, which is not covered here; the PCM is its special case $a_j = 1$.\n\n### The bank layout\n\n`cat_eap_pcm.R` expects one row per item and one column per step:\n\n- columns 1 to $m$ hold $\\delta_{j1},\\ldots,\\delta_{jm}$, where $m$ is the largest number of steps in the bank;\n- there is no location column and no discrimination column, so a bank with $m$ columns describes items with $m+1$ categories: a five-point Likert item scored 0 to 4 needs **four** columns (the RSM layout needs five, because its first column holds $\\lambda_j$);\n- an item with fewer categories is padded with `NA` in its **last** columns. The code builds the cumulative sums $\\sum_{t \\le k}$ one step at a time and drops every category whose sum is `NA`, so an `NA` in the middle of a row does not skip one step — it removes every category above it (shown below). As an exact rule: $m_j$ is the number of entries of row $j$ before its first `NA` ($m$ if there is none), categories $m_j+1,\\ldots,m$ are returned as `NA` in `Pi` and in all three derivatives, and every sum over categories below runs over $0,\\ldots,m_j$ only;\n- responses are scored $0, 1, \\ldots, m_j$;\n- a bank calibrated in `mirt` with `itemtype = \"Rasch\"` maps directly, $\\delta_{jt} = b_{jt}$, where $b_{jt}$ are the columns `b1` to `bm` of `pars$items` with `pars <- mirt::coef(model, IRTpars = TRUE, simplify = TRUE)`; a dichotomous item's single `b` goes in the first column. It is used with $D = 1$ and, because `mirt` estimates the latent variance of a Rasch model, with `priorPar = c(0, sqrt(pars$cov))`.\n\n### Derivatives and the metric constant\n\nWrite $E_j$, $V_j$ and $\\kappa_{3j}$ for the mean, the variance and the third central moment of the item score at $\\theta$, so that $E_j = E(X_j\\mid\\theta)$ and $V_j = \\mathrm{Var}(X_j\\mid\\theta)$:\n\n$$E_j = \\sum_{h=0}^{m_j} h\\,P_{jh}(\\theta)\n\\qquad\nV_j = \\sum_{h=0}^{m_j} (h-E_j)^2\\,P_{jh}(\\theta)\n\\qquad\n\\kappa_{3j} = \\sum_{h=0}^{m_j} (h-E_j)^3\\,P_{jh}(\\theta)$$\n\nDifferentiating the category probability gives the standard Rasch-family result for the first derivative, and differentiating twice more, with $E_j' = DV_j$ and $V_j' = D\\kappa_{3j}$, gives the second and the third:\n\n$$P'_{jk} = D\\,P_{jk}\\,(k-E_j)\n\\qquad\nP''_{jk} = D^2P_{jk}\\big[(k-E_j)^2-V_j\\big]\n\\qquad\nP'''_{jk} = D^3P_{jk}\\big[(k-E_j)^3-3V_j(k-E_j)-\\kappa_{3j}\\big]$$\n\n`compute_pi_pcm()` returns the probabilities `Pi` together with three derivatives `dPi`, `d2Pi` and `d3Pi`. It writes the numerator of category $k$ as $\\gamma_{jk} = \\exp\\big[\\sum_{t\\le k} D(\\theta-\\delta_{jt})\\big]$ and differentiates it as $\\gamma_{jk}\\,k$, exactly as `catR::Pi()` does, where the exact derivative is $\\gamma_{jk}\\,D\\,k$ (the exact line is left commented out in the source). The derivatives it returns, written $\\dot P_{jk}$, $\\ddot P_{jk}$ and $\\dddot P_{jk}$ from here on, are therefore the three above without their powers of $D$:\n\n$$\\dot P_{jk} = \\frac{P'_{jk}}{D} = P_{jk}\\,(k-E_j)\n\\qquad\n\\ddot P_{jk} = \\frac{P''_{jk}}{D^2} = P_{jk}\\big[(k-E_j)^2-V_j\\big]\n\\qquad\n\\dddot P_{jk} = \\frac{P'''_{jk}}{D^3} = P_{jk}\\big[(k-E_j)^3-3V_j(k-E_j)-\\kappa_{3j}\\big]$$\n\nWith $D = 1$ the returned and the exact derivatives coincide. With $D = 1.702$ the probabilities are still exact, but `dPi` is the true slope divided by $D$, and each higher derivative loses one more factor of $D$. The function keeps catR's convention on purpose so that the two return the same numbers. The validation of the probabilities below confirms the factors against finite differences; the subsections on next-item selection and on EAP explain why the convention changes neither item selection nor EAP scoring.\n\n### No probability floor\n\nUnlike `compute_pi_dichotomous()`, `compute_pi_pcm()` applies no probability floor, and neither does the polytomous branch of `catR::Pi()`. None is needed: every category probability is a positive exponential divided by a sum of positive exponentials, and the information below divides each squared slope by its own category probability, never by $1-P_{jk}$, so a probability that rounds to exactly 1 far out in a tail cannot make it infinite. The only guards are the `NA` rule of the bank layout and `na.rm = TRUE` in the category sums of `compute_ii_pcm()`, which skips the `NA` categories of padded items.\n\n### Item information\n\n$$I_j(\\theta) = \\sum_{k=0}^{m_j} \\frac{P'^2_{jk}(\\theta)}{P_{jk}(\\theta)} = D^2\\,V_j$$\n\nThe second equality follows from substituting $P'_{jk}$ above and is specific to the Rasch family: the information of a PCM item is its conditional score variance, scaled by $D^2$. Because `compute_ii_pcm()` builds the sum from catR's derivative,\n\n$$\\texttt{Ii} = \\sum_{k=0}^{m_j} \\frac{\\dot P_{jk}^2}{P_{jk}} = V_j = \\frac{I_j(\\theta)}{D^2},$$\n\nit returns $\\mathrm{Var}(X_j\\mid\\theta)$ itself — the exact information at $D=1$, and the exact information divided by $D^2$ at $D=1.702$. Three consequences, all checked below:\n\n1. With no discrimination parameter, the height and the shape of an information curve depend, for a given $D$, only on the number of steps and their spacing. Adding the same constant to every step of an item only moves its curve.\n2. The variance of a score on $0,\\ldots,m_j$ is at most $m_j^2/4$, so the returned information of an item with $m_j$ steps can never exceed $m_j^2/4$ — 4 for a five-category item.\n3. Items with different spacings have differently shaped curves, so — unlike in the RSM — items in a PCM bank differ in *how much* information they can deliver, not only in *where*.\n\n`compute_ii_pcm()` also returns two derivatives of the information, obtained by differentiating each term $P'^2_{jk}/P_{jk}$ and summing over categories. As in `catR::Ii()`, they are written with the returned derivatives, which makes them the exact derivatives $I'_j$ and $I''_j$ divided by $D^3$ and $D^4$:\n\n$$\\texttt{dIi} = \\sum_{k} \\left[\\frac{2\\dot P_{jk}\\ddot P_{jk}}{P_{jk}} - \\frac{\\dot P_{jk}^3}{P_{jk}^2}\\right] = \\frac{I'_j}{D^3}\n\\qquad\n\\texttt{d2Ii} = \\sum_{k} \\left[\\frac{2\\ddot P_{jk}^2 + 2\\dot P_{jk}\\dddot P_{jk}}{P_{jk}} - \\frac{5\\dot P_{jk}^2\\ddot P_{jk}}{P_{jk}^2} + \\frac{2\\dot P_{jk}^4}{P_{jk}^3}\\right] = \\frac{I''_j}{D^4}$$\n\nSubstituting the closed forms of $\\dot P_{jk}$, $\\ddot P_{jk}$ and $\\dddot P_{jk}$ turns the two sums into the third and the fourth cumulant of the item score, just as `Ii` is the second:\n\n$$\\texttt{dIi} = \\kappa_{3j}\n\\qquad\n\\texttt{d2Ii} = \\kappa_{4j} = \\sum_{h=0}^{m_j} (h-E_j)^4\\,P_{jh}(\\theta) - 3V_j^2$$\n\nAt $D = 1.702$ they are therefore not even the derivatives of the returned `Ii`: its slope is $D$ times `dIi` and its curvature $D^2$ times `d2Ii`. Neither maximum-information selection nor EAP scoring uses `dIi` or `d2Ii`; they are returned because `catR::Ii()` returns them. **Test information** is the sum of the item informations,\n\n$$I(\\theta) = \\sum_{j=1}^{n} I_j(\\theta)$$\n\nand at $D = 1.702$ the sum of the returned `Ii` has to be multiplied by $D^2$ before it is used as a number, for instance in a maximum-likelihood standard error $1/\\sqrt{I(\\theta)}$.\n\n### Next-item selection\n\nAn adaptive test picks, at each step, the unadministered item that is most informative at the current ability estimate — the **Maximum Fisher Information (MFI)** criterion:\n\n$$j^{*} = \\arg\\max_{j\\notin\\texttt{out}} I_j(\\hat\\theta)$$\n\n`compute_next_item_pcm()` evaluates `compute_ii_pcm()` for every item not listed in `out` (the items already administered; it stops with an error when none is left) and returns the index of the best one, its returned information `Ii`, and the indices of the items that were available. Under the RSM every information curve is the same curve shifted by $\\lambda_j$, so MFI is close to a nearest-neighbour lookup on the item locations (not exactly one, because that common curve is not symmetric about its peak; the RSM vignette shows where the two disagree). Under the PCM the curves differ in shape and height, there is not even an approximate shortcut of that kind, and the information of every available item has to be computed at $\\theta$.\n\nThe $D$ convention does not affect selection: at a given $D$ the information of every candidate is divided by the same $D^2$, and dividing all candidates by one positive constant does not change which is largest.\n\nThe `randomesque` argument draws at random from the $k$ most informative available items instead of always taking the single best, which is standard exposure control. Exactly: with $k = \\max\\big(1, \\min(\\lfloor\\texttt{randomesque}\\rfloor,\\ \\text{number of available items})\\big)$, the available items are ranked by decreasing $I_j(\\hat\\theta)$, ties broken by item order as `order()` does, and the next item is drawn uniformly from the first $k$; with $k = 1$ there is no draw and the result is $j^{*}$, the first of any tied maxima. Two edge cases are documented in the source: when several items tie exactly for the maximum, `catR` draws one of them at random whereas `compute_next_item_pcm()` takes the first; and with `randomesque` above 1 `catR` also keeps every item tied with the last one kept, so it can draw from more than $k$ items.\n\n### Likelihood of a response pattern\n\nUnder **local independence**, the likelihood of a response pattern $\\mathbf{x} = (x_1,\\ldots,x_n)$, with each $x_j \\in \\{0,\\ldots,m_j\\}$, is\n\n$$L(\\theta) = \\prod_{j=1}^{n} P_{jx_j}(\\theta)$$\n\n`compute_pi_pcm()` returns one row per item and one column per category, so the response to item $j$ selects column `x[j]+1`; the `+1` is index bookkeeping, because categories start at 0 and R columns start at 1. `catR` computes this product inside `eapEst()` and `eapSem()` without exporting it; `compute_likelihood_pcm()` exposes it as a function of its own, and `compute_eap_pcm()` and `compute_eap_se_pcm()` call it.\n\n### EAP and its standard error\n\nA **prior** $\\pi(\\theta)$ on ability — normal with `priorPar = c(mean, sd)`, standard normal by default — turns the likelihood into a posterior, and EAP (Bock & Mislevy, 1982) reports its mean:\n\n$$\\hat\\theta_{EAP} = E[\\theta \\mid \\mathbf{x}] = \\frac{\\displaystyle\\int \\theta\\,\\pi(\\theta)\\,L(\\theta)\\,d\\theta}{\\displaystyle\\int \\pi(\\theta)\\,L(\\theta)\\,d\\theta}$$\n\nFor a response pattern $\\mathbf{x}=(x_1,\\ldots,x_n)$, the likelihood and the two integrands are\n\n$$\n\\begin{aligned}\nL(s) &= \\prod_{j=1}^{n} P_{jx_j}(s),\\\\\ng(s) &= s\\,\\pi(s)\\,L(s),\\\\\nh(s) &= \\pi(s)\\,L(s).\n\\end{aligned}\n$$\n\nOn the quadrature grid $X=(\\theta_1,\\ldots,\\theta_Q)$, where $Q=\\texttt{nqp}$ and $\\theta_q=\\texttt{lower}+(q-1)(\\texttt{upper}-\\texttt{lower})/(Q-1)$, the estimate is approximated by\n\n$$\n\\hat\\theta_{EAP} \\approx \\frac{\\operatorname{Trap}(X,\\,g(X))}{\\operatorname{Trap}(X,\\,h(X))},\n$$\n\nwhere $g(X)=(g(\\theta_1),\\ldots,g(\\theta_Q))$ and $h(X)=(h(\\theta_1),\\ldots,h(\\theta_Q))$. `Trap` denotes the trapezoidal integration implemented by `integrate_cat()` below. The standard error is the posterior standard deviation,\n\n$$SE(\\hat\\theta_{EAP}) = \\sqrt{\\frac{\\displaystyle\\int (\\theta-\\hat\\theta_{EAP})^2\\,\\pi(\\theta)\\,L(\\theta)\\,d\\theta}{\\displaystyle\\int \\pi(\\theta)\\,L(\\theta)\\,d\\theta}}$$\n\nwhose numerator integrand is the squared distance from the EAP estimate times the posterior weight; the denominator is the same posterior weight used above:\n\n$$\n\\begin{aligned}\ng_{SE}(s) &= (s-\\hat\\theta_{EAP})^2\\,\\pi(s)\\,L(s),\\\\\nh(s) &= \\pi(s)\\,L(s).\n\\end{aligned}\n$$\n\nUsing the same quadrature grid $X$, the numerical estimate is\n\n$$\nSE(\\hat\\theta_{EAP}) \\approx \\sqrt{\\frac{\\operatorname{Trap}(X,\\,g_{SE}(X))}{\\operatorname{Trap}(X,\\,h(X))}}.\n$$\n\nThe defaults are `nqp = 33`, `lower = -4` and `upper = 4`, as in `catR`. Only the probabilities enter the integrals, never their derivatives, so the $D$ convention above has no effect on the estimate or its standard error. Maximum likelihood has no finite estimate for a pattern with every response in the lowest or in the highest category; the prior keeps both integrals finite for every pattern.\n\n`compute_eap_se_pcm()` takes the evaluation point `theta` as a free argument, which takes the place of $\\hat\\theta_{EAP}$ in $g_{SE}$. Passing the EAP estimate returns the posterior standard deviation; any other value returns the posterior root mean squared deviation around that point, which is larger.\n\n### Numerical integration\n\nNeither integral has a closed form, so the integrands are evaluated at the $Q$ **quadrature points** $\\theta_1<\\cdots<\\theta_Q$ of the grid above and integrated with the **trapezoidal rule**, which approximates the area between two adjacent points by a trapezoid, the width times the average of the two heights:\n\n$$\\int f(\\theta)\\,d\\theta \\approx \\operatorname{Trap}(X,\\,f(X)) = \\sum_{q=1}^{Q-1} (\\theta_{q+1}-\\theta_q)\\,\\frac{f(\\theta_q)+f(\\theta_{q+1})}{2}$$\n\n`integrate_cat()` implements exactly this sum. `density_function()` supplies the prior, the normal density\n\n$$\\pi(\\theta) = \\frac{1}{\\sigma\\sqrt{2\\pi}}\\exp\\!\\left(-\\frac{(\\theta-\\mu)^2}{2\\sigma^2}\\right), \\qquad (\\mu,\\sigma) = \\texttt{priorPar}$$\n\n### A Rasch-family consequence: the raw score is sufficient\n\nWriting out the likelihood of a PCM response pattern,\n\n$$L(\\theta) = \\frac{\\exp\\left(D\\,\\theta \\sum_{j} x_j \\;-\\; D \\sum_{j} \\sum_{t=1}^{x_j}\\delta_{jt}\\right)}{\\prod_{j} \\sum_{h=0}^{m_j}\\exp\\left[\\sum_{t=1}^{h} D(\\theta-\\delta_{jt})\\right]}$$\n\nThe denominator depends on $\\theta$ and on the items but not on the responses, and the second term of the numerator depends on the responses but not on $\\theta$. The pattern therefore touches the $\\theta$-dependent part of the likelihood only through the **total score** $\\sum_j x_j$. For two patterns with the same total on the same items, the likelihood ratio is the constant $\\exp\\left[-D(S_1 - S_2)\\right]$, where $S = \\sum_j \\sum_{t \\le x_j} \\delta_{jt}$ is the sum of the step parameters each pattern has passed. The constant cancels from both EAP ratios, so the two patterns get identical estimates and standard errors: the raw score is a **sufficient statistic** for $\\theta$ (Masters, 1982).\n\n---\n\n# Validation\n\n## The item bank\n\nThe bank from the roxygen examples of `cat_eap_pcm.R`: five items, four steps each, so five categories scored 0 to 4.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndeltaj1 <- c(-1.853, -2.214, -0.936, -1.508, -0.412)\ndeltaj2 <- c(-0.627, -0.504, -1.215, -0.183,  0.338)\ndeltaj3 <- c( 0.418,  0.692,  0.284,  0.735,  1.102)\ndeltaj4 <- c( 1.636,  1.927,  1.405,  2.118,  2.285)\n\nbank <- matrix(c(deltaj1, deltaj2, deltaj3, deltaj4), nrow = 5,\n               dimnames = list(1:5, c(\"deltaj1\", \"deltaj2\", \"deltaj3\", \"deltaj4\")))\nbank\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  deltaj1 deltaj2 deltaj3 deltaj4\n1  -1.853  -0.627   0.418   1.636\n2  -2.214  -0.504   0.692   1.927\n3  -0.936  -1.215   0.284   1.405\n4  -1.508  -0.183   0.735   2.118\n5  -0.412   0.338   1.102   2.285\n```\n\n\n:::\n:::\n\n\nUnlike the RSM bank, no column is constant: every item has its own steps. Item 3 has its first two steps reversed ($\\delta_{31}$ = -0.936, $\\delta_{32}$ = -1.215), which the PCM allows; the worked example on threshold ordering shows what that does.\n\n---\n\n## Validating each piece against `catR`\n\n### Normal density\n\n\n::: {.cell}\n\n```{.r .cell-code}\nv <- seq(-3, 3, by = 0.1)\ncomparison <- data.frame(x = v, density_function = density_function(v), dnorm = dnorm(v))\nhead(comparison)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     x density_function       dnorm\n1 -3.0      0.004431848 0.004431848\n2 -2.9      0.005952532 0.005952532\n3 -2.8      0.007915452 0.007915452\n4 -2.7      0.010420935 0.010420935\n5 -2.6      0.013582969 0.013582969\n6 -2.5      0.017528300 0.017528300\n```\n\n\n:::\n\n```{.r .cell-code}\nc(standard_normal = all.equal(comparison$density_function, comparison$dnorm),\n  mean_0.5_sd_2   = all.equal(density_function(v, mean = 0.5, sd = 2), dnorm(v, mean = 0.5, sd = 2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nstandard_normal   mean_0.5_sd_2 \n           TRUE            TRUE \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(comparison, aes(x = x)) +\n  geom_line(aes(y = density_function, color = \"density_function()\"), linewidth = 1) +\n  geom_point(aes(y = dnorm, color = \"dnorm()\"), shape = 1) +\n  labs(title = \"Hand-written normal density vs. dnorm()\",\n       x = expression(theta), y = \"density\", color = NULL) +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_pcm_files/figure-html/density_plot-1.png){width=60%}\n:::\n:::\n\n\nThe function writes out the normal density of the theory section longhand, and it agrees with `dnorm()` for the standard normal and for a prior with mean 0.5 and standard deviation 2. It uses `exp(1)` rather than a hard-coded `2.71828`, which is accurate to only six significant digits and, according to its documentation, shifts the EAP estimate in the seventh decimal.\n\n### Numerical integration\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- seq(from = -3, to = 3, length = 33)\ny <- round(exp(x), 2)\nc(integrate_cat = integrate_cat(x, y), integrate.catR = catR::integrate.catR(x, y))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n integrate_cat integrate.catR \n      20.09437       20.09437 \n```\n\n\n:::\n\n```{.r .cell-code}\nall.equal(integrate_cat(x, y), catR::integrate.catR(x, y))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\nBoth apply the trapezoidal rule to the same 33 points, an approximation of $\\int_{-3}^{3} e^x\\,dx$, and return the same number.\n\n### Category response probabilities and their derivatives\n\nThe probabilities at $\\theta = 0$, then the largest absolute difference from `catR::Pi()` in each returned element, over a range of abilities that includes the far tails and at both values of the metric constant:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(compute_pi_pcm(theta = 0, bank)$Pi, 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          cat0     cat1     cat2     cat3     cat4\nItem1 0.034827 0.222162 0.415884 0.273802 0.053325\nItem2 0.029420 0.269263 0.445719 0.223115 0.032482\nItem3 0.049507 0.126230 0.425433 0.320251 0.078579\nItem4 0.072167 0.326029 0.391500 0.187726 0.022578\nItem5 0.251208 0.379282 0.270502 0.089862 0.009146\n```\n\n\n:::\n\n```{.r .cell-code}\nsettings <- expand.grid(theta = c(-6, -3, -1, 0, 0.7, 2.5, 6), D = c(1, 1.702))\npi_diff <- t(mapply(function(th, d) {\n  a <- compute_pi_pcm(th, bank, D = d)\n  b <- catR::Pi(th, bank, model = \"PCM\", D = d)\n  sapply(c(\"Pi\", \"dPi\", \"d2Pi\", \"d3Pi\"), function(k) max(abs(a[[k]] - b[[k]])))\n}, settings$theta, settings$D))\ncbind(settings, pi_diff)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   theta     D Pi dPi d2Pi d3Pi\n1   -6.0 1.000  0   0    0    0\n2   -3.0 1.000  0   0    0    0\n3   -1.0 1.000  0   0    0    0\n4    0.0 1.000  0   0    0    0\n5    0.7 1.000  0   0    0    0\n6    2.5 1.000  0   0    0    0\n7    6.0 1.000  0   0    0    0\n8   -6.0 1.702  0   0    0    0\n9   -3.0 1.702  0   0    0    0\n10  -1.0 1.702  0   0    0    0\n11   0.0 1.702  0   0    0    0\n12   0.7 1.702  0   0    0    0\n13   2.5 1.702  0   0    0    0\n14   6.0 1.702  0   0    0    0\n```\n\n\n:::\n:::\n\n\nThe largest difference over every element, ability and metric constant is exactly zero: the two functions perform the same arithmetic in the same order.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheta_grid <- seq(-5, 5, by = 0.05)\ndf_curves <- do.call(rbind, lapply(1:5, function(j) {\n  p <- t(sapply(theta_grid, function(th) compute_pi_pcm(th, bank[j, , drop = FALSE])$Pi[1, ]))\n  d <- data.frame(theta = theta_grid, p)\n  names(d)[-1] <- paste0(\"category \", 0:4)\n  out <- reshape2::melt(d, id.vars = \"theta\", variable.name = \"category\", value.name = \"P\")\n  out$item <- paste(\"item\", j)\n  out\n}))\ndf_steps <- data.frame(item = paste(\"item\", rep(1:5, times = 4)), step = as.vector(bank))\n\nggplot(df_curves, aes(x = theta, y = P, color = category)) +\n  geom_vline(data = df_steps, aes(xintercept = step), linetype = \"dashed\", color = \"grey60\") +\n  geom_line(linewidth = 0.9) +\n  facet_wrap(~ item, ncol = 2) +\n  labs(title = \"Category response curves, all five items\",\n       subtitle = \"dashed lines mark the step parameters of each item\",\n       x = expression(theta), y = expression(P(theta)), color = NULL) +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_pcm_files/figure-html/pi_plot-1.png){width=60%}\n:::\n:::\n\n\nEach panel has its own set of curves, and each dashed line — one step parameter — passes through the crossing point of two adjacent category curves. In item 3 the first two dashed lines are in reverse order, and category 1 is squeezed between its neighbours.\n\n`catR` leaves $D$ out of the derivatives in the same way, so the comparison above cannot show the convention. At $\\theta = 0.3$ the returned derivatives are therefore compared with the closed forms $\\dot P_{jk}$, $\\ddot P_{jk}$ and $\\dddot P_{jk}$ of the theory section, and each central finite-difference slope is divided by the derivative returned for it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nth  <- 0.3\neps <- 1e-5\nslope <- function(f) (f(th + eps) - f(th - eps)) / (2 * eps)\n\nderivative_check <- sapply(c(\"D = 1\" = 1, \"D = 1.702\" = 1.702), function(d) {\n  r  <- compute_pi_pcm(th, bank, D = d)\n  C  <- matrix(0:4, 5, 5, byrow = TRUE) - as.vector(r$Pi %*% (0:4))   # k - E_j\n  V  <- rowSums(r$Pi * C^2)                                          # V_j\n  K3 <- rowSums(r$Pi * C^3)                                          # kappa_3j\n  s1 <- slope(function(t) compute_pi_pcm(t, bank, D = d)$Pi)   / r$dPi\n  s2 <- slope(function(t) compute_pi_pcm(t, bank, D = d)$dPi)  / r$d2Pi\n  s3 <- slope(function(t) compute_pi_pcm(t, bank, D = d)$d2Pi) / r$d3Pi\n  c(max_abs_dPi_minus_closed_form  = max(abs(r$dPi  - r$Pi * C)),\n    max_abs_d2Pi_minus_closed_form = max(abs(r$d2Pi - r$Pi * (C^2 - V))),\n    max_abs_d3Pi_minus_closed_form = max(abs(r$d3Pi - r$Pi * (C^3 - 3 * V * C - K3))),\n    slope_Pi_over_dPi_min    = min(s1), slope_Pi_over_dPi_max    = max(s1),\n    slope_dPi_over_d2Pi_min  = min(s2), slope_dPi_over_d2Pi_max  = max(s2),\n    slope_d2Pi_over_d3Pi_min = min(s3), slope_d2Pi_over_d3Pi_max = max(s3))\n})\nround(derivative_check, 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                               D = 1 D = 1.702\nmax_abs_dPi_minus_closed_form      0     0.000\nmax_abs_d2Pi_minus_closed_form     0     0.000\nmax_abs_d3Pi_minus_closed_form     0     0.000\nslope_Pi_over_dPi_min              1     1.702\nslope_Pi_over_dPi_max              1     1.702\nslope_dPi_over_d2Pi_min            1     1.702\nslope_dPi_over_d2Pi_max            1     1.702\nslope_d2Pi_over_d3Pi_min           1     1.702\nslope_d2Pi_over_d3Pi_max           1     1.702\n```\n\n\n:::\n:::\n\n\nAt both values of $D$ the returned derivatives equal the closed forms. At $D = 1$ every ratio is 1, so they are the exact derivatives; at $D = 1.702$ every ratio is 1.702, so `dPi`, `d2Pi` and `d3Pi` are the exact derivatives divided by $D$, $D^2$ and $D^3$.\n\nItems with fewer categories are padded with `NA` at the end of their rows. Making item 2 a three-category item and item 5 a four-category one, and repeating the comparison with `catR` over the same abilities and metric constants, then putting an `NA` in the middle of a row:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbank_na <- bank\nbank_na[2, c(\"deltaj3\", \"deltaj4\")] <- NA   # item 2 is scored 0 to 2\nbank_na[5, \"deltaj4\"] <- NA                 # item 5 is scored 0 to 3\nround(compute_pi_pcm(theta = 0, bank_na)$Pi, 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          cat0     cat1     cat2     cat3     cat4\nItem1 0.034827 0.222162 0.415884 0.273802 0.053325\nItem2 0.039522 0.361717 0.598761       NA       NA\nItem3 0.049507 0.126230 0.425433 0.320251 0.078579\nItem4 0.072167 0.326029 0.391500 0.187726 0.022578\nItem5 0.253526 0.382783 0.272999 0.090692       NA\n```\n\n\n:::\n\n```{.r .cell-code}\nrowSums(compute_pi_pcm(theta = 0, bank_na)$Pi, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nItem1 Item2 Item3 Item4 Item5 \n    1     1     1     1     1 \n```\n\n\n:::\n\n```{.r .cell-code}\nna_diff <- t(mapply(function(th, d) {\n  a <- compute_pi_pcm(th, bank_na, D = d)\n  b <- catR::Pi(th, bank_na, model = \"PCM\", D = d)\n  c(same_NA_cells = identical(is.na(a$Pi), is.na(b$Pi)),\n    sapply(c(\"Pi\", \"dPi\", \"d2Pi\", \"d3Pi\"), function(k) max(abs(a[[k]] - b[[k]]), na.rm = TRUE)))\n}, settings$theta, settings$D))\ndata.frame(same_NA_cells_everywhere = all(na_diff[, \"same_NA_cells\"] == 1),\n           max_abs_difference       = max(na_diff[, -1]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  same_NA_cells_everywhere max_abs_difference\n1                     TRUE                  0\n```\n\n\n:::\n\n```{.r .cell-code}\nitem_gap <- rbind(c(-1, NA, 0.5, 1.5))   # an NA in the middle of the row\nrbind(compute_pi_pcm = compute_pi_pcm(theta = 0, item_gap)$Pi[1, ],\n      catR_Pi        = catR::Pi(th = 0, item_gap, model = \"PCM\")$Pi[1, ])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    cat0      cat1 cat2 cat3 cat4\ncompute_pi_pcm 0.2689414 0.7310586   NA   NA   NA\ncatR_Pi        0.2689414 0.7310586   NA   NA   NA\n```\n\n\n:::\n:::\n\n\nThe categories that do not exist are `NA` in the same cells as in `catR`, the remaining probabilities of each item still sum to 1, and everything else agrees. An `NA` in the middle of a row does not skip a step, because every later cumulative sum inherits it: it removes categories 2, 3 and 4 and leaves a dichotomous item, in `catR` as well.\n\n### Item information\n\nThe information and its two derivatives at $\\theta = 0$, then the largest absolute difference from `catR::Ii()` over all three, at the same abilities and metric constants, for the full and the `NA`-padded bank:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmine   <- compute_ii_pcm(theta = 0, bank)\ntheirs <- catR::Ii(th = 0, bank, model = \"PCM\")\ndata.frame(Ii   = mine$Ii,   Ii_catR   = theirs$Ii,\n           dIi  = mine$dIi,  dIi_catR  = theirs$dIi,\n           d2Ii = mine$d2Ii, d2Ii_catR = theirs$d2Ii)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Ii   Ii_catR         dIi    dIi_catR        d2Ii   d2Ii_catR\n1 0.8407174 0.8407174 -0.02462767 -0.02462767 -0.24497371 -0.24497371\n2 0.7383865 0.7383865  0.06707017  0.06707017 -0.14918727 -0.14918727\n3 0.8952369 0.8952369 -0.26667915 -0.26667915  0.01489645  0.01489645\n4 0.8363394 0.8363394  0.07422137  0.07422137 -0.28438800 -0.28438800\n5 0.9121881 0.9121881  0.35380136  0.35380136 -0.39974150 -0.39974150\n```\n\n\n:::\n\n```{.r .cell-code}\nii_diff <- t(mapply(function(th, d) {\n  sapply(list(full = bank, NA_padded = bank_na), function(b) {\n    a <- compute_ii_pcm(th, b, D = d)\n    r <- catR::Ii(th, b, model = \"PCM\", D = d)\n    max(abs(unlist(a) - unlist(r)))\n  })\n}, settings$theta, settings$D))\ncbind(settings, ii_diff)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   theta     D full NA_padded\n1   -6.0 1.000    0         0\n2   -3.0 1.000    0         0\n3   -1.0 1.000    0         0\n4    0.0 1.000    0         0\n5    0.7 1.000    0         0\n6    2.5 1.000    0         0\n7    6.0 1.000    0         0\n8   -6.0 1.702    0         0\n9   -3.0 1.702    0         0\n10  -1.0 1.702    0         0\n11   0.0 1.702    0         0\n12   0.7 1.702    0         0\n13   2.5 1.702    0         0\n14   6.0 1.702    0         0\n```\n\n\n:::\n:::\n\n\nThe largest difference is exactly zero.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninfo_grid <- seq(-4, 4, by = 0.05)\ninfo <- t(sapply(info_grid, function(th) compute_ii_pcm(th, bank)$Ii))\ndf_info <- data.frame(theta = info_grid, info)\nnames(df_info)[-1] <- paste0(\"item \", 1:5)\ndf_info_long <- reshape2::melt(df_info, id.vars = \"theta\",\n                               variable.name = \"item\", value.name = \"information\")\n\nggplot(df_info_long, aes(x = theta, y = information, color = item)) +\n  geom_line(linewidth = 1) +\n  labs(title = \"Item information curves\",\n       subtitle = \"each item has its own steps, so each curve has its own height and shape\",\n       x = expression(theta), y = \"information\", color = NULL) +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_pcm_files/figure-html/ii_plot-1.png){width=60%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_test <- data.frame(theta = info_grid, information = rowSums(info))\n\nggplot(df_test, aes(x = theta, y = information)) +\n  geom_line(linewidth = 1, color = \"steelblue\") +\n  labs(title = \"Test information\", x = expression(theta), y = \"information\") +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_pcm_files/figure-html/test_info_plot-1.png){width=60%}\n:::\n:::\n\n\nThe item curves differ in height as well as in location; the worked example on information curves below measures by how much.\n\nThe information inherits the $D$ convention. At $\\theta = 0.3$ the returned `Ii`, `dIi` and `d2Ii` are compared with the variance, the third central moment and the fourth cumulant of the item score; the exact information, built from finite-difference slopes of the probabilities, is divided by the returned one; and finite-difference derivatives of the returned `Ii` are divided by `dIi` and `d2Ii`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninformation_check <- sapply(c(\"D = 1\" = 1, \"D = 1.702\" = 1.702), function(d) {\n  p  <- compute_pi_pcm(th, bank, D = d)$Pi\n  C  <- matrix(0:4, 5, 5, byrow = TRUE) - as.vector(p %*% (0:4))   # k - E_j\n  V  <- rowSums(p * C^2)                                          # V_j\n  ii <- compute_ii_pcm(th, bank, D = d)\n  exact_information <- rowSums(slope(function(t) compute_pi_pcm(t, bank, D = d)$Pi)^2 / p)\n  s1 <- slope(function(t) compute_ii_pcm(t, bank, D = d)$Ii)\n  c2 <- (compute_ii_pcm(th + 1e-4, bank, D = d)$Ii - 2 * ii$Ii +\n         compute_ii_pcm(th - 1e-4, bank, D = d)$Ii) / 1e-4^2\n  c(max_abs_Ii_minus_variance = max(abs(ii$Ii   - V)),\n    max_abs_dIi_minus_kappa3  = max(abs(ii$dIi  - rowSums(p * C^3))),\n    max_abs_d2Ii_minus_kappa4 = max(abs(ii$d2Ii - (rowSums(p * C^4) - 3 * V^2))),\n    exact_over_Ii             = mean(exact_information / ii$Ii),\n    slope_Ii_over_dIi         = mean(s1 / ii$dIi),\n    curvature_Ii_over_d2Ii    = mean(c2 / ii$d2Ii))\n})\nround(information_check, 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                          D = 1 D = 1.702\nmax_abs_Ii_minus_variance     0    0.0000\nmax_abs_dIi_minus_kappa3      0    0.0000\nmax_abs_d2Ii_minus_kappa4     0    0.0000\nexact_over_Ii                 1    2.8968\nslope_Ii_over_dIi             1    1.7020\ncurvature_Ii_over_d2Ii        1    2.8968\n```\n\n\n:::\n\n```{.r .cell-code}\nc(D_squared = 1.702^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nD_squared \n 2.896804 \n```\n\n\n:::\n:::\n\n\nAt both values of $D$ the returned `Ii`, `dIi` and `d2Ii` are the second, third and fourth cumulants of the item score. At $D = 1$ they are the information and its exact first and second derivatives; at $D = 1.702$ the exact information is 2.8968 $= D^2$ times the returned value, and the slope and the curvature of the returned `Ii` are $D$ times `dIi` and $D^2$ times `d2Ii`.\n\n### Next-item selection\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmine   <- compute_next_item_pcm(theta = 0, bank)\ntheirs <- catR::nextItem(bank, model = \"PCM\", theta = 0, criterion = \"MFI\")\nc(mine_item = mine$item, catR_item = theirs$item,\n  mine_info = mine$info, catR_info = theirs$info)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmine_item catR_item mine_info catR_info \n5.0000000 5.0000000 0.9121881 0.9121881 \n```\n\n\n:::\n:::\n\n\nWith items already administered excluded via `out`: five exclusion sets, on a grid of abilities from $-6$ to $6$ and at both values of the metric constant, cross-tabulating the item each function selects:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nout_sets <- list(NULL, 5, c(5, 3), c(5, 3, 1), c(1, 2, 3, 5))\nout_grid <- expand.grid(theta = seq(-6, 6, by = 0.1), D = c(1, 1.702), out = seq_along(out_sets))\nselections <- t(mapply(function(th, d, o) {\n  mine   <- compute_next_item_pcm(th, bank, out = out_sets[[o]], D = d)\n  theirs <- catR::nextItem(bank, model = \"PCM\", theta = th, out = out_sets[[o]], D = d,\n                           criterion = \"MFI\")\n  c(mine = mine$item, catR = theirs$item, info_difference = abs(mine$info - theirs$info))\n}, out_grid$theta, out_grid$D, out_grid$out))\ntable(mine = selections[, \"mine\"], catR = selections[, \"catR\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    catR\nmine   1   2   3   4   5\n   1  56   0   0   0   0\n   2   0 338   0   0   0\n   3   0   0  75   0   0\n   4   0   0   0 617   0\n   5   0   0   0   0 124\n```\n\n\n:::\n\n```{.r .cell-code}\nc(comparisons = nrow(selections), max_info_difference = max(selections[, \"info_difference\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        comparisons max_info_difference \n               1210                   0 \n```\n\n\n:::\n:::\n\n\nEvery selection lies on the diagonal: in all 1210 combinations of ability, metric constant and excluded items, both functions select the same item, with the same information.\n\nWith `randomesque` above 1 both functions draw at random, so they can only be compared under the same seed. Both rank the candidates by decreasing information and make one draw from the same random-number stream:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsame_pick <- sapply(1:200, function(s) {\n  set.seed(s)\n  a <- catR::nextItem(bank, model = \"PCM\", theta = 0.4, out = 2, randomesque = 3)$item\n  set.seed(s)\n  b <- compute_next_item_pcm(theta = 0.4, bank, out = 2, randomesque = 3)$item\n  a == b\n})\ntable(same_pick)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsame_pick\nTRUE \n 200 \n```\n\n\n:::\n:::\n\n\nThe same item is drawn under all 200 seeds. This bank has no exact ties in information; with ties, the two functions would differ in the way described in the theory section.\n\n### Likelihood\n\n`catR` has no exported likelihood function to compare against, so the check reconstructs the same product from `catR`'s own probability matrix, at both values of $D$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresponse <- c(4, 3, 2, 1, 0)\nsapply(c(1, 1.702), function(d) {\n  P_catR <- catR::Pi(th = 0.3, bank, model = \"PCM\", D = d)$Pi\n  c(D = d,\n    compute_likelihood_pcm = compute_likelihood_pcm(theta = 0.3, bank = bank, x = response, D = d),\n    from_catR_Pi = prod(sapply(1:5, function(i) P_catR[i, response[i] + 1])))\n})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                               [,1]         [,2]\nD                      1.0000000000 1.7020000000\ncompute_likelihood_pcm 0.0004239852 0.0001343686\nfrom_catR_Pi           0.0004239852 0.0001343686\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlik_grid <- seq(-4, 4, by = 0.05)\ndf_lik <- data.frame(theta = lik_grid,\n                     likelihood = sapply(lik_grid, function(th)\n                       compute_likelihood_pcm(th, bank, response)))\n\nggplot(df_lik, aes(x = theta, y = likelihood)) +\n  geom_line(linewidth = 1, color = \"steelblue\") +\n  labs(title = \"Likelihood of the response pattern (4, 3, 2, 1, 0)\",\n       x = expression(theta), y = \"likelihood\") +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_pcm_files/figure-html/likelihood_plot-1.png){width=60%}\n:::\n:::\n\n\n### EAP ability estimate and standard error\n\nEight patterns on the full bank, including the two extreme ones for which maximum likelihood has no finite estimate, and three on the `NA`-padded bank, at both values of the metric constant:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npatterns    <- list(c(0, 0, 0, 0, 0), c(1, 1, 1, 1, 1), c(2, 2, 2, 2, 2), c(3, 3, 3, 3, 3),\n                    c(4, 4, 4, 4, 4), c(4, 3, 2, 1, 0), c(0, 4, 0, 4, 0), c(4, 4, 4, 4, 3))\npatterns_na <- list(c(0, 0, 0, 0, 0), c(4, 2, 3, 1, 3), c(4, 2, 4, 4, 3))   # item 2 scored 0 to 2, item 5 0 to 3\n\neap_row <- function(b, label, x, d) {\n  th_mine <- compute_eap_pcm(b, x, D = d)\n  data.frame(bank     = label,\n             D        = d,\n             pattern  = paste(x, collapse = \" \"),\n             eap_mine = th_mine,\n             eap_catR = catR::eapEst(b, x, model = \"PCM\", D = d),\n             se_mine  = compute_eap_se_pcm(th_mine, b, x, D = d),\n             se_catR  = catR::eapSem(th_mine, b, x, model = \"PCM\", D = d))\n}\nvalidation <- do.call(rbind, lapply(c(1, 1.702), function(d)\n  rbind(do.call(rbind, lapply(patterns,    function(x) eap_row(bank,    \"full\",      x, d))),\n        do.call(rbind, lapply(patterns_na, function(x) eap_row(bank_na, \"NA-padded\", x, d))))))\nvalidation\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        bank     D   pattern   eap_mine   eap_catR   se_mine   se_catR\n1       full 1.000 0 0 0 0 0 -2.2503535 -2.2503535 0.5916538 0.5916538\n2       full 1.000 1 1 1 1 1 -0.8813607 -0.8813607 0.4700995 0.4700995\n3       full 1.000 2 2 2 2 2  0.1350411  0.1350411 0.4415744 0.4415744\n4       full 1.000 3 3 3 3 3  1.1474792  1.1474792 0.4683922 0.4683922\n5       full 1.000 4 4 4 4 4  2.4760214  2.4760214 0.5683329 0.5683329\n6       full 1.000 4 3 2 1 0  0.1350411  0.1350411 0.4415744 0.4415744\n7       full 1.000 0 4 0 4 0 -0.2576244 -0.2576244 0.4459408 0.4459408\n8       full 1.000 4 4 4 4 3  2.1629756  2.1629756 0.5484565 0.5484565\n9  NA-padded 1.000 0 0 0 0 0 -2.2442060 -2.2442060 0.5943244 0.5943244\n10 NA-padded 1.000 4 2 3 1 3  0.9477636  0.9477636 0.5002069 0.5002069\n11 NA-padded 1.000 4 2 4 4 3  2.1531571  2.1531571 0.6072413 0.6072413\n12      full 1.702 0 0 0 0 0 -2.3278599 -2.3278599 0.5211812 0.5211812\n13      full 1.702 1 1 1 1 1 -0.8547948 -0.8547948 0.3564228 0.3564228\n14      full 1.702 2 2 2 2 2  0.1551035  0.1551035 0.3380806 0.3380806\n15      full 1.702 3 3 3 3 3  1.1589172  1.1589172 0.3576636 0.3576636\n16      full 1.702 4 4 4 4 4  2.5774475  2.5774475 0.4897417 0.4897417\n17      full 1.702 4 3 2 1 0  0.1551035  0.1551035 0.3380806 0.3380806\n18      full 1.702 0 4 0 4 0 -0.2375268 -0.2375268 0.3417986 0.3417986\n19      full 1.702 4 4 4 4 3  2.2045210  2.2045210 0.4456511 0.4456511\n20 NA-padded 1.702 0 0 0 0 0 -2.3273729 -2.3273729 0.5214667 0.5214667\n21 NA-padded 1.702 4 2 3 1 3  0.9170880  0.9170880 0.3829539 0.3829539\n22 NA-padded 1.702 4 2 4 4 3  2.2433632  2.2433632 0.5320307 0.5320307\n```\n\n\n:::\n\n```{.r .cell-code}\nc(max_eap_difference = max(abs(validation$eap_mine - validation$eap_catR)),\n  max_se_difference  = max(abs(validation$se_mine  - validation$se_catR)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmax_eap_difference  max_se_difference \n      4.440892e-16       1.110223e-16 \n```\n\n\n:::\n:::\n\n\nBoth the estimate and its standard error reproduce `catR` to within $4.4\\times 10^{-16}$ across all 22 combinations, including the all-lowest and all-highest patterns, the `NA`-padded bank and $D = 1.702$.\n\n---\n\n# Examples\n\n## Worked example: the rating scale model is a constrained partial credit model\n\nThe RSM writes every step as $\\lambda_j + \\delta_k$. Any RSM bank is therefore also a PCM bank, with step matrix $\\delta_{jk} = \\lambda_j + \\delta_k$. Take the RSM bank from the companion vignette and rewrite it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlambdaj <- c(-0.560, -0.230, 1.559, 0.071, 0.129)\ndeltak  <- c(1.715, 0.461, -1.265, -0.687)\n\nbank_rsm <- matrix(c(lambdaj, rep(deltak, each = 5)), nrow = 5,\n                   dimnames = list(1:5, c(\"lambdaj\", paste0(\"delta\", 1:4))))\nbank_from_rsm <- outer(lambdaj, deltak, \"+\")\ndimnames(bank_from_rsm) <- list(1:5, paste0(\"deltaj\", 1:4))\n\nbank_rsm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  lambdaj delta1 delta2 delta3 delta4\n1  -0.560  1.715  0.461 -1.265 -0.687\n2  -0.230  1.715  0.461 -1.265 -0.687\n3   1.559  1.715  0.461 -1.265 -0.687\n4   0.071  1.715  0.461 -1.265 -0.687\n5   0.129  1.715  0.461 -1.265 -0.687\n```\n\n\n:::\n\n```{.r .cell-code}\nbank_from_rsm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  deltaj1 deltaj2 deltaj3 deltaj4\n1   1.155  -0.099  -1.825  -1.247\n2   1.485   0.231  -1.495  -0.917\n3   3.274   2.020   0.294   0.872\n4   1.786   0.532  -1.194  -0.616\n5   1.844   0.590  -1.136  -0.558\n```\n\n\n:::\n:::\n\n\nThe RSM layout has five columns (location plus four thresholds); the PCM layout of the same items has four. The two parameterisations give the same probabilities, derivatives and information, whether computed with `compute_pi_rsm()` or with `compute_pi_pcm()`, and both agree with `catR::Pi(model = \"RSM\")`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrsm_pcm_diff <- t(mapply(function(th, d) {\n  a <- compute_pi_rsm(th, bank_rsm, D = d)\n  b <- compute_pi_pcm(th, bank_from_rsm, D = d)\n  c(sapply(c(\"Pi\", \"dPi\", \"d2Pi\", \"d3Pi\"), function(k) max(abs(a[[k]] - b[[k]]))),\n    Ii = max(abs(compute_ii_rsm(th, bank_rsm, D = d)$Ii - compute_ii_pcm(th, bank_from_rsm, D = d)$Ii)),\n    Pi_vs_catR_RSM = max(abs(catR::Pi(th, bank_rsm, model = \"RSM\", D = d)$Pi - b$Pi)))\n}, settings$theta, settings$D))\ncbind(settings, rsm_pcm_diff)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   theta     D Pi dPi d2Pi d3Pi Ii Pi_vs_catR_RSM\n1   -6.0 1.000  0   0    0    0  0              0\n2   -3.0 1.000  0   0    0    0  0              0\n3   -1.0 1.000  0   0    0    0  0              0\n4    0.0 1.000  0   0    0    0  0              0\n5    0.7 1.000  0   0    0    0  0              0\n6    2.5 1.000  0   0    0    0  0              0\n7    6.0 1.000  0   0    0    0  0              0\n8   -6.0 1.702  0   0    0    0  0              0\n9   -3.0 1.702  0   0    0    0  0              0\n10  -1.0 1.702  0   0    0    0  0              0\n11   0.0 1.702  0   0    0    0  0              0\n12   0.7 1.702  0   0    0    0  0              0\n13   2.5 1.702  0   0    0    0  0              0\n14   6.0 1.702  0   0    0    0  0              0\n```\n\n\n:::\n:::\n\n\nAnd the same EAP estimates:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrsm_patterns <- list(c(0, 0, 0, 0, 0), c(4, 3, 2, 1, 0), c(2, 2, 2, 2, 2), c(4, 4, 4, 4, 4))\nrsm_eap <- do.call(rbind, lapply(rsm_patterns, function(x) {\n  data.frame(pattern      = paste(x, collapse = \" \"),\n             eap_rsm      = compute_eap_rsm(bank_rsm, x),\n             eap_pcm      = compute_eap_pcm(bank_from_rsm, x),\n             eap_catR_RSM = catR::eapEst(bank_rsm, x, model = \"RSM\"),\n             eap_catR_PCM = catR::eapEst(bank_from_rsm, x, model = \"PCM\"))\n}))\nrsm_eap\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    pattern     eap_rsm     eap_pcm eap_catR_RSM eap_catR_PCM\n1 0 0 0 0 0 -1.31916068 -1.31916068  -1.31916068  -1.31916068\n2 4 3 2 1 0  0.09165378  0.09165378   0.09165378   0.09165378\n3 2 2 2 2 2  0.09165378  0.09165378   0.09165378   0.09165378\n4 4 4 4 4 4  1.86908014  1.86908014   1.86908014   1.86908014\n```\n\n\n:::\n\n```{.r .cell-code}\nc(max_abs_difference = max(abs(as.matrix(rsm_eap[, -1]) - rsm_eap$eap_rsm)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmax_abs_difference \n                 0 \n```\n\n\n:::\n:::\n\n\nThe converse does not hold. A PCM bank can be written as an RSM bank only if, after removing each item's mean step, every row is left with the same thresholds. The rewritten RSM bank passes that test by construction; the PCM bank of this vignette does not:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(bank_from_rsm - rowMeans(bank_from_rsm), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  deltaj1 deltaj2 deltaj3 deltaj4\n1   1.659   0.405  -1.321  -0.743\n2   1.659   0.405  -1.321  -0.743\n3   1.659   0.405  -1.321  -0.743\n4   1.659   0.405  -1.321  -0.743\n5   1.659   0.405  -1.321  -0.743\n```\n\n\n:::\n\n```{.r .cell-code}\nround(bank - rowMeans(bank), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  deltaj1 deltaj2 deltaj3 deltaj4\n1  -1.746  -0.520   0.524   1.742\n2  -2.189  -0.479   0.717   1.952\n3  -0.821  -1.100   0.400   1.520\n4  -1.798  -0.474   0.444   1.827\n5  -1.240  -0.490   0.274   1.457\n```\n\n\n:::\n:::\n\n\nIn the first matrix every row is the same; in the second no two rows are. The RSM describes this five-item, five-category bank with 8 free parameters ($n + m - 1$: its layout stores 9 numbers, but a constant can be moved between the $\\lambda_j$ and the $\\delta_k$) where the PCM spends 20 ($n \\times m$); the PCM's extra freedom is what the next example is about.\n\n---\n\n## Worked example: every item has its own information curve\n\nA few per-item summaries show how the items of the PCM bank differ:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbank_summary <- data.frame(mean_step = rowMeans(bank),\n                           spread    = apply(bank, 1, function(b) diff(range(b))),\n                           ordered   = !apply(bank, 1, is.unsorted))\nbank_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  mean_step spread ordered\n1  -0.10650  3.489    TRUE\n2  -0.02475  4.141    TRUE\n3  -0.11550  2.620   FALSE\n4   0.29050  3.626    TRUE\n5   0.82825  2.697    TRUE\n```\n\n\n:::\n:::\n\n\nThe items differ both in where their steps sit and in how widely they are spaced. Locate each item's information peak numerically, in the PCM bank and in the RSM bank rewritten above:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nitem_peaks <- function(b) {\n  t(sapply(1:nrow(b), function(j) {\n    opt <- optimize(function(th) compute_ii_pcm(th, b[j, , drop = FALSE])$Ii,\n                    interval = c(-6, 6), maximum = TRUE)\n    c(peak = opt$maximum, max_information = opt$objective)\n  }))\n}\npeaks     <- item_peaks(bank)\npeaks_rsm <- item_peaks(bank_from_rsm)\n\ndata.frame(bank_summary[, c(\"mean_step\", \"spread\")], peaks,\n           offset = peaks[, \"peak\"] - bank_summary$mean_step)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  mean_step spread       peak max_information       offset\n1  -0.10650  3.489 -0.1003451       0.8419535  0.006154867\n2  -0.02475  4.141  0.3839167       0.7518495  0.408666737\n3  -0.11550  2.620 -0.7471063       1.0357470 -0.631606322\n4   0.29050  3.626  0.2522402       0.8457751 -0.038259781\n5   0.82825  2.697  0.6332829       1.0313680 -0.194967056\n```\n\n\n:::\n\n```{.r .cell-code}\ndata.frame(mean_step = rowMeans(bank_from_rsm), peaks_rsm,\n           offset = peaks_rsm[, \"peak\"] - rowMeans(bank_from_rsm))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  mean_step       peak max_information      offset\n1    -0.504 -0.5532804        3.113338 -0.04928045\n2    -0.174 -0.2232778        3.113338 -0.04927776\n3     1.615  1.5657125        3.113338 -0.04928749\n4     0.127  0.0777152        3.113338 -0.04928480\n5     0.185  0.1357230        3.113338 -0.04927700\n```\n\n\n:::\n:::\n\n\nIn the rewritten RSM bank every item reaches the same maximum information (to $8.1\\times 10^{-10}$) at the same offset from its mean step: one curve, shifted. In the PCM bank the maximum ranges from 0.752 (item 2) to 1.036 (item 3), and the peak sits anywhere from -0.632 to 0.409 away from the item's mean step. The two tallest curves belong to the two items with the narrowest spread of steps, and the lowest curve to the item with the widest spread.\n\nBecause heights differ, an item can be beaten everywhere. Comparing MFI with the rule \"take the item whose mean step is closest to $\\theta$\" across the ability range:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid    <- seq(-4, 4, by = 0.05)\nmfi     <- sapply(grid, function(th) compute_next_item_pcm(th, bank)$item)\nnearest <- sapply(grid, function(th) which.min(abs(th - bank_summary$mean_step)))\nc(agreements = sum(mfi == nearest), grid_points = length(grid))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n agreements grid_points \n        109         161 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(MFI_choice = factor(mfi, levels = 1:5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMFI_choice\n 1  2  3  4  5 \n 5 33 42  0 81 \n```\n\n\n:::\n:::\n\n\nThe location rule agrees with MFI at only 109 of 161 points. Item 4 is never the most informative item anywhere between $-4$ and $4$, although its mean step (0.29) sits well inside the range of the bank: at every ability, some other item is more informative. It would still be administered once better items had been used up, which is why `compute_next_item_pcm()` evaluates every available item rather than looking up locations.\n\n### What shapes the curve\n\nWith the height and shape set by the spacing of the steps alone, synthetic items make the pattern easy to see. All have four steps, so the returned information cannot exceed $m_j^2/4 = 4$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapes <- rbind(\"equal (0, 0, 0, 0)\"          = c(0, 0, 0, 0),\n                \"narrow (-0.75 ... 0.75)\"     = c(-0.75, -0.25, 0.25, 0.75),\n                \"moderate (-1.5 ... 1.5)\"     = c(-1.5, -0.5, 0.5, 1.5),\n                \"moderate shifted by +2\"      = c(-1.5, -0.5, 0.5, 1.5) + 2,\n                \"wide (-4.5 ... 4.5)\"         = c(-4.5, -1.5, 1.5, 4.5),\n                \"reversed (0.75 ... -0.75)\"   = c(0.75, 0.25, -0.25, -0.75),\n                \"strongly reversed (6 ... -6)\" = c(6, 2, -2, -6))\n\nshape_grid <- seq(-8, 8, by = 0.01)\nshape_info <- sapply(1:nrow(shapes), function(j)\n  sapply(shape_grid, function(th) compute_ii_pcm(th, shapes[j, , drop = FALSE])$Ii))\ncolnames(shape_info) <- rownames(shapes)\n\nshape_summary <- data.frame(max_information = apply(shape_info, 2, max),\n                            local_maxima    = apply(shape_info, 2, function(v) sum(diff(sign(diff(v))) == -2)))\nshape_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                             max_information local_maxima\nequal (0, 0, 0, 0)                 2.0000000            1\nnarrow (-0.75 ... 0.75)            1.3665790            1\nmoderate (-1.5 ... 1.5)            0.9243122            1\nmoderate shifted by +2             0.9243122            1\nwide (-4.5 ... 4.5)                0.3452037            4\nreversed (0.75 ... -0.75)          2.7002050            1\nstrongly reversed (6 ... -6)       3.9919142            1\n```\n\n\n:::\n\n```{.r .cell-code}\n# the shifted item is the moderate item moved by exactly 2\nshifted <- sapply(shape_grid, function(th)\n  compute_ii_pcm(th + 2, shapes[\"moderate shifted by +2\", , drop = FALSE])$Ii)\nc(max_abs_difference_after_undoing_the_shift = max(abs(shifted - shape_info[, \"moderate (-1.5 ... 1.5)\"])))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmax_abs_difference_after_undoing_the_shift \n                                         0 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_shapes <- data.frame(theta = shape_grid, shape_info, check.names = FALSE)\ndf_shapes_long <- reshape2::melt(df_shapes, id.vars = \"theta\",\n                                 variable.name = \"steps\", value.name = \"information\")\n\nggplot(df_shapes_long, aes(x = theta, y = information, color = steps)) +\n  geom_hline(yintercept = 4, linetype = \"dashed\", color = \"grey40\") +\n  geom_line(linewidth = 0.9) +\n  labs(title = \"Information curves of synthetic four-step PCM items\",\n       subtitle = \"dashed line: the ceiling m^2/4 = 4\",\n       x = expression(theta), y = \"information\", color = NULL) +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_pcm_files/figure-html/info_shapes_plot-1.png){width=60%}\n:::\n:::\n\n\nSpreading the steps lowers and widens the curve — from 1.367 for the narrow item to 0.924 for the moderate one and 0.345 for the wide one, which splits into 4 bumps, one per step. Bringing the steps together and then past each other does the opposite: 2 with all four steps equal, 2.7 with mildly reversed steps and 3.992 with strongly reversed ones, close to the ceiling of 4 but not above it. Moving every step by 2 moves the curve by exactly 2 and changes nothing else. The real bank fits the same pattern: item 3, whose steps are the most compressed and partly reversed, has the tallest curve.\n\nA tall, narrow curve is not simply a better item. With strongly reversed steps the middle categories almost never occur, and the item behaves like a sharp dichotomy between 0 and 4 at a single point on the scale; the next-but-one example looks at that from the category side.\n\n---\n\n## Worked example: the raw score is all that matters\n\nFive response patterns, all summing to 10, spread over the items in completely different ways:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsame_total <- list(c(2, 2, 2, 2, 2), c(4, 3, 2, 1, 0), c(0, 1, 2, 3, 4),\n                   c(4, 4, 2, 0, 0), c(3, 3, 2, 1, 1))\n\nsufficiency <- data.frame(pattern   = sapply(same_total, paste, collapse = \" \"),\n                          raw_score = sapply(same_total, sum),\n                          theta_EAP = sapply(same_total, function(x) compute_eap_pcm(bank, x)))\nsufficiency$SE <- mapply(function(x, th) compute_eap_se_pcm(th, bank, x),\n                         same_total, sufficiency$theta_EAP)\ndata.frame(sufficiency[, 1:2],\n           theta_EAP = sprintf(\"%.12f\", sufficiency$theta_EAP),\n           SE        = sprintf(\"%.12f\", sufficiency$SE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    pattern raw_score      theta_EAP             SE\n1 2 2 2 2 2        10 0.135041138205 0.441574439094\n2 4 3 2 1 0        10 0.135041138205 0.441574439094\n3 0 1 2 3 4        10 0.135041138205 0.441574439094\n4 4 4 2 0 0        10 0.135041138205 0.441574439094\n5 3 3 2 1 1        10 0.135041138205 0.441574439094\n```\n\n\n:::\n\n```{.r .cell-code}\nc(eap_range = diff(range(sufficiency$theta_EAP)), se_range = diff(range(sufficiency$SE)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   eap_range     se_range \n1.665335e-16 5.551115e-17 \n```\n\n\n:::\n:::\n\n\nThe estimates and the standard errors are identical to twelve decimal places. The theory section says why: for two patterns with the same total, the likelihood ratio is a constant, $\\exp\\left[-D(S_1 - S_2)\\right]$. That constant can be computed from the steps each pattern has passed and compared with the ratio of the two likelihoods across $\\theta$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsteps_passed <- function(x) sum(sapply(seq_along(x), function(i) sum(bank[i, seq_len(x[i])])))\n\nx1 <- c(4, 3, 2, 1, 0)\nx2 <- c(0, 1, 2, 3, 4)\nratio_theta <- seq(-3, 3, by = 1)\nrbind(theta            = ratio_theta,\n      likelihood_ratio = sapply(ratio_theta, function(th)\n        compute_likelihood_pcm(th, bank, x1) / compute_likelihood_pcm(th, bank, x2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     [,1]     [,2]     [,3]     [,4]     [,5]     [,6]     [,7]\ntheta            -3.00000 -2.00000 -1.00000  0.00000  1.00000  2.00000  3.00000\nlikelihood_ratio 60.52158 60.52158 60.52158 60.52158 60.52158 60.52158 60.52158\n```\n\n\n:::\n\n```{.r .cell-code}\nc(closed_form = exp(-(steps_passed(x1) - steps_passed(x2))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclosed_form \n   60.52158 \n```\n\n\n:::\n:::\n\n\nThe ratio is the same at every $\\theta$ and equals the closed form. The two likelihoods have the same shape and differ only in height, so after normalisation the two posteriors are the same distribution.\n\nSufficiency means that, for a fixed set of items, the whole scoring procedure collapses into a **raw-score conversion table**: one EAP estimate and one standard error per possible total. Any pattern with the right total will do to compute it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npattern_for_total <- function(total, m = rep(4, 5)) {\n  x <- integer(length(m))\n  for (i in seq_along(m)) { x[i] <- min(m[i], total); total <- total - x[i] }\n  x\n}\n\nscore_table <- data.frame(raw_score = 0:20)\nscore_table$pattern   <- sapply(score_table$raw_score, function(s) paste(pattern_for_total(s), collapse = \" \"))\nscore_table$theta_EAP <- sapply(score_table$raw_score, function(s) compute_eap_pcm(bank, pattern_for_total(s)))\nscore_table$SE        <- mapply(function(s, th) compute_eap_se_pcm(th, bank, pattern_for_total(s)),\n                                score_table$raw_score, score_table$theta_EAP)\nscore_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   raw_score   pattern   theta_EAP        SE\n1          0 0 0 0 0 0 -2.25035348 0.5916538\n2          1 1 0 0 0 0 -1.91748870 0.5609377\n3          2 2 0 0 0 0 -1.62033060 0.5298916\n4          3 3 0 0 0 0 -1.35333006 0.5044758\n5          4 4 0 0 0 0 -1.10903348 0.4848793\n6          5 4 1 0 0 0 -0.88136072 0.4700995\n7          6 4 2 0 0 0 -0.66573479 0.4591589\n8          7 4 3 0 0 0 -0.45870968 0.4512896\n9          8 4 4 0 0 0 -0.25762439 0.4459408\n10         9 4 4 1 0 0 -0.06032754 0.4427614\n11        10 4 4 2 0 0  0.13504114 0.4415744\n12        11 4 4 3 0 0  0.33022530 0.4423497\n13        12 4 4 4 0 0  0.52699437 0.4451772\n14        13 4 4 4 1 0  0.72726683 0.4502495\n15        14 4 4 4 2 0  0.93323039 0.4578559\n16        15 4 4 4 3 0  1.14747916 0.4683922\n17        16 4 4 4 4 0  1.37319103 0.4823833\n18        17 4 4 4 4 1  1.61435651 0.5004693\n19        18 4 4 4 4 2  1.87592590 0.5230504\n20        19 4 4 4 4 3  2.16297563 0.5484565\n21        20 4 4 4 4 4  2.47602137 0.5683329\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(score_table, aes(x = raw_score, y = theta_EAP)) +\n  geom_ribbon(aes(ymin = theta_EAP - SE, ymax = theta_EAP + SE),\n              alpha = 0.2, fill = \"steelblue\") +\n  geom_line(color = \"steelblue\", linewidth = 1) +\n  geom_point(size = 2, color = \"steelblue\") +\n  labs(title = \"Raw-score conversion table: EAP estimate (± 1 SE)\",\n       x = \"raw score (out of 20)\", y = expression(hat(theta)[EAP])) +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_pcm_files/figure-html/score_table_plot-1.png){width=60%}\n:::\n:::\n\n\nThe estimate rises strictly with the raw score, from -2.25 at 0 to 2.476 at 20, well inside the integration bounds of $\\pm 4$: the prior pulls the posterior mean of the extreme patterns back towards zero. The standard error is largest at raw score 0 and 20 and smallest at 10, because a zero or a perfect score is compatible with a wide range of low or high abilities.\n\nThe table belongs to these five items. In an adaptive test different examinees answer different items, so two examinees with the same raw score generally have different estimates; the raw score is sufficient only given the items that were administered.\n\n---\n\n## Worked example: threshold ordering and modal categories\n\nIn item 3 the second step is easier than the first ($\\delta_{32}$ = -1.215 < $\\delta_{31}$ = -0.936). Such **reversed** steps are allowed by the PCM and are common in real data. The first check is that adjacent curves really do cross at the step parameters:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt(sapply(1:4, function(k) {\n  p <- compute_pi_pcm(theta = bank[3, k], bank[3, ])$Pi[1, ]\n  c(step = k, theta = unname(bank[3, k]), P_lower_category = unname(p[k]), P_upper_category = unname(p[k + 1]))\n}))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     step  theta P_lower_category P_upper_category\n[1,]    1 -0.936        0.2666953        0.2666953\n[2,]    2 -1.215        0.2807868        0.2807868\n[3,]    3  0.284        0.3823730        0.3823730\n[4,]    4  1.405        0.4251759        0.4251759\n```\n\n\n:::\n:::\n\n\nAt $\\theta = \\delta_{3k}$ categories $k-1$ and $k$ have exactly the same probability, for every $k$, whether or not the steps are ordered. Next, which categories are ever the single most likely response, for each item, on a fine grid from $-8$ to $8$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodal_categories <- function(b, th = seq(-8, 8, by = 0.01)) {\n  sort(unique(sapply(th, function(t) which.max(compute_pi_pcm(t, b)$Pi[1, ])))) - 1\n}\nsapply(1:5, function(j) paste(modal_categories(bank[j, ]), collapse = \" \"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"0 1 2 3 4\" \"0 1 2 3 4\" \"0 2 3 4\"   \"0 1 2 3 4\" \"0 1 2 3 4\"\n```\n\n\n:::\n\n```{.r .cell-code}\nmax_p_item3 <- apply(t(sapply(seq(-8, 8, by = 0.01), function(t) compute_pi_pcm(t, bank[3, ])$Pi[1, ])), 2, max)\nround(max_p_item3, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n cat0  cat1  cat2  cat3  cat4 \n0.999 0.281 0.440 0.451 0.999 \n```\n\n\n:::\n:::\n\n\nEvery category is modal somewhere for items 1, 2, 4 and 5. For item 3, category 1 never is: its probability never rises above 0.281. Once $\\theta$ is high enough for step 1 to be more likely passed than failed, step 2 — which is easier — is also more likely passed, so the response moves straight from category 0 to category 2. Sorting the steps into increasing order restores category 1 as a modal response:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nitem3_sorted <- sort(bank[3, ])\nrbind(as_given = bank[3, ], sorted = item3_sorted)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         deltaj1 deltaj2 deltaj3 deltaj4\nas_given  -0.936  -1.215   0.284   1.405\nsorted    -1.215  -0.936   0.284   1.405\n```\n\n\n:::\n\n```{.r .cell-code}\nlist(as_given = modal_categories(bank[3, ]), sorted = modal_categories(item3_sorted))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$as_given\n[1] 0 2 3 4\n\n$sorted\n[1] 0 1 2 3 4\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncurves_for <- function(b, label) {\n  g <- seq(-5, 5, by = 0.05)\n  m <- t(sapply(g, function(th) compute_pi_pcm(th, b)$Pi[1, ]))\n  d <- data.frame(theta = g, m)\n  names(d)[-1] <- paste0(\"category \", 0:4)\n  out <- reshape2::melt(d, id.vars = \"theta\", variable.name = \"category\", value.name = \"P\")\n  out$steps <- label\n  out\n}\n\nboth <- rbind(curves_for(bank[3, ],    \"as given (steps 1 and 2 reversed)\"),\n              curves_for(item3_sorted, \"sorted (ordered)\"))\n\nggplot(both, aes(x = theta, y = P, color = category)) +\n  geom_line(linewidth = 0.9) +\n  facet_wrap(~ steps) +\n  labs(title = \"Category response curves, item 3\",\n       subtitle = \"effect of step ordering on whether category 1 is ever modal\",\n       x = expression(theta), y = expression(P(theta)), color = NULL) +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_pcm_files/figure-html/ordering_plot-1.png){width=60%}\n:::\n:::\n\n\nThe information consequence:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npeak_information <- function(b) optimize(function(th) compute_ii_pcm(th, b)$Ii,\n                                         interval = c(-6, 6), maximum = TRUE)$objective\nc(as_given = peak_information(bank[3, ]), sorted = peak_information(item3_sorted))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n as_given    sorted \n1.0357470 0.9866207 \n```\n\n\n:::\n:::\n\n\nWith the steps as given, item 3 peaks at 1.036; with sorted steps, at 0.987. Swapping the two steps changes only the numerator of category 1, from $\\exp[D(\\theta-\\delta_{31})]$ to $\\exp[D(\\theta-\\delta_{32})]$ — the cumulative sums for categories 2 and above are the same, and the other probabilities move only through the common denominator — so the difference is modest here, but it runs in the direction of the synthetic items above: reversed steps give a taller curve. As with the synthetic items, that extra information comes from a category that does no distinct work, which is usually read as a sign that the response format is not being used as intended rather than as a well-functioning item.\n\nEvery category probability stays positive whatever the order of the steps, because each is an exponential divided by a sum of exponentials. That is a real difference from cumulative-boundary models such as the graded response model, whose boundaries must be ordered for all category probabilities to be non-negative.\n\n---\n\n## Worked example: a short adaptive test\n\nA five-item bank is too small to show adaptivity — any five-item test uses all five items — so this section simulates a 40-item PCM bank: each item gets a location between $-2.5$ and $2.5$, four steps spaced roughly one unit apart around it, and some noise in each step.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2024)\nn_items  <- 40\nlocation <- runif(n_items, -2.5, 2.5)\njitter   <- matrix(rnorm(4 * n_items, 0, 0.4), n_items)\nbig_bank <- round(location + matrix(c(-1.5, -0.5, 0.5, 1.5), n_items, 4, byrow = TRUE) + jitter, 3)\ncolnames(big_bank) <- paste0(\"deltaj\", 1:4)\n\nhead(big_bank)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     deltaj1 deltaj2 deltaj3 deltaj4\n[1,]   0.641   1.822   3.068   3.405\n[2,]  -2.269  -1.052  -0.220   0.106\n[3,]  -0.181   0.617   1.819   2.083\n[4,]  -0.594   0.561   1.541   3.188\n[5,]  -1.556  -0.057  -0.221   1.631\n[6,]  -1.110   0.456   1.657   2.800\n```\n\n\n:::\n\n```{.r .cell-code}\nc(items = nrow(big_bank), items_with_reversed_steps = sum(apply(big_bank, 1, is.unsorted)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    items items_with_reversed_steps \n                       40                         2 \n```\n\n\n:::\n:::\n\n\nAt each step the loop picks the most informative unadministered item at the current estimate, simulates a response from an examinee at the true ability, and rescores on the items given so far:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# simulate a response to item j from an examinee at theta\nsimulate_response <- function(j, theta, b) {\n  p <- compute_pi_pcm(theta, b[j, , drop = FALSE])$Pi[1, ]\n  p <- p[!is.na(p)]\n  sample(0:(length(p) - 1), size = 1, prob = p)\n}\n\nrun_cat <- function(true_theta, b, test_length = 10, randomesque = 1) {\n  theta <- 0\n  administered <- integer(0)\n  responses <- integer(0)\n  trace <- data.frame()\n  for (step in 1:test_length) {\n    sel <- compute_next_item_pcm(theta, b, out = administered, randomesque = randomesque)\n    administered <- c(administered, sel$item)\n    responses <- c(responses, simulate_response(sel$item, true_theta, b))\n\n    sub_bank <- b[administered, , drop = FALSE]\n    theta <- compute_eap_pcm(sub_bank, responses)\n    se <- compute_eap_se_pcm(theta, sub_bank, responses)\n\n    trace <- rbind(trace, data.frame(step = step, item = sel$item,\n                                     mean_step = mean(b[sel$item, ]),\n                                     information = sel$info,\n                                     response = tail(responses, 1),\n                                     theta_EAP = theta, SE = se))\n  }\n  trace\n}\n\nset.seed(1)\ntrue_theta <- 1.0\ntrace <- run_cat(true_theta, big_bank)\ntrace\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   step item mean_step information response theta_EAP        SE\n1     1    5  -0.05075   1.0792035        3 0.4894229 0.7394683\n2     2   23   0.90725   1.0793592        2 0.6135463 0.5974298\n3     3   16   1.24075   1.0666630        2 0.7967879 0.5075670\n4     4   28   1.33750   1.0750567        0 0.5022341 0.4591798\n5     5   27   0.49725   0.9940716        3 0.6638666 0.4142409\n6     6   40   0.78075   1.0277701        4 0.9802293 0.3808820\n7     7   24   1.90825   1.0163283        3 1.1883379 0.3593790\n8     8    3   1.08450   1.0317548        1 1.0684495 0.3357460\n9     9   25   1.27275   0.9019872        2 1.0919846 0.3199332\n10   10   13   1.16600   0.8324037        2 1.0863080 0.3070541\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(trace, aes(x = step, y = theta_EAP)) +\n  geom_hline(yintercept = true_theta, linetype = \"dashed\", color = \"grey40\") +\n  geom_ribbon(aes(ymin = theta_EAP - SE, ymax = theta_EAP + SE),\n              alpha = 0.2, fill = \"steelblue\") +\n  geom_line(color = \"steelblue\", linewidth = 1) +\n  geom_point(size = 2, color = \"steelblue\") +\n  annotate(\"text\", x = 1, y = true_theta + 0.08, hjust = 0,\n           label = \"true theta\", color = \"grey40\", size = 3.5) +\n  scale_x_continuous(breaks = trace$step) +\n  labs(title = \"Adaptive test: EAP estimate (± 1 SE) after each item\",\n       x = \"item administered\", y = expression(hat(theta)[EAP])) +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_pcm_files/figure-html/adaptive_plot-1.png){width=60%}\n:::\n:::\n\n\nThe standard error falls at every step, from 0.739 after the first item to 0.307 after the 10th, and the final estimate is 1.086 for a true ability of 1. The first item is chosen at $\\theta = 0$; once the estimate moves up, the mean steps of the items chosen move up with it (-0.051 for the first item, 1.133 on average for the other 9). The information column also shows that the chosen items differ in how much they deliver at the moment they are chosen.\n\n### Exposure control\n\nPure MFI is deterministic: every examinee starting at $\\theta = 0$ receives the same first item. The `randomesque` argument draws at random from the $k$ best instead:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\ntable(replicate(2000, compute_next_item_pcm(theta = 0, big_bank, randomesque = 1)$item))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   5 \n2000 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(replicate(2000, compute_next_item_pcm(theta = 0, big_bank, randomesque = 3)$item))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  2   5  27 \n679 657 664 \n```\n\n\n:::\n\n```{.r .cell-code}\ninfo_at_0 <- sort(compute_ii_pcm(theta = 0, big_bank)$Ii, decreasing = TRUE)\nc(best_item = info_at_0[1], mean_of_top_3 = mean(info_at_0[1:3]),\n  proportion_of_best = mean(info_at_0[1:3]) / info_at_0[1])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         best_item      mean_of_top_3 proportion_of_best \n          1.079204           1.026002           0.950703 \n```\n\n\n:::\n:::\n\n\nWith `randomesque = 1` one item is the first item of every test; with `randomesque = 3` the first item is spread over three, at an average cost of 4.9% of the information of the best one. The first item is only part of the story, so the whole adaptive test is repeated for 100 simulated examinees, with and without randomesque:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7)\nexaminees <- rnorm(100)\nsims <- lapply(c(1, 3), function(r) lapply(examinees, function(t) run_cat(t, big_bank, 10, r)))\n\nexposure_summary <- do.call(rbind, lapply(1:2, function(i) {\n  runs  <- sims[[i]]\n  rate  <- tabulate(unlist(lapply(runs, function(d) d$item)), nbins = nrow(big_bank)) / length(examinees)\n  final <- sapply(runs, function(d) tail(d$theta_EAP, 1))\n  data.frame(randomesque      = c(1, 3)[i],\n             max_exposure     = max(rate),\n             items_never_used = sum(rate == 0),\n             mean_final_SE    = mean(sapply(runs, function(d) tail(d$SE, 1))),\n             RMSE             = sqrt(mean((final - examinees)^2)))\n}))\nexposure_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  randomesque max_exposure items_never_used mean_final_SE      RMSE\n1           1         1.00                9     0.3158546 0.3563993\n2           3         0.81                3     0.3182340 0.3000608\n```\n\n\n:::\n:::\n\n\nRandomesque lowers the highest exposure rate from 1 to 0.81 and the number of never-used items from 9 to 3, while the mean final standard error moves from 0.316 to 0.318. The RMSE against the true abilities is 0.356 and 0.3; with 100 simulated examinees a difference of this size should not be over-read. Even with randomesque, the most-used item appears in 81% of the tests: drawing among the three best items spreads the load only so far when a few items are clearly better than the rest over a wide ability range.\n\n---\n\n## Worked example: the numerical settings\n\nThe EAP integrals are approximations, and four arguments control them. None of these is a free choice to make casually.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(4, 4, 4, 4, 4)   # the hardest case for numerical integration\n\nnumerical <- rbind(\n  data.frame(setting = \"quadrature points\", value = c(11, 33, 101, 501),\n             theta = sapply(c(11, 33, 101, 501),\n                            function(n) compute_eap_pcm(bank, x, nqp = n))),\n  data.frame(setting = \"integration bound\", value = c(3, 4, 6),\n             theta = sapply(c(3, 4, 6),\n                            function(b) compute_eap_pcm(bank, x, lower = -b, upper = b))),\n  data.frame(setting = \"prior SD\", value = c(1, 2),\n             theta = sapply(c(1, 2),\n                            function(s) compute_eap_pcm(bank, x, priorPar = c(0, s)))),\n  data.frame(setting = \"metric constant D\", value = c(1, 1.702),\n             theta = sapply(c(1, 1.702),\n                            function(d) compute_eap_pcm(bank, x, D = d)))\n)\nnumerical\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             setting   value    theta\n1  quadrature points  11.000 2.469688\n2  quadrature points  33.000 2.476021\n3  quadrature points 101.000 2.476705\n4  quadrature points 501.000 2.476780\n5  integration bound   3.000 2.286785\n6  integration bound   4.000 2.476021\n7  integration bound   6.000 2.493050\n8           prior SD   1.000 2.476021\n9           prior SD   2.000 3.176578\n10 metric constant D   1.000 2.476021\n11 metric constant D   1.702 2.577447\n```\n\n\n:::\n:::\n\n\n\n\nThree different kinds of effect are visible here, and they should not be confused with one another:\n\n- **Quadrature points** are pure approximation error. Moving from 11 to 33 points changes the estimate by 0.0063; from 101 to 501 it changes by $7.5\\times 10^{-5}$. The default of 33 is a reasonable accuracy/speed compromise and matches `catR`.\n- **Integration bounds** are also approximation error, but of a more dangerous kind. Truncating at $\\pm 3$ moves the estimate by 0.19 downwards, because for an all-maximum pattern the posterior still has real mass beyond $\\theta = 3$ and cutting it off silently biases the estimate. Widening to $\\pm 6$ changes it by 0.017. Bounds must be wide enough for the *most extreme pattern the bank can produce*, not for a typical one.\n- **The prior SD and the metric constant are not approximation error at all** — they are different models. Doubling the prior SD to 2 weakens the shrinkage and moves the estimate from 2.476 to 3.177; changing $D$ to 1.702 rescales the whole latent metric and moves it to 2.577. Both belong in the model specification and must match whatever was used to calibrate the step parameters.\n\n---\n\n# Conclusion\n\nThe six PCM functions in `cat_eap_pcm.R`, together with the two helpers in `cat_eap_common.R`, reproduce their `catR` counterparts: the normal density, the trapezoidal integrator, the PCM category probabilities and all three of their derivatives, the item information and its two derivatives, MFI item selection with and without `out` and with randomesque under a common seed, and the two integrals that define EAP scoring, at $D = 1$ and at $D = 1.702$; the probabilities, the information and the EAP estimates also for an `NA`-padded bank. The likelihood, which `catR` does not export, matches the product rebuilt from `catR`'s own probabilities, and the closed-form moment expressions and central finite differences confirm the derivatives independently of `catR`, at both metric constants.\n\nWritten out, the model's character is easy to see. Each item has its own steps, so each item has its own category curves and its own information curve: items differ in how much they can measure and not only where, one item in this small bank is never the best choice anywhere, and adaptive selection has to evaluate every available item. The Rating Scale Model is the special case with a common step pattern, and rewriting an RSM bank as a PCM bank changes nothing. Steps may be reversed without breaking the model, but a reversed pair leaves a category that is never the most likely response. The PCM is still a Rasch model, so the raw score is a sufficient statistic, and the returned information is simply the conditional score variance. Finally, the functions share catR's convention of leaving $D$ out of the derivatives: exact at $D = 1$, scaled by powers of $D$ at $D = 1.702$, and harmless for both maximum-information selection and EAP scoring.\n\n---\n\n# References\n\n- Andrich, D. (1978). A rating formulation for ordered response categories. *Psychometrika, 43*(4), 561–573.\n- Bock, R. D., & Mislevy, R. J. (1982). Adaptive EAP estimation of ability in a microcomputer environment. *Applied Psychological Measurement, 6*(4), 431–444.\n- Magis, D., & Barrada, J. R. (2017). Computerized adaptive testing with R: Recent updates of the package catR. *Journal of Statistical Software, Code Snippets, 76*(1), 1–19. https://doi.org/10.18637/jss.v076.c01\n- Magis, D., & Raîche, G. (2012). Random generation of response patterns under computerized adaptive testing with the R package catR. *Journal of Statistical Software, 48*(8), 1–31. https://doi.org/10.18637/jss.v048.i08\n- Masters, G. N. (1982). A Rasch model for partial credit scoring. *Psychometrika, 47*(2), 149–174.\n\n---\n\n*Rendered with R 4.6.1 · validated against catR 3.17*\n\n---\n\n# Comments\n\nQuestions, corrections and suggestions are welcome below (sign in with GitHub to post).\n\n```{=html}\n<div class=\"giscus\"></div>\n<script>\n(function () {\n  var s = document.createElement(\"script\");\n  s.src = \"https://giscus.app/client.js\";\n  s.setAttribute(\"data-repo\", \"sedzinfo/rwf\");\n  s.setAttribute(\"data-repo-id\", \"REPLACE_WITH_REPO_ID\");\n  s.setAttribute(\"data-category\", \"Comments\");\n  s.setAttribute(\"data-category-id\", \"REPLACE_WITH_CATEGORY_ID\");\n  s.setAttribute(\"data-mapping\", \"specific\");\n  s.setAttribute(\"data-term\", \"EAP PCM Ability Estimation in base R\");\n  s.setAttribute(\"data-strict\", \"1\");\n  s.setAttribute(\"data-reactions-enabled\", \"1\");\n  s.setAttribute(\"data-emit-metadata\", \"0\");\n  s.setAttribute(\"data-input-position\", \"top\");\n  s.setAttribute(\"data-theme\", \"light\");\n  s.setAttribute(\"data-lang\", \"en\");\n  s.setAttribute(\"data-loading\", \"lazy\");\n  s.crossOrigin = \"anonymous\";\n  s.async = true;\n  document.querySelector(\".giscus\").appendChild(s);\n})();\n</script>\n```\n",
    "supporting": [
      "eap_pcm_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}