{
  "hash": "e00951d50b5ab541bc04726f8a6aacc1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"EAP Dichotomous Ability Estimation in base R\"\ndescription: \"4PL model for right/wrong items: response probabilities, item information, EAP scoring and an adaptive test, validated against catR.\"\n---\n\n\n\n# Background\n\n## Acknowledgement\n\nThe functions in [`cat_eap_common.R`](https://github.com/sedzinfo/rwf/blob/main/working_examples/cat_eap_common.R) and [`cat_eap_dichotomous.R`](https://github.com/sedzinfo/rwf/blob/main/working_examples/cat_eap_dichotomous.R) are adapted from the source code of the **catR** package by David Magis, Gilles Raîche and Juan Ramón Barrada (Magis & Raîche, 2012; Magis & Barrada, 2017). The model parameterisations, the formulas for the response probabilities and their derivatives, the item information, maximum-information item selection and the trapezoidal EAP integration all follow catR's `Pi()`, `Ii()`, `nextItem()`, `eapEst()`, `eapSem()` and `integrate.catR()`, and much of the code keeps catR's structure line for line. The purpose of the rewrite is teaching, not replacement: every step is written out in plain base R so that it can be read, and catR remains the reference implementation that every function is checked against below. catR is free software distributed under the GNU General Public License (version 3 or later).\n\n## Description\n\nAdaptive testing packages like `catR` score examinees using **EAP (Expected A Posteriori)** ability estimation, a Bayesian method that stays numerically stable where Maximum Likelihood breaks down: a response pattern that is all-correct, all-incorrect, or otherwise perfectly separates the item bank has a likelihood with no finite maximum.\n\nThis vignette covers **dichotomous** items, scored right/wrong, under the **four-parameter logistic (4PL)** model, which contains the 1PL, 2PL and 3PL models as special cases. [`working_examples/cat_eap_common.R`](https://github.com/sedzinfo/rwf/blob/main/working_examples/cat_eap_common.R) holds the two model-free helpers, and [`working_examples/cat_eap_dichotomous.R`](https://github.com/sedzinfo/rwf/blob/main/working_examples/cat_eap_dichotomous.R) holds the six model-specific functions. Together they implement the full adaptive-testing pipeline in plain base R, with no runtime dependency on `catR`:\n\n| Function | File | Purpose | `catR` equivalent it mirrors |\n|---|---|---|---|\n| `density_function()` | `cat_eap_common.R` | Normal density | `stats::dnorm()` |\n| `integrate_cat()` | `cat_eap_common.R` | Numerical integration (trapezoidal rule) | `catR::integrate.catR()` |\n| `compute_pi_dichotomous()` | `cat_eap_dichotomous.R` | 4PL response probabilities and their first three derivatives | `catR::Pi()` |\n| `compute_ii_dichotomous()` | `cat_eap_dichotomous.R` | Item information and its first two derivatives | `catR::Ii()` |\n| `compute_next_item_dichotomous()` | `cat_eap_dichotomous.R` | Maximum Fisher information item selection | `catR::nextItem(criterion = \"MFI\")` |\n| `compute_likelihood_dichotomous()` | `cat_eap_dichotomous.R` | Likelihood of a 0/1 response pattern | *(internal to `catR::eapEst()`)* |\n| `compute_eap_dichotomous()` | `cat_eap_dichotomous.R` | EAP ability estimate | `catR::eapEst()` |\n| `compute_eap_se_dichotomous()` | `cat_eap_dichotomous.R` | EAP standard error | `catR::eapSem()` |\n\nThis vignette walks through the theory behind each function, validates every one of them against its `catR` counterpart, works through what the guessing and slipping parameters and unequal discriminations do to an estimate, and then runs a small adaptive test end to end.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(catR)\nsource(\"R/cat_eap_common.R\", local = knitr::knit_global())\nsource(\"R/cat_eap_dichotomous.R\", local = knitr::knit_global())\n```\n:::\n\n\n---\n\n## Theoretical Background\n\n### The four-parameter logistic (4PL) response model\n\nEvery dichotomous item response model gives the probability that an examinee with ability $\\theta$ answers item $j$ correctly. The 4PL model writes it as\n\n$$P_j(\\theta) = c_j + (d_j-c_j)\\,\\frac{e^{Da_j(\\theta-b_j)}}{1+e^{Da_j(\\theta-b_j)}}$$\n\n- $a_j$: **discrimination**, how steeply the curve rises around $b_j$\n- $b_j$: **difficulty**, the ability level at the curve's midpoint, where $P_j = (c_j+d_j)/2$\n- $c_j$: **guessing (lower asymptote)**, the success probability of an examinee of very low ability\n- $d_j$: **slipping or inattention (upper asymptote)**, the success probability of an examinee of very high ability\n- $D$: the metric constant, 1 for the logistic metric or 1.702 to make the logistic curve closely approximate the normal ogive\n\nSetting $d_j=1$ gives Birnbaum's (1968) **3PL** model; additionally setting $c_j=0$ gives the **2PL** model; additionally fixing $a_j$ to one common value across items gives the **1PL/Rasch** model. The upper asymptote $d_j<1$ was proposed by Barton and Lord (1981) for high-ability examinees who still miss an easy item through carelessness.\n\n### The item bank layout\n\n`cat_eap_dichotomous.R` expects `bank` to be a numeric matrix with **one row per item and exactly four columns**, read by position: column 1 holds $a_j$, column 2 $b_j$, column 3 $c_j$ and column 4 $d_j$. A dichotomous item always has two response categories, so the number of columns never changes and there is no `NA` padding; a 1PL, 2PL or 3PL item is entered as a 4PL item with $c_j=0$ and/or $d_j=1$. `compute_pi_dichotomous()`, which every other function calls, begins with `bank <- rbind(bank)`, so a single item may also be passed as a plain vector `c(a, b, c, d)`.\n\n### Derivatives of the response function\n\nWriting $e_j = \\exp\\big(Da_j(\\theta-b_j)\\big)$, `compute_pi_dichotomous()` returns $P_j$ together with its first three derivatives with respect to $\\theta$:\n\n$$P'_j = \\frac{Da_j(d_j-c_j)\\,e_j}{(1+e_j)^2}\n\\qquad\nP''_j = \\frac{D^2a_j^2(d_j-c_j)\\,e_j(1-e_j)}{(1+e_j)^3}\n\\qquad\nP'''_j = \\frac{D^3a_j^3(d_j-c_j)\\,e_j(e_j^2-4e_j+1)}{(1+e_j)^4}$$\n\nThe first derivative is what item information is built from; the second and third are what the derivatives of the information are built from. Neither maximum-information selection nor EAP scoring needs the derivatives of the information, but they are returned for parity with `catR`.\n\n### The probability floor\n\nFloating-point arithmetic cannot represent a probability arbitrarily close to 1: once $e_j/(1+e_j)$ is within half a unit in the last place of 1 it rounds to exactly 1. The code therefore replaces any $P_j$ that is exactly 0 with $10^{-10}$ and any that is exactly 1 with $1-10^{-10}$, as `catR::Pi()` does. Without this, $1-P_j$ could be exactly zero, and the item information (which divides by $P_j(1-P_j)$) would become infinite. The floor only matters for items with $c_j=0$ or $d_j=1$; any other item has asymptotes strictly inside $(0,1)$.\n\n### Item information\n\nThe Fisher information of a dichotomous item is its squared slope divided by the variance of the response:\n\n$$I_j(\\theta) = \\frac{P'^2_j}{P_j Q_j}, \\qquad Q_j = 1-P_j$$\n\nThis is the polytomous formula $\\sum_k (\\partial P_{jk}/\\partial\\theta)^2/P_{jk}$ with the two categories $P_j$ and $Q_j$, whose derivatives are $P'_j$ and $-P'_j$: $P'^2_j/P_j + P'^2_j/Q_j = P'^2_j/(P_jQ_j)$. **Test information** is the sum of the item informations, and its reciprocal square root is the asymptotic standard error of a maximum-likelihood ability estimate.\n\nFor a test of $n$ items, the test information is\n\n$$I(\\theta) = \\sum_{j=1}^{n} I_j(\\theta)$$\n\nFor the 2PL ($c_j=0$, $d_j=1$) the slope is $P'_j = Da_jP_jQ_j$, so the information reduces to $D^2a_j^2P_jQ_j$. It is symmetric around $b_j$, peaks there with height $D^2a_j^2/4$, and so is governed entirely by the discrimination: in a 2PL bank the high-$a$ items are simply better items. Guessing and slipping change both the height and the location of the peak. A guessing parameter $c_j>0$ (with $d_j=1$) lowers the information and moves its peak **above** $b_j$, to (Birnbaum, 1968)\n\n$$\\theta_{\\max} = b_j + \\frac{1}{Da_j}\\,\\log\\frac{1+\\sqrt{1+8c_j}}{2}$$\n\nbecause a correct answer from an examinee just below $b_j$ may well be a lucky guess and tells the test less than it would under the 2PL. The worked example on guessing and slipping below checks this formula numerically, and also checks its mirror image for $d_j<1$.\n\nIts mirror image, for slipping with $c_j=0$ and $d_j<1$, puts the peak **below** $b_j$, at\n\n$$\\theta_{\\max} = b_j - \\frac{1}{Da_j}\\,\\log\\frac{1+\\sqrt{1+8(1-d_j)}}{2}$$\n\n`compute_ii_dichotomous()` also returns the first two derivatives of the information. The first is\n\n$$I'_j = \\frac{P'_j\\,\\big[\\,2P_jQ_jP''_j - P'^2_j(Q_j-P_j)\\,\\big]}{P_j^2Q_j^2}$$\n\nand the second, written out in the same form as `catR::Ii()`, is\n\n$$I''_j = \\frac{2P_jQ_j\\big(P''^2_j + P'_jP'''_j\\big) - 2P'^2_jP''_j(Q_j-P_j)}{P_j^2Q_j^2}\n- \\frac{3P_j^2Q_jP'^2_jP''_j - P_jP'^4_j(2Q_j-P_j)}{P_j^4Q_j^2}\n+ \\frac{3P_jQ_j^2P'^2_jP''_j - Q_jP'^4_j(Q_j-2P_j)}{P_j^2Q_j^4}$$\n\nBoth are checked against finite differences below as well as against `catR`.\n\n### Next-item selection\n\nAn adaptive test picks, at each step, the unadministered item that is most informative at the current ability estimate: the **Maximum Fisher Information (MFI)** criterion. `compute_next_item_dichotomous()` computes $I_j(\\hat\\theta)$ for every item not listed in `out`, the indices of the items already administered, and returns the index of the best one, its information, and the indices that were available.\n\nThe best item is\n\n$$j^{*} = \\arg\\max_{j\\notin\\texttt{out}} I_j(\\hat\\theta)$$\n\nIf every item had the same $a_j$ with $c_j=0$ and $d_j=1$, the information curves would be copies of one another shifted by $b_j$, and MFI would reduce to picking the item whose $b_j$ is closest to $\\hat\\theta$. In a 4PL bank the curves differ in height and in shape, so a highly discriminating item some distance away can beat a weak item right on target, and the information of every available item really does have to be computed. This contrasts with the Rating Scale Model vignette, where every item reaches the same maximum information and MFI is close to (though not exactly) a nearest-neighbour lookup on the item locations.\n\nThe `randomesque` argument draws at random from the $k$ most informative items instead of always taking the single best. This is standard exposure control: pure MFI would give the same handful of highly discriminating items to almost everyone. Two documented differences from `catR::nextItem()` matter only for ties: when several items are exactly tied for the maximum, `catR` draws one of them at random while this function takes the first; and with `randomesque` above 1, `catR` also keeps every item tied with the last one kept.\n\nIn general `item` is drawn uniformly from the $k$ available items with the largest $I_j(\\hat\\theta)$ ($j^{*}$ when $k=1$), and `info` is its information, where\n\n$$k = \\max\\!\\big(1,\\ \\min(\\lfloor\\texttt{randomesque}\\rfloor,\\ |\\texttt{available}|)\\big), \\qquad \\texttt{available} = \\{\\,j : j\\notin\\texttt{out}\\,\\}$$\n\n### Likelihood of a response pattern\n\nAssuming **local independence** (conditional on $\\theta$, responses to different items are independent), the likelihood of a 0/1 response pattern $\\mathbf{x}=(x_1,\\ldots,x_n)$ is\n\n$$L(\\theta) = \\prod_{j=1}^{n} P_j(\\theta)^{x_j}\\,Q_j(\\theta)^{1-x_j}$$\n\nThe exponents act as a switch: a correct response contributes $P_j$, a wrong one $Q_j$. `catR` computes this product inside `eapEst()` and `eapSem()` without exporting it; `compute_likelihood_dichotomous()` exposes it as a function of its own, and `compute_eap_dichotomous()` and `compute_eap_se_dichotomous()` compute the same product internally.\n\n### EAP: a Bayesian point estimate\n\nMaximum Likelihood fails outright for an all-correct or all-incorrect pattern, because the likelihood keeps increasing toward $\\theta=\\pm\\infty$ with no interior maximum. EAP (Bock & Mislevy, 1982) sidesteps this by placing a **prior** $\\pi(\\theta)$ on ability (standard normal by default) and reporting the **mean of the posterior distribution**\n\n$$\\hat\\theta_{EAP} = E[\\theta \\mid \\mathbf{x}] = \\frac{\\displaystyle\\int \\theta\\,\\pi(\\theta)\\,L(\\theta)\\,d\\theta}{\\displaystyle\\int \\pi(\\theta)\\,L(\\theta)\\,d\\theta}$$\n\nThe prior is the normal density computed by `density_function()`:\n\n$$\\pi(\\theta) = \\frac{1}{\\sigma\\sqrt{2\\pi}}\\exp\\!\\left(-\\frac{(\\theta-\\mu)^2}{2\\sigma^2}\\right), \\qquad (\\mu,\\sigma) = \\texttt{priorPar}$$\n\nFor a response pattern $\\mathbf{x}=(x_1,\\ldots,x_n)$, the likelihood and the two integrands are\n\n$$\n\\begin{aligned}\nL(s) &= \\prod_{j=1}^{n} P_j(s)^{x_j}\\,[1-P_j(s)]^{1-x_j},\\\\\ng(s) &= s\\,\\pi(s)\\,L(s),\\\\\nh(s) &= \\pi(s)\\,L(s).\n\\end{aligned}\n$$\n\nOn the quadrature grid $X=(\\theta_1,\\ldots,\\theta_Q)$, where $Q=\\texttt{nqp}$ and $\\theta_q=\\texttt{lower}+(q-1)(\\texttt{upper}-\\texttt{lower})/(Q-1)$, the estimate is approximated by\n\n$$\n\\hat\\theta_{EAP} \\approx \\frac{\\operatorname{Trap}(X,\\,g(X))}{\\operatorname{Trap}(X,\\,h(X))},\n$$\n\nwhere $g(X)=(g(\\theta_1),\\ldots,g(\\theta_Q))$ and $h(X)=(h(\\theta_1),\\ldots,h(\\theta_Q))$. `Trap` denotes the trapezoidal integration implemented by `integrate_cat()` below.\n\n$$SE(\\hat\\theta_{EAP}) = \\sqrt{\\frac{\\displaystyle\\int (\\theta-\\hat\\theta_{EAP})^2\\,\\pi(\\theta)\\,L(\\theta)\\,d\\theta}{\\displaystyle\\int \\pi(\\theta)\\,L(\\theta)\\,d\\theta}}$$\n\nFor this calculation, the numerator integrand is the squared distance from the EAP estimate times the posterior weight; the denominator is the same posterior weight used above:\n\n$$\n\\begin{aligned}\ng_{SE}(s) &= (s-\\hat\\theta_{EAP})^2\\,\\pi(s)\\,L(s),\\\\\nh(s) &= \\pi(s)\\,L(s).\n\\end{aligned}\n$$\n\nUsing the same quadrature grid $X$ as above, the numerical estimate is\n\n$$\nSE(\\hat\\theta_{EAP}) \\approx \\sqrt{\\frac{\\operatorname{Trap}(X,\\,g_{SE}(X))}{\\operatorname{Trap}(X,\\,h(X))}}.\n$$\n\n`compute_eap_se_dichotomous()` centres the deviation at its `theta` argument $t$, which is $\\hat\\theta_{EAP}$ in normal use but need not be:\n\n$$\\operatorname{RMSD}(t) = \\sqrt{\\frac{\\operatorname{Trap}(X,\\,g_t(X))}{\\operatorname{Trap}(X,\\,h(X))}}, \\qquad g_t(s) = (s-t)^2\\,\\pi(s)\\,L(s)$$\n\nAll four integrals are finite, and both denominators are positive, for every response pattern: $0<L(\\theta)\\le 1$ and the normal prior has a finite mean and variance. This is what rescues the all-correct and all-incorrect patterns, whose likelihood never shrinks to zero in one tail and so cannot be integrated on its own.\n\n### Numerical integration\n\nNeither integral has a closed form, so the integrands are evaluated at `nqp` **quadrature points** $\\theta_1<\\cdots<\\theta_Q$ (default 33, evenly spaced from `lower` to `upper`, default $\\pm4$) and integrated with the **trapezoidal rule**, which approximates the area between two adjacent points by a trapezoid, the width times the average of the two heights:\n\n$$\\int f(\\theta)\\,d\\theta \\approx \\sum_{q=1}^{Q-1} (\\theta_{q+1}-\\theta_q)\\,\\frac{f(\\theta_q)+f(\\theta_{q+1})}{2}$$\n\n`integrate_cat()` implements exactly this sum; `density_function()` supplies $\\pi(\\theta)$.\n\n### What the response pattern contributes\n\nWhich feature of a response pattern the estimate depends on is a property of the model. Under the **1PL/Rasch** model the likelihood depends on the pattern only through the **number correct** $\\sum_j x_j$, which is a sufficient statistic for $\\theta$: two examinees with the same number correct get the same estimate whichever items they answered correctly. This is what the Rating Scale and Partial Credit Model vignettes show for their raw scores. Under the **2PL** the sufficient statistic becomes the **discrimination-weighted score** $\\sum_j a_jx_j$: a correct answer to a highly discriminating item counts for more, and the item difficulties play no part at all. Under the **3PL and 4PL** there is no simple sufficient statistic, and the whole pattern matters. A worked example below demonstrates all three cases.\n\n---\n\n# Validation\n\n## The item bank\n\nThe bank from the roxygen examples of `cat_eap_dichotomous.R`: five items spanning the ability range, with different discriminations, and a guessing parameter of 0.1 and an upper asymptote of 0.9 on every item.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbank<-matrix(c(1.75,1.80,1.85,1.90,1.95,\n              -3,-2,0,2,3,\n               0.1,0.1,0.1,0.1,0.1,\n               0.9,0.9,0.9,0.9,0.9),\n             nrow=5,\n             dimnames=list(c(1,2,3,4,5),\n                           c(\"a\",\"b\",\"c\",\"d\")))\nbank\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     a  b   c   d\n1 1.75 -3 0.1 0.9\n2 1.80 -2 0.1 0.9\n3 1.85  0 0.1 0.9\n4 1.90  2 0.1 0.9\n5 1.95  3 0.1 0.9\n```\n\n\n:::\n:::\n\n\nBecause $c_j = 1 - d_j$ for every item here, each curve is point-symmetric around its own $b_j$; the section on item information shows what that does to the location of the information peak.\n\n---\n\n## Validating each piece against `catR`\n\n### Normal density\n\n\n::: {.cell}\n\n```{.r .cell-code}\nv <- seq(-3, 3, by = 0.1)\ncomparison <- data.frame(x = v, density_function = density_function(v), dnorm = dnorm(v))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(comparison, aes(x = x)) +\n  geom_line(aes(y = density_function, color = \"density_function()\"), linewidth = 1) +\n  geom_point(aes(y = dnorm, color = \"dnorm()\"), shape = 1) +\n  labs(title = \"Hand-written normal density vs. dnorm()\",\n       x = expression(theta), y = \"density\", color = NULL) +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_dichotomous_files/figure-html/density_plot-1.png){width=60%}\n:::\n:::\n\n\n### Numerical integration\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- seq(from = -3, to = 3, length = 33)\ny <- round(exp(x), 2)\ndata.frame(integrate_cat = integrate_cat(x, y), \n           integrate.catR = catR::integrate.catR(x, y))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  integrate_cat integrate.catR\n1      20.09437       20.09437\n```\n\n\n:::\n:::\n\n\nBoth approximate $\\int_{-3}^{3} e^x\\,dx$ on the same 33-point trapezoidal grid and return the same number.\n\n### Response probabilities and derivatives\n\nAt a single ability value, the whole returned list (probabilities and all three derivatives) matches `catR::Pi()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(catR=catR::Pi(th = 0, bank),\n           compute_pi_dichotomous(theta = 0, bank))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    catR.Pi    catR.dPi    catR.d2Pi   catR.d3Pi        Pi         dPi\n1 0.8958239 0.007270026 -0.012589720  0.02157076 0.8958239 0.007270026\n2 0.8787224 0.037281015 -0.063536200  0.10202719 0.8787224 0.037281015\n3 0.5000000 0.370000000  0.000000000 -0.63316250 0.5000000 0.370000000\n4 0.1175050 0.032531771  0.059105386  0.10235869 0.1175050 0.032531771\n5 0.1022973 0.004466877  0.008660385  0.01669349 0.1022973 0.004466877\n          d2Pi        d3Pi\n1 -0.012589720  0.02157076\n2 -0.063536200  0.10202719\n3  0.000000000 -0.63316250\n4  0.059105386  0.10235869\n5  0.008660385  0.01669349\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheta_grid <- seq(-6, 6, by = 0.01)\nprob_curves <- t(sapply(theta_grid, function(th) compute_pi_dichotomous(theta = th, bank)$Pi))\ndf_curves <- data.frame(theta = theta_grid, prob_curves)\nnames(df_curves)[-1] <- paste0(\"item \", 1:5, \" (a=\", bank[, \"a\"], \", b=\", bank[, \"b\"], \")\")\ndf_curves_long <- reshape2::melt(df_curves, id.vars = \"theta\",\n                                 variable.name = \"item\", value.name = \"P\")\nggplot(df_curves_long, aes(x = theta, y = P, color = item)) +\n  geom_hline(yintercept = c(0.1, 0.9), linetype = \"dashed\", color = \"grey50\") +\n  geom_line(linewidth = 1) +\n  scale_y_continuous(expand=c(0, 0), limits=c(0, 1)) +\n  labs(title = \"ICF\",\n       subtitle = \"every item has lower asymptote c = 0.1 and upper asymptote d = 0.9 (dashed)\",\n       x = expression(theta),\n       y = expression(P(theta)),\n       color = NULL) +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_dichotomous_files/figure-html/pi_plot-1.png){width=60%}\n:::\n:::\n\n\nEach curve rises from the guessing floor of 0.1 to the slipping ceiling of 0.9, passing through 0.5 at its own $b_j$. Steeper curves (higher $a$) discriminate more sharply around their difficulty; curves shifted right are harder.\n\n### Item information\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(catR=catR::Ii(th = 0, bank),compute_ii_dichotomous(theta = 0, bank))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       catR.Ii      catR.dIi    catR.d2Ii           Ii           dIi\n1 0.0005663452 -0.0019265867  0.006460126 0.0005663452 -0.0019265867\n2 0.0130419693 -0.0409977656  0.119867898 0.0130419693 -0.0409977656\n3 0.5476000000  0.0000000000 -1.274429480 0.5476000000  0.0000000000\n4 0.0102057931  0.0346355167  0.110734946 0.0102057931  0.0346355167\n5 0.0002172758  0.0008341025  0.003176704 0.0002172758  0.0008341025\n          d2Ii\n1  0.006460126\n2  0.119867898\n3 -1.274429480\n4  0.110734946\n5  0.003176704\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninfo_grid <- seq(-5, 5, by = 0.02)\ninfo <- t(sapply(info_grid, function(th) compute_ii_dichotomous(th, bank)$Ii))\ndf_info <- data.frame(theta = info_grid, info)\nnames(df_info)[-1] <- paste0(\"item \", 1:5, \" (a=\", bank[, \"a\"], \", b=\", bank[, \"b\"], \")\")\ndf_info_long <- reshape2::melt(df_info, id.vars = \"theta\",\n                               variable.name = \"item\", value.name = \"information\")\n\nggplot(df_info_long, aes(x = theta, y = information, color = item)) +\n  geom_line(linewidth = 1) +\n  labs(title = \"Item information curves\",\n       subtitle = \"different heights and widths: the discrimination sets how useful an item can be\",\n       x = expression(theta), y = \"information\", color = NULL) +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_dichotomous_files/figure-html/ii_plot-1.png){width=60%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_test <- data.frame(theta = info_grid, information = rowSums(info))\n\nggplot(df_test, aes(x = theta, y = information)) +\n  geom_line(linewidth = 1, color = \"steelblue\") +\n  labs(title = \"Test information\", x = expression(theta), y = \"information\") +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_dichotomous_files/figure-html/test_info_plot-1.png){width=60%}\n:::\n:::\n\n\nLocating each item's peak numerically shows how different this is from a Rasch-family bank:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npeaks <- t(sapply(1:5, function(j) {\n  opt <- optimize(function(th) compute_ii_dichotomous(th, bank[j, , drop = FALSE])$Ii,\n                  interval = bank[j, \"b\"] + c(-4, 4), maximum = TRUE, tol = 1e-10)\n  c(peak = opt$maximum, max_information = opt$objective)\n}))\ndata.frame(b = bank[, \"b\"], a = bank[, \"a\"], peaks,\n           peak_minus_b      = peaks[, \"peak\"] - bank[, \"b\"],\n           ratio_to_2PL_peak = peaks[, \"max_information\"] / (bank[, \"a\"]^2 / 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   b    a          peak max_information  peak_minus_b ratio_to_2PL_peak\n1 -3 1.75 -3.000000e+00          0.4900  2.220446e-15              0.64\n2 -2 1.80 -2.000000e+00          0.5184  1.554312e-15              0.64\n3  0 1.85 -6.253594e-09          0.5476 -6.253594e-09              0.64\n4  2 1.90  2.000000e+00          0.5776  8.881784e-16              0.64\n5  3 1.95  3.000000e+00          0.6084  1.332268e-15              0.64\n```\n\n\n:::\n:::\n\n\n### Next-item selection\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmine <- compute_next_item_dichotomous(theta = 0, bank)\ntheirs <- catR::nextItem(bank, theta = 0, criterion = \"MFI\")\nc(mine_item = mine$item, catR_item = theirs$item,\n  mine_info = unname(mine$info), catR_info = unname(theirs$info))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmine_item catR_item mine_info catR_info \n   3.0000    3.0000    0.5476    0.5476 \n```\n\n\n:::\n:::\n\n\nWith items already administered excluded via `out`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmine <- compute_next_item_dichotomous(theta = 0, bank, out = 3)\ntheirs <- catR::nextItem(bank, theta = 0, out = 3, criterion = \"MFI\")\nc(mine_item = mine$item, catR_item = theirs$item,\n  mine_info = unname(mine$info), catR_info = unname(theirs$info))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n mine_item  catR_item  mine_info  catR_info \n2.00000000 2.00000000 0.01304197 0.01304197 \n```\n\n\n:::\n:::\n\n\n### Likelihood\n\n`catR` has no exported likelihood function to compare against, so the check rebuilds the same product from `catR`'s own probabilities, for several patterns and ability values:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresponse <- c(1, 1, 1, 0, 0)\nP_catR <- catR::Pi(th = 0.3, bank)$Pi\nc(compute_likelihood_dichotomous = compute_likelihood_dichotomous(theta = 0.3, bank = bank, x = response),\n  from_catR_Pi                   = prod(P_catR^response * (1 - P_catR)^(1 - response)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncompute_likelihood_dichotomous                   from_catR_Pi \n                     0.3774149                      0.3774149 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlik_grid <- seq(-6, 6, by = 0.05)\ndf_lik <- data.frame(theta = lik_grid,\n                     \"1 1 1 0 0\" = sapply(lik_grid, function(th)\n                       compute_likelihood_dichotomous(th, bank, c(1, 1, 1, 0, 0))),\n                     \"1 1 1 1 1\" = sapply(lik_grid, function(th)\n                       compute_likelihood_dichotomous(th, bank, c(1, 1, 1, 1, 1))),\n                     check.names = FALSE)\ndf_lik_long <- reshape2::melt(df_lik, id.vars = \"theta\",\n                              variable.name = \"pattern\", value.name = \"likelihood\")\n\nggplot(df_lik_long, aes(x = theta, y = likelihood, color = pattern)) +\n  geom_hline(yintercept = prod(bank[, \"d\"]), linetype = \"dashed\", color = \"grey50\") +\n  geom_line(linewidth = 1) +\n  labs(title = \"Likelihood of two response patterns\",\n       subtitle = \"dashed line: the product of the upper asymptotes d\",\n       x = expression(theta), y = \"likelihood\", color = \"pattern\") +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_dichotomous_files/figure-html/likelihood_plot-1.png){width=60%}\n:::\n:::\n\n\n### EAP ability estimate and standard error\n\n\n::: {.cell}\n\n```{.r .cell-code}\npatterns <- list(c(0, 0, 0, 0, 0),\n                 c(1, 0, 0, 0, 0),\n                 c(1, 1, 0, 0, 0),\n                 c(1, 1, 1, 0, 0),\n                 c(1, 1, 1, 1, 0),\n                 c(1, 1, 1, 1, 1),\n                 c(0, 0, 1, 1, 1),\n                 c(0, 1, 0, 1, 0))\n\nresults<-do.call(rbind,lapply(patterns,function(x) {\n  est_0<-compute_eap_dichotomous(bank,x,D=1,priorPar=c(0,1),lower=-4,upper=4,nqp=33)\n  est_1<-catR::eapEst(bank,x,D=1,priorDist=\"norm\",priorPar=c(0,1),lower=-4,upper=4,nqp=33)\n  se_0<-compute_eap_se_dichotomous(est_0,bank,x,D=1,priorPar=c(0,1),lower=-4,upper=4,nqp=33)\n  se_1<-catR::eapSem(est_0,bank,x,D=1,priorPar=c(0,1),lower=-4,upper=4,nqp=33)\n  data.frame(pattern=paste(x,collapse=\"\"),\n             eap=est_0,\n             eap_catR=est_1,\n             se=se_0,\n             se_catR=se_1)\n}))\nresults\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  pattern        eap   eap_catR        se   se_catR\n1   00000 -1.3397028 -1.3397028 1.0024100 1.0024100\n2   10000 -0.8954934 -0.8954934 0.8875608 0.8875608\n3   11000 -0.3790041 -0.3790041 0.7775310 0.7775310\n4   11100  0.3886053  0.3886053 0.7758057 0.7758057\n5   11110  0.9114764  0.9114764 0.8934987 0.8934987\n6   11111  1.3498110  1.3498110 1.0229576 1.0229576\n7   00111  0.9696999  0.9696999 1.3409227 1.3409227\n8   01010 -0.2755731 -0.2755731 1.0216724 1.0216724\n```\n\n\n:::\n:::\n\n\n\n---\n\n# Examples\n\n## Worked example: the estimate across the number-correct range\n\nReproducing \"Example 1\" from the bottom of `cat_eap_dichotomous.R`: a 2PL bank ($c_j = 0$, $d_j = 1$) scored against response patterns with an increasing number of correct answers, always the *easiest* items first.\n\n\n::: {.cell}\n\n```{.r .cell-code}\na_2pl <- c(0.7521, 0.8083, 1.1857, 0.5481, 0.5695)\nb_2pl <- c(-1.5521, -0.9083, 0.1857, 0.5481, 1.5695)\nbank_2pl <- matrix(c(a_2pl, b_2pl, rep(0, 5), rep(1, 5)), nrow = 5,\n                   dimnames = list(1:5, c(\"a\", \"b\", \"c\", \"d\")))\nbank_2pl\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       a       b c d\n1 0.7521 -1.5521 0 1\n2 0.8083 -0.9083 0 1\n3 1.1857  0.1857 0 1\n4 0.5481  0.5481 0 1\n5 0.5695  1.5695 0 1\n```\n\n\n:::\n\n```{.r .cell-code}\nresponses <- list(c(0, 0, 0, 0, 0),\n                  c(1, 0, 0, 0, 0),\n                  c(1, 1, 0, 0, 0),\n                  c(1, 1, 1, 0, 0),\n                  c(1, 1, 1, 1, 0),\n                  c(1, 1, 1, 1, 1))\n\nresults <- data.frame(\n  n_correct = sapply(responses, sum),\n  theta_EAP = sapply(responses, function(x) compute_eap_dichotomous(bank_2pl, x))\n)\nresults$SE <- mapply(function(x, th) compute_eap_se_dichotomous(th, bank_2pl, x),\n                     responses, results$theta_EAP)\nresults\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  n_correct  theta_EAP        SE\n1         0 -1.2469219 0.7962924\n2         1 -0.7780203 0.7832647\n3         2 -0.2881144 0.7752039\n4         3  0.4264169 0.7810946\n5         4  0.7648196 0.7910812\n6         5  1.1272372 0.8046738\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(results, aes(x = n_correct, y = theta_EAP)) +\n  geom_ribbon(aes(ymin = theta_EAP - SE, ymax = theta_EAP + SE), alpha = 0.2, fill = \"steelblue\") +\n  geom_line(color = \"steelblue\", linewidth = 1) +\n  geom_point(size = 2, color = \"steelblue\") +\n  labs(title = \"EAP estimate (± 1 SE) vs. number of items correct\",\n       x = \"number of items correct (out of 5)\", y = expression(hat(theta)[EAP])) +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_dichotomous_files/figure-html/worked_example_plot-1.png){width=60%}\n:::\n:::\n\n\nThe estimate climbs monotonically with the number of correct responses, from -1.247 to 1.127. It never approaches the integration bounds of $\\pm4$, even for the all-incorrect and all-correct patterns: the normal prior pulls the posterior mean back toward 0. That regularisation is the reason to prefer EAP over Maximum Likelihood at the edges of the score range, and the price is a deliberate, known bias toward the prior mean.\n\nThe standard error barely moves across the range, from 0.775 to 0.805. It is smallest for 2 correct and largest for 5 correct: a mid-range pattern pins $\\theta$ down a little more tightly against this bank than a perfect or a zero score, which is compatible with a wide range of high (or low) abilities. Five items of moderate discrimination cannot shrink a standard normal prior by much, which is why the standard error stays close to 0.8 throughout.\n\n---\n\n## Worked example: standard error as a function of $\\theta$\n\n`compute_eap_se_dichotomous()` takes `theta` as a free argument. Passing the EAP estimate returns the posterior standard deviation; passing anything else returns the posterior root mean squared deviation around that point. The same 2PL bank, evaluated at every $\\theta$ from $-3$ to $3$ under three response patterns:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nse_grid <- seq(-3, 3, by = 0.05)\nse_patterns <- list(\"all incorrect (0 0 0 0 0)\" = c(0, 0, 0, 0, 0),\n                    \"all correct (1 1 1 1 1)\"   = c(1, 1, 1, 1, 1),\n                    \"2 of 5 correct (1 0 1 0 0)\" = c(1, 0, 1, 0, 0))\n\nse_df <- do.call(rbind, lapply(names(se_patterns), function(nm) {\n  data.frame(theta = se_grid,\n             SE = sapply(se_grid, function(th)\n               compute_eap_se_dichotomous(theta = th, bank = bank_2pl, x = se_patterns[[nm]])),\n             pattern = nm)\n}))\n\neap_points <- do.call(rbind, lapply(names(se_patterns), function(nm) {\n  th <- compute_eap_dichotomous(bank_2pl, se_patterns[[nm]])\n  data.frame(theta = th, SE = compute_eap_se_dichotomous(th, bank_2pl, se_patterns[[nm]]),\n             pattern = nm)\n}))\neap_points\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        theta        SE                    pattern\n1 -1.24692189 0.7962924  all incorrect (0 0 0 0 0)\n2  1.12723723 0.8046738    all correct (1 1 1 1 1)\n3 -0.06158777 0.7746548 2 of 5 correct (1 0 1 0 0)\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(se_df, aes(x = theta, y = SE, color = pattern)) +\n  geom_line(linewidth = 1) +\n  geom_point(data = eap_points, size = 3) +\n  labs(title = \"Posterior RMSD vs. evaluation point, by response pattern\",\n       subtitle = \"solid points mark the EAP estimate, where each curve bottoms out\",\n       x = expression(theta), y = \"standard error\", color = NULL) +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_dichotomous_files/figure-html/se_curves_plot-1.png){width=60%}\n:::\n:::\n\n\nEach curve bottoms out at its own EAP estimate. This is not a coincidence of the bank but the defining property of a mean: the mean squared deviation of a distribution around a point $t$ is its variance plus $(t - \\text{mean})^2$. The identity holds for the quadrature weights as well, to rounding error:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsapply(names(se_patterns), function(nm) {\n  pt <- eap_points[eap_points$pattern == nm, ]\n  curve <- se_df[se_df$pattern == nm, ]\n  max(abs(curve$SE - sqrt(pt$SE^2 + (curve$theta - pt$theta)^2)))\n})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n all incorrect (0 0 0 0 0)    all correct (1 1 1 1 1) \n              8.881784e-16               8.881784e-16 \n2 of 5 correct (1 0 1 0 0) \n              4.440892e-16 \n```\n\n\n:::\n:::\n\n\nSo the curves carry no information beyond the EAP estimate and its standard error, and the free `theta` argument is useful mainly for showing what the pairing `compute_eap_se_dichotomous(compute_eap_dichotomous(bank, x), bank, x)` is doing. In practice the two functions are always called that way.\n\n---\n\n## Worked example: guessing and slipping\n\nOne item, $a = 1.3$ and $b = 0.5$, in four versions: a 2PL item, a 3PL item with guessing $c = 0.2$, an item with slipping $d = 0.8$ and no guessing, and an item with both.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvariants <- list(\"2PL (c=0, d=1)\"          = c(1.3, 0.5, 0,   1),\n                 \"guessing (c=0.2, d=1)\"   = c(1.3, 0.5, 0.2, 1),\n                 \"slipping (c=0, d=0.8)\"   = c(1.3, 0.5, 0,   0.8),\n                 \"both (c=0.2, d=0.8)\"     = c(1.3, 0.5, 0.2, 0.8))\n\ngs_grid <- seq(-4, 5, by = 0.02)\ngs_curves <- do.call(rbind, lapply(names(variants), function(nm) {\n  it <- variants[[nm]]\n  data.frame(theta = gs_grid, version = nm,\n             P = compute_pi_dichotomous(gs_grid, it)$Pi,\n             information = compute_ii_dichotomous(gs_grid, it)$Ii)\n}))\ngs_curves$version <- factor(gs_curves$version, levels = names(variants))\ngs_long <- reshape2::melt(gs_curves, id.vars = c(\"theta\", \"version\"),\n                          variable.name = \"curve\", value.name = \"value\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gs_long, aes(x = theta, y = value, color = version)) +\n  geom_vline(xintercept = 0.5, linetype = \"dashed\", color = \"grey50\") +\n  geom_line(linewidth = 1) +\n  facet_wrap(~ curve, ncol = 1, scales = \"free_y\",\n             labeller = as_labeller(c(P = \"response probability\", information = \"item information\"))) +\n  labs(title = \"What c and d do to one item (a = 1.3, b = 0.5)\",\n       subtitle = \"dashed line: b\",\n       x = expression(theta), y = NULL, color = NULL) +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_dichotomous_files/figure-html/guess_slip_plot-1.png){width=60%}\n:::\n:::\n\n\nLocating each information peak numerically and comparing it with the closed-form predictions from the theory section: $b + \\log\\big((1+\\sqrt{1+8c})/2\\big)/(Da)$ for guessing, its mirror image $b - \\log\\big((1+\\sqrt{1+8(1-d)})/2\\big)/(Da)$ for slipping, and $b$ itself when $c = 1-d$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshift <- function(g, a, D = 1) log((1 + sqrt(1 + 8 * g)) / 2) / (D * a)\npredicted <- c(0.5, 0.5 + shift(0.2, 1.3), 0.5 - shift(1 - 0.8, 1.3), 0.5)\n\ngs_peaks <- do.call(rbind, lapply(seq_along(variants), function(i) {\n  it <- variants[[i]]\n  opt <- optimize(function(th) compute_ii_dichotomous(th, it)$Ii,\n                  interval = c(-4, 5), maximum = TRUE, tol = 1e-10)\n  data.frame(version = names(variants)[i], peak = opt$maximum, predicted = predicted[i],\n             max_information = opt$objective,\n             ratio_to_2PL_peak = opt$objective / (1.3^2 / 4))\n}))\ngs_peaks\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    version      peak predicted max_information\nbank         2PL (c=0, d=1) 0.5000000 0.5000000       0.4225000\nbank1 guessing (c=0.2, d=1) 0.7054938 0.7054938       0.2879516\nbank2 slipping (c=0, d=0.8) 0.2945062 0.2945062       0.2879516\nbank3   both (c=0.2, d=0.8) 0.5000000 0.5000000       0.1521000\n      ratio_to_2PL_peak\nbank          1.0000000\nbank1         0.6815422\nbank2         0.6815422\nbank3         0.3600000\n```\n\n\n:::\n:::\n\n\nThe guessing item's information peaks 0.205 above $b$ and the slipping item's the same distance below it, both where the formulas say. With both asymptotes and $c = 1 - d$ the two shifts cancel and the peak returns to $b$, just as in the item bank above. All three non-2PL versions lose information: 32% of the 2PL peak for $c = 0.2$ or $d = 0.8$ alone, and 64% with both, where the peak is $(d-c)^2 =$ 0.36 of the 2PL value. Guessing and slipping of the same size cost the same amount of information, because the slipping item is the guessing item reflected through $(b, 0.5)$.\n\nThe guessing formula is checked here for a range of $c$ at both metric constants, as the difference between the numerical peak and the prediction:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nformula_check <- expand.grid(c = c(0.05, 0.1, 0.2, 0.25, 0.35), D = c(1, 1.702))\nformula_check$numerical_minus_formula <- mapply(function(g, D) {\n  it <- c(1.3, 0.5, g, 1)\n  optimize(function(th) compute_ii_dichotomous(th, it, D = D)$Ii,\n           interval = c(-4, 5), maximum = TRUE, tol = 1e-10)$maximum - (0.5 + shift(g, 1.3, D))\n}, formula_check$c, formula_check$D)\nformula_check\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      c     D numerical_minus_formula\n1  0.05 1.000           -1.276698e-08\n2  0.10 1.000           -1.962512e-08\n3  0.20 1.000            1.634635e-09\n4  0.25 1.000            3.455876e-09\n5  0.35 1.000            7.003635e-09\n6  0.05 1.702            1.012235e-11\n7  0.10 1.702            1.522737e-11\n8  0.20 1.702            7.030289e-09\n9  0.25 1.702            1.072704e-08\n10 0.35 1.702           -1.011230e-08\n```\n\n\n:::\n:::\n\n\nThe differences are at the level of the optimiser's tolerance, so the formula in the roxygen note of `compute_ii_dichotomous()` holds, including its $1/D$ scaling.\n\n---\n\n## Worked example: the response pattern, not just the number correct\n\nTake every pattern with exactly two correct answers out of five (there are 10 of them) and score each under three versions of the Example 1 bank: a **1PL** version with every $a_j = 1$, the original **2PL** bank, and a **3PL** version with every $a_j = 1$ and $c_j = 0.2$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairs <- combn(5, 2)\ntwo_correct <- lapply(seq_len(ncol(pairs)), function(k) {\n  x <- rep(0, 5)\n  x[pairs[, k]] <- 1\n  x\n})\n\nbank_1pl <- bank_2pl\nbank_1pl[, \"a\"] <- 1\nbank_3pl <- bank_1pl\nbank_3pl[, \"c\"] <- 0.2\n\npattern_table <- data.frame(\n  pattern        = sapply(two_correct, paste, collapse = \" \"),\n  weighted_score = sapply(two_correct, function(x) sum(a_2pl * x)),\n  EAP_1PL        = sapply(two_correct, function(x) compute_eap_dichotomous(bank_1pl, x)),\n  EAP_2PL        = sapply(two_correct, function(x) compute_eap_dichotomous(bank_2pl, x)),\n  EAP_3PL        = sapply(two_correct, function(x) compute_eap_dichotomous(bank_3pl, x))\n)\npattern_table[order(pattern_table$EAP_2PL), ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     pattern weighted_score    EAP_1PL     EAP_2PL    EAP_3PL\n10 0 0 0 1 1         1.1176 -0.2762533 -0.55520429 -0.8866599\n3  1 0 0 1 0         1.3002 -0.2762533 -0.44477592 -0.5250563\n4  1 0 0 0 1         1.3216 -0.2762533 -0.43186436 -0.6637299\n6  0 1 0 1 0         1.3564 -0.2762533 -0.41087983 -0.5646559\n7  0 1 0 0 1         1.3778 -0.2762533 -0.39798249 -0.7072493\n1  1 1 0 0 0         1.5604 -0.2762533 -0.28811441 -0.3824532\n8  0 0 1 1 0         1.7338 -0.2762533 -0.18399237 -0.6834367\n9  0 0 1 0 1         1.7552 -0.2762533 -0.17115028 -0.8332303\n2  1 0 1 0 0         1.9378 -0.2762533 -0.06158777 -0.4798948\n5  0 1 1 0 0         1.9940 -0.2762533 -0.02785831 -0.5176594\n```\n\n\n:::\n\n```{.r .cell-code}\nc(range_1PL = diff(range(pattern_table$EAP_1PL)),\n  range_2PL = diff(range(pattern_table$EAP_2PL)),\n  range_3PL = diff(range(pattern_table$EAP_3PL)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   range_1PL    range_2PL    range_3PL \n1.665335e-16 5.273460e-01 5.042068e-01 \n```\n\n\n:::\n\n```{.r .cell-code}\nidentical(order(pattern_table$EAP_2PL), order(pattern_table$weighted_score))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\nThree models, three different answers to \"what does the estimate depend on?\":\n\n- **1PL.** All 10 patterns get the same estimate, -0.276253; the spread is at the level of rounding error. With equal discriminations and no asymptotes the number correct is sufficient, just as the raw score is in the Rating Scale and Partial Credit Model vignettes.\n- **2PL.** The estimates spread over 0.527 logits, and they are ordered exactly by the weighted score $\\sum_j a_jx_j$. The difficulties play no part: the two hardest items (4 and 5) give the *lowest* estimate of all, -0.555, because they are the two least discriminating items in the bank, while the highest estimate, -0.028, goes to the pattern 0 1 1 0 0, which includes item 3, the most discriminating one.\n- **3PL.** Even with equal discriminations the pattern matters again, now over 0.504 logits, and in the opposite direction from the 2PL: the two easiest items correct gives the highest estimate (-0.382) and the two hardest the lowest (-0.887). With a guessing floor, a correct answer to an item far too hard for the examinee is better explained as a lucky guess.\n\nThe 2PL claim can be made sharper. Under the 2PL two patterns with the same weighted score get the same estimate even when their numbers correct differ. With discriminations 0.5, 0.75 and 1.25 (all exactly representable in binary), getting the first two items right scores $0.5 + 0.75 = 1.25$, the same as getting only the third right:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbank_w <- matrix(c(0.5, 0.75, 1.25, -1, 0, 1, 0, 0, 0, 1, 1, 1), nrow = 3,\n                 dimnames = list(1:3, c(\"a\", \"b\", \"c\", \"d\")))\nbank_w_3pl <- bank_w\nbank_w_3pl[, \"c\"] <- 0.2\n\ndata.frame(pattern        = c(\"1 1 0\", \"0 0 1\"),\n           n_correct      = c(2, 1),\n           weighted_score = c(sum(bank_w[, \"a\"] * c(1, 1, 0)), sum(bank_w[, \"a\"] * c(0, 0, 1))),\n           EAP_2PL        = sprintf(\"%.12f\", c(compute_eap_dichotomous(bank_w, c(1, 1, 0)),\n                                               compute_eap_dichotomous(bank_w, c(0, 0, 1)))),\n           EAP_3PL        = sprintf(\"%.12f\", c(compute_eap_dichotomous(bank_w_3pl, c(1, 1, 0)),\n                                               compute_eap_dichotomous(bank_w_3pl, c(0, 0, 1)))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  pattern n_correct weighted_score        EAP_2PL         EAP_3PL\n1   1 1 0         2           1.25 0.163749566152  0.027986838554\n2   0 0 1         1           1.25 0.163749566152 -0.278655852616\n```\n\n\n:::\n:::\n\n\nUnder the 2PL two correct answers and one correct answer give identical estimates to twelve decimal places; adding a guessing parameter of 0.2 to every item separates them. This is what the discrimination parameter buys and what it costs. Better items count for more, which makes better use of the data; but the estimate can no longer be explained from the score sheet alone, and two examinees with the same number correct can legitimately receive different scores.\n\n---\n\n## Worked example: a short adaptive test\n\nFive items are too few for an adaptive test to choose anything, so this example generates a 40-item 4PL bank with discriminations between 0.8 and 2, difficulties spread around 0, guessing up to 0.25 and upper asymptotes between 0.9 and 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2024)\nn_items <- 40\nbank_cat <- cbind(a = round(runif(n_items, 0.8, 2.0), 2),\n                  b = round(rnorm(n_items, 0, 1.2), 2),\n                  c = round(runif(n_items, 0, 0.25), 2),\n                  d = round(runif(n_items, 0.9, 1.0), 2))\nrownames(bank_cat) <- 1:n_items\nhead(bank_cat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     a     b    c    d\n1 1.80  1.37 0.24 0.91\n2 1.19  0.38 0.02 0.98\n3 1.62  1.25 0.20 0.98\n4 1.64 -0.26 0.03 0.92\n5 1.35  0.48 0.18 0.98\n6 1.64 -1.85 0.00 0.98\n```\n\n\n:::\n:::\n\n\nAt each step the loop picks the most informative unadministered item at the current estimate, simulates a response from an examinee with true ability 1, and rescores.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\ntrue_theta <- 1.0\n\n# simulate a 0/1 response to item j from an examinee at theta\nsimulate_response <- function(j, theta) {\n  p <- compute_pi_dichotomous(theta, bank_cat[j, , drop = FALSE])$Pi\n  rbinom(1, 1, p)\n}\n\ntheta <- 0\nadministered <- integer(0)\nresponses <- integer(0)\ntrace <- data.frame()\n\nfor (step in 1:20) {\n  sel <- compute_next_item_dichotomous(theta, bank_cat, out = administered)\n  theta_before <- theta\n  administered <- c(administered, sel$item)\n  responses <- c(responses, simulate_response(sel$item, true_theta))\n\n  sub_bank <- bank_cat[administered, , drop = FALSE]\n  theta <- compute_eap_dichotomous(sub_bank, responses)\n  se <- compute_eap_se_dichotomous(theta, sub_bank, responses)\n\n  trace <- rbind(trace, data.frame(step = step, theta_before = theta_before, item = sel$item,\n                                   a = bank_cat[sel$item, \"a\"], b = bank_cat[sel$item, \"b\"],\n                                   information = unname(sel$info),\n                                   response = tail(responses, 1),\n                                   theta_EAP = theta, SE = se))\n}\nrownames(trace) <- NULL\ntrace\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   step theta_before item    a     b information response theta_EAP        SE\n1     1    0.0000000   38 1.96 -0.29   0.7741458        1 0.4994706 0.8148179\n2     2    0.4994706   28 1.78  0.80   0.5790472        1 0.9300785 0.7631718\n3     3    0.9300785   23 1.62  0.59   0.4768977        1 1.2003800 0.6954405\n4     4    1.2003800    3 1.62  1.25   0.4068768        0 0.9162451 0.6117131\n5     5    0.9162451   16 1.81  0.47   0.4577606        1 1.0560148 0.5790796\n6     6    1.0560148   27 1.54  0.39   0.3502425        0 0.7679117 0.5393279\n7     7    0.7679117   40 1.58 -0.04   0.3854264        0 0.4756732 0.5150931\n8     8    0.4756732   12 1.94 -0.39   0.4165912        1 0.5641784 0.4789634\n9     9    0.5641784    2 1.19  0.38   0.3220779        1 0.6734847 0.4652500\n10   10    0.6734847    5 1.35  0.48   0.3029440        1 0.7570965 0.4581241\n11   11    0.7570965   14 1.42  1.45   0.2643348        0 0.6795539 0.4370484\n12   12    0.6795539    4 1.64 -0.26   0.2486879        1 0.7342323 0.4235285\n13   13    0.7342323   20 1.15  0.51   0.2199065        0 0.6362468 0.4106558\n14   14    0.6362468   26 1.15  0.16   0.2011803        1 0.6809798 0.4067322\n15   15    0.6809798    8 1.16  0.82   0.1936899        0 0.6044335 0.3956015\n16   16    0.6044335   13 1.64 -0.61   0.1826315        1 0.6371167 0.3872493\n17   17    0.6371167    7 1.30 -0.14   0.1770243        1 0.6778974 0.3819418\n18   18    0.6778974    1 1.80  1.37   0.1841058        1 0.7527370 0.3893765\n19   19    0.7527370   22 0.93 -0.01   0.1609148        1 0.7923930 0.3864475\n20   20    0.7923930   37 0.86  1.07   0.1509293        1 0.8559116 0.3851877\n```\n\n\n:::\n:::\n\n\n`catR::nextItem()` is then asked the same question at every step: the same estimate, the same items already given. The check runs after the loop rather than inside it because `catR::nextItem()` draws from the random-number stream even when there is nothing to draw between, and calling it inside the loop would change the simulated responses:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1); invisible(catR::nextItem(bank_cat, theta = 0, criterion = \"MFI\")); after_catR <- runif(1)\nset.seed(1); untouched <- runif(1)\nc(runif_after_catR_nextItem = after_catR, runif_untouched = untouched)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrunif_after_catR_nextItem           runif_untouched \n                0.2198273                 0.2655087 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrace$catR_item <- sapply(seq_len(nrow(trace)), function(k)\n  catR::nextItem(bank_cat, theta = trace$theta_before[k],\n                 out = administered[seq_len(k - 1)], criterion = \"MFI\")$item)\nall(trace$item == trace$catR_item)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nc(final_mine = theta,\n  final_catR = catR::eapEst(bank_cat[administered, ], responses),\n  se_mine    = se,\n  se_catR    = catR::eapSem(theta, bank_cat[administered, ], responses))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfinal_mine final_catR    se_mine    se_catR \n 0.8559116  0.8559116  0.3851877  0.3851877 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(trace, aes(x = step, y = theta_EAP)) +\n  geom_hline(yintercept = true_theta, linetype = \"dashed\", color = \"grey40\") +\n  geom_ribbon(aes(ymin = theta_EAP - SE, ymax = theta_EAP + SE),\n              alpha = 0.2, fill = \"steelblue\") +\n  geom_line(color = \"steelblue\", linewidth = 1) +\n  geom_point(size = 2, color = \"steelblue\") +\n  annotate(\"text\", x = 1, y = true_theta + 0.08, hjust = 0,\n           label = \"true theta\", color = \"grey40\", size = 3.5) +\n  scale_x_continuous(breaks = trace$step) +\n  labs(title = \"Adaptive test: EAP estimate (± 1 SE) after each item\",\n       x = \"item administered\", y = expression(hat(theta)[EAP])) +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](eap_dichotomous_files/figure-html/adaptive_plot-1.png){width=60%}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(first_item_a         = trace$a[1],\n  mean_a_first_5       = mean(trace$a[1:5]),\n  mean_a_last_5        = mean(trace$a[16:20]),\n  mean_a_bank          = mean(bank_cat[, \"a\"]),\n  steps_where_SE_rose  = sum(diff(trace$SE) > 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       first_item_a      mean_a_first_5       mean_a_last_5         mean_a_bank \n            1.96000             1.75800             1.30600             1.41025 \nsteps_where_SE_rose \n            1.00000 \n```\n\n\n:::\n\n```{.r .cell-code}\ntrace$step[c(FALSE, diff(trace$SE) > 0)]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 18\n```\n\n\n:::\n:::\n\n\n`catR` picks the same item at every one of the 20 steps, and the final estimate and standard error agree with `catR`'s. After 20 items the estimate is 0.856 with a standard error of 0.385, down from 0.815 after the first item. The fall is not strictly monotone: the standard error rose 1 time(s), at step(s) 18. For dichotomous items a response that contradicts the current estimate can widen the posterior, so a posterior standard deviation, unlike the asymptotic $1/\\sqrt{\\text{test information}}$, need not shrink with every item.\n\nThe item choices show the discrimination at work. MFI opens with the most informative item at $\\theta = 0$, which has $a =$ 1.96, and the first five items average $a =$ 1.76 against a bank average of 1.41. By the last five steps the best items near the estimate are used up and the average has fallen to 1.31. Pure MFI spends the strongest items first.\n\n### Exposure control\n\nPure MFI is deterministic: every examinee starting at $\\theta = 0$ receives the same first item. The `randomesque` argument draws at random from the $k$ best instead.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\nexposure_1 <- table(replicate(2000, compute_next_item_dichotomous(theta = 0, bank_cat, randomesque = 1)$item))\nexposure_5 <- table(replicate(2000, compute_next_item_dichotomous(theta = 0, bank_cat, randomesque = 5)$item))\nexposure_1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  38 \n2000 \n```\n\n\n:::\n\n```{.r .cell-code}\nexposure_5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  4  12  18  38  40 \n396 419 382 399 404 \n```\n\n\n:::\n:::\n\n\nWith `randomesque = 1` item 38 is chosen 2000 times out of 2000. With `randomesque = 5` the load is spread over 5 items, each chosen between 382 and 419 times. In a 4PL bank the price is higher than in a Rasch-family bank, because the runners-up are not just slightly off target but genuinely less informative items:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninfo_at_0 <- compute_ii_dichotomous(theta = 0, bank_cat)$Ii\ntop_5 <- sort(info_at_0, decreasing = TRUE)[1:5]\nround(top_5, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   38    12    40     4    18 \n0.774 0.746 0.564 0.496 0.428 \n```\n\n\n:::\n\n```{.r .cell-code}\nc(best_item          = max(info_at_0),\n  mean_of_top_5      = mean(top_5),\n  proportion_of_best = mean(top_5) / max(info_at_0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         best_item      mean_of_top_5 proportion_of_best \n         0.7741458          0.6015497          0.7770497 \n```\n\n\n:::\n:::\n\n\nSpreading the first item over the five best retains on average 78% of the information of always taking the single best: the standard trade-off between measurement efficiency and item security, and one that is steeper when discriminations vary.\n\n---\n\n## Worked example: the numerical settings\n\nThe EAP integrals are approximations, and four arguments control them. None of these is a free choice to make casually. The all-correct pattern on the item bank is the hardest case, because its likelihood never comes back down:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(1, 1, 1, 1, 1)\n\nsettings <- rbind(\n  data.frame(setting = \"quadrature points\", value = c(11, 33, 101, 501),\n             theta = sapply(c(11, 33, 101, 501),\n                            function(n) compute_eap_dichotomous(bank, x, nqp = n))),\n  data.frame(setting = \"integration bound\", value = c(3, 4, 6),\n             theta = sapply(c(3, 4, 6),\n                            function(b) compute_eap_dichotomous(bank, x, lower = -b, upper = b))),\n  data.frame(setting = \"prior SD\", value = c(1, 2),\n             theta = sapply(c(1, 2),\n                            function(s) compute_eap_dichotomous(bank, x, priorPar = c(0, s)))),\n  data.frame(setting = \"metric constant D\", value = c(1, 1.702),\n             theta = sapply(c(1, 1.702),\n                            function(d) compute_eap_dichotomous(bank, x, D = d)))\n)\nsettings\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             setting   value    theta\n1  quadrature points  11.000 1.347322\n2  quadrature points  33.000 1.349811\n3  quadrature points 101.000 1.350068\n4  quadrature points 501.000 1.350097\n5  integration bound   3.000 1.262503\n6  integration bound   4.000 1.349811\n7  integration bound   6.000 1.354500\n8           prior SD   1.000 1.349811\n9           prior SD   2.000 2.707759\n10 metric constant D   1.000 1.349811\n11 metric constant D   1.702 1.398733\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nThree different kinds of effect are visible here, and they should not be confused with one another:\n\n- **Quadrature points** are pure approximation error. Moving from 11 to 33 points changes the estimate by 0.0025, and from 101 to 501 by 0.00003. The default of 33 is a reasonable accuracy/speed compromise and matches `catR`.\n- **Integration bounds** are also approximation error, but of a more dangerous kind. Truncating at $\\pm 3$ moves the estimate from 1.350 to 1.263, because for an all-correct pattern the posterior still has real mass beyond $\\theta = 3$ and cutting it off silently biases the estimate downward. Widening to $\\pm 6$ changes it by only 0.0047. Bounds must be wide enough for the *most extreme pattern the bank can produce*, not for a typical one.\n- **The prior SD and the metric constant are not approximation error at all**: they are different models. Doubling the prior SD to 2 weakens the shrinkage and moves the estimate from 1.35 to 2.71; with $d_j = 0.9$ the likelihood of this pattern flattens out at $\\prod_j d_j$ in the upper tail (see the likelihood plot above), so out there only the prior shapes the posterior and a wider prior lets the estimate travel much further. Changing $D$ to 1.702 rescales every discrimination and moves the estimate to 1.40. Both belong in the model specification and must match whatever was used to calibrate the item parameters.\n\n---\n\n# Conclusion\n\nAll eight functions reproduce their `catR` counterparts to machine precision: the normal density and the trapezoidal integrator in `cat_eap_common.R`, and in `cat_eap_dichotomous.R` the 4PL probabilities with their three derivatives, the item information with its two derivatives, MFI item selection with and without excluded items, the likelihood, and the two integrals that define EAP scoring. Finite differences confirm the derivative formulas independently of `catR`, at both metric constants. Together the functions run a complete dichotomous adaptive test in a few hundred lines of base R.\n\nWritten out, the model's character is easy to see. The discrimination sets how useful an item can be, so information curves differ in height and MFI has to compute them all rather than look for the nearest difficulty; it also makes the response pattern, not only the number correct, drive the estimate. The guessing and slipping asymptotes lower the information and pull its peak away from $b$, in opposite directions, in the amounts the closed-form expression predicts. The probability floor keeps the information finite when a probability rounds to 1. And the prior does what it does in every EAP model: it keeps estimates and standard errors finite for the all-correct and all-incorrect patterns that short tests produce routinely, at the cost of a known, deliberate pull toward the prior mean.\n\n---\n\n# References\n\n- Barton, M. A., & Lord, F. M. (1981). *An upper asymptote for the three-parameter logistic item-response model* (ETS Research Report RR-81-20). Educational Testing Service.\n- Birnbaum, A. (1968). Some latent trait models and their use in inferring an examinee's ability. In F. M. Lord & M. R. Novick, *Statistical theories of mental test scores*. Addison-Wesley.\n- Bock, R. D., & Mislevy, R. J. (1982). Adaptive EAP estimation of ability in a microcomputer environment. *Applied Psychological Measurement, 6*(4), 431–444.\n- Magis, D., & Barrada, J. R. (2017). Computerized adaptive testing with R: Recent updates of the package catR. *Journal of Statistical Software, Code Snippets, 76*(1), 1–19. https://doi.org/10.18637/jss.v076.c01\n- Magis, D., & Raîche, G. (2012). Random generation of response patterns under computerized adaptive testing with the R package catR. *Journal of Statistical Software, 48*(8), 1–31. https://doi.org/10.18637/jss.v048.i08\n\n---\n\n*Rendered with R 4.6.1 · validated against catR 3.17*\n\n---\n\n# Comments\n\nQuestions, corrections and suggestions are welcome below (sign in with GitHub to post).\n\n```{=html}\n<div class=\"giscus\"></div>\n<script>\n(function () {\n  var s = document.createElement(\"script\");\n  s.src = \"https://giscus.app/client.js\";\n  s.setAttribute(\"data-repo\", \"sedzinfo/rwf\");\n  s.setAttribute(\"data-repo-id\", \"REPLACE_WITH_REPO_ID\");\n  s.setAttribute(\"data-category\", \"Comments\");\n  s.setAttribute(\"data-category-id\", \"REPLACE_WITH_CATEGORY_ID\");\n  s.setAttribute(\"data-mapping\", \"specific\");\n  s.setAttribute(\"data-term\", \"EAP Dichotomous Ability Estimation in base R\");\n  s.setAttribute(\"data-strict\", \"1\");\n  s.setAttribute(\"data-reactions-enabled\", \"1\");\n  s.setAttribute(\"data-emit-metadata\", \"0\");\n  s.setAttribute(\"data-input-position\", \"top\");\n  s.setAttribute(\"data-theme\", \"light\");\n  s.setAttribute(\"data-lang\", \"en\");\n  s.setAttribute(\"data-loading\", \"lazy\");\n  s.crossOrigin = \"anonymous\";\n  s.async = true;\n  document.querySelector(\".giscus\").appendChild(s);\n})();\n</script>\n```\n",
    "supporting": [
      "eap_dichotomous_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}